#!/usr/bin/env python3
"""Run the one-shot loop with a real LLM call to generate the bridge translator spec.

This is the Phase 4 bootstrap act: the first time the system uses its own
one-shot loop + LLM to produce a verified PlusCal spec, rather than hand-writing it.

Flow:
  1. Load registry DAG, query context for gwt-0008 (bridge behavior)
  2. Build prompt with registry context + state machine template
  3. Send prompt to Claude via claude-agent-sdk
  4. Feed LLM response through OneShotLoop.process_response() → TLC verification
  5. If RETRY, send counterexample feedback → LLM → process_response() again
  6. If PASS, the verified spec defines the bridge translator contract

Uses: claude-agent-sdk (Claude Code Agent SDK)
"""

import asyncio
import os
import sys
from pathlib import Path

# Must unset CLAUDECODE to allow launching a sub-session from within Claude Code
os.environ.pop("CLAUDECODE", None)

import claude_agent_sdk

# Add python/ to path so registry imports work
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "python"))

from registry.context import ProjectContext
ctx = ProjectContext.self_hosting(PROJECT_ROOT)
ctx.session_dir.mkdir(parents=True, exist_ok=True)

LOG_FILE = ctx.session_dir / "bridge_loop_output.log"
_log_fh = open(LOG_FILE, "w")


def log(msg: str) -> None:
    """Print to both log file and stdout."""
    print(msg, flush=True)
    _log_fh.write(msg + "\n")
    _log_fh.flush()

from registry.extractor import SchemaExtractor
from registry.one_shot_loop import OneShotLoop, LoopResult


# TLC model checking config for the bridge translator
BRIDGE_CFG = """\
\\* Bridge translator TLC config (generated by run_bridge_loop.py)
SPECIFICATION Spec

CONSTANTS
    MaxSteps = 20
    NumVariables = 3
    NumActions = 4
    NumInvariants = 2

INVARIANTS
    ValidState
    BoundedExecution
    OutputConformsToSchema
    TranslationOrder
    NoPartialOutput
    InputPreserved
"""


def build_prompt(loop: OneShotLoop) -> str:
    """Build the LLM prompt from registry context + instructions."""
    # Query registry context for gwt-0008 (state variable translation)
    loop.query("gwt-0008")
    context = loop.format_prompt()

    # Read the state machine template for reference
    template_path = ctx.template_dir / "state_machine.tla"
    template_text = template_path.read_text()

    return f"""You are generating a PlusCal specification for a bridge translator —
a mechanical pipeline that converts TLA+ specs into code artifacts.

## Registry Context (from the DAG)

{context}

## State Machine Template (use this pattern)

```tla
{template_text}
```

## Requirements

Generate a COMPLETE PlusCal specification (inside a TLA+ module) for a bridge
translator state machine with these characteristics:

**Module name:** bridge_translator (the MODULE name MUST be bridge_translator)

**States:** idle, parsing_spec, translating_vars, translating_actions,
translating_invariants, translating_traces, validating_output, done, failed

**Transitions:**
- idle → parsing_spec: spec received
- parsing_spec → translating_vars: spec parsed successfully
- parsing_spec → failed: spec cannot be parsed
- translating_vars → translating_actions: state vars → data_structures done
- translating_actions → translating_invariants: actions → operations done
- translating_invariants → translating_traces: invariants → verifiers + assertions done
- translating_traces → validating_output: traces → test scenarios done
- validating_output → done: all outputs conform to schemas
- validating_output → failed: output does not conform

**CONSTANTS:** MaxSteps, NumVariables, NumActions, NumInvariants

**State variables (beyond current_state):**
- vars_found, actions_found, invariants_found (set during parsing from CONSTANTS)
- has_traces (boolean, TRUE if NumInvariants > 0)
- data_structures_out, operations_out, verifiers_out, assertions_out, scenarios_out (output counters)
- schema_valid (boolean), input_hash (integer, set during parsing)
- step_count, op, result, dirty (control variables)

**Invariants (in define block):**
- ValidState: current_state \\in StateSet
- BoundedExecution: step_count <= MaxSteps
- OutputConformsToSchema: when done, output counts match input counts
  (data_structures_out = vars_found, operations_out = actions_found,
   verifiers_out = invariants_found, assertions_out = invariants_found)
- TranslationOrder: each translator only runs after its predecessor completed
- NoPartialOutput: done implies all translators produced output
- InputPreserved: input_hash > 0 after parsing

**Two-phase action model:** Use a `dirty` flag. Set dirty=TRUE when mutating
primary state, then set dirty=FALSE when derived state is consistent. Gate
invariants on derived state with `dirty = TRUE \\/` prefix.

**Process:** Single fair process "main" with a while loop that terminates
when current_state is in done/failed or step_count >= MaxSteps. Use
`either/or` for nondeterministic choice between transitions.

**PlusCal LABEL RULES (CRITICAL — pcal.trans will reject without these):**

In PlusCal, when you have an `if` statement inside an `either` branch, and the
if body contains multiple assignments OR the else branch exists, you MUST add
a label AFTER the first assignment in each branch. PlusCal requires labels at
"control flow join points."

CORRECT pattern (two-phase with labels):
```
either
    ActionLabel:
        if guard then
            \* first assignments
            var1 := val1;
            dirty := TRUE;
            step_count := step_count + 1;
        ActionDecide:
            \* second phase — state transition
            current_state := "next_state";
            dirty := FALSE;
        else
            op := "skip";
        end if;
or
    ...
end either;
```

The key: after the initial assignments in the `if` branch, add a NEW label
before additional assignments. This is the "two-phase action model" — Phase 1
mutates data, Phase 2 transitions state. Each phase needs its own label.

Look at this working example from the one_shot_loop.tla for reference:
```
either
    ParseSpec:
        if current_state = "parsing_spec" then
            vars_found := NumVariables;
            actions_found := NumActions;
            input_hash := NumVariables + NumActions + 1;
            dirty := TRUE;
            step_count := step_count + 1;
        ParseDecide:
            if NumVariables >= 0 then
                current_state := "translating_vars";
            else
                current_state := "failed";
            end if;
            dirty := FALSE;
        else
            op := "parse_skip";
        end if;
or
```

**OUTPUT FORMAT:** Output ONLY the PlusCal algorithm inside a TLA+ module.
Do NOT include the compiled TLA+ translation — pcal.trans will generate that.
The module should contain:
1. MODULE line
2. EXTENDS
3. CONSTANTS
4. (* --algorithm ... end algorithm; *)
5. The closing ===... line

The module name in the MODULE line MUST be `bridge_translator`.
Use EXTENDS Integers, FiniteSets, Sequences, TLC.
"""


async def run_loop() -> None:
    """Execute the one-shot loop with real LLM calls."""
    log("=" * 70)
    log("Phase 4 Bootstrap: One-Shot Loop → Bridge Translator Spec")
    log("=" * 70)

    # Step 1: Load registry DAG
    log("\n[1/5] Loading registry DAG...")
    extractor = SchemaExtractor(schema_dir=str(ctx.schema_dir), self_host=ctx.is_self_hosting)
    dag = extractor.extract()
    log(f"  DAG: {len(dag.nodes)} nodes, {len(dag.edges)} edges")

    # Step 2: Initialize loop and build prompt
    log("\n[2/5] Querying registry context for gwt-0008...")
    loop = OneShotLoop(dag=dag, ctx=ctx)
    prompt = build_prompt(loop)
    log(f"  Prompt length: {len(prompt)} chars")

    # Step 3: Send to LLM via claude-agent-sdk
    log("\n[3/5] Sending prompt to Claude via Agent SDK...")
    llm_response = await call_llm(prompt)
    log(f"  Response length: {len(llm_response)} chars")

    # Save the raw LLM response for inspection
    response_file = ctx.session_dir / "bridge_llm_response.txt"
    response_file.write_text(llm_response)
    log(f"  Saved raw response to {response_file}")

    # Step 4: Process through the loop (extract → compile → TLC)
    log("\n[4/5] Processing response through one-shot loop pipeline...")
    status = loop.process_response(
        llm_response=llm_response,
        module_name="bridge_translator",
        cfg_text=BRIDGE_CFG,
    )

    log(f"  Result: {status.result}")
    if status.tlc_result:
        log(f"  TLC states: {status.tlc_result.states_found} found, "
            f"{status.tlc_result.states_distinct} distinct")
        if not status.tlc_result.success:
            log(f"  TLC error: {status.tlc_result.error_message}")
            log(f"  TLC output (last 500 chars): {status.tlc_result.raw_output[-500:]}")

    # Step 5: Handle retry if needed
    if status.result == LoopResult.RETRY:
        log("\n[5/5] TLC found issue — retrying with counterexample feedback...")

        retry_prompt = build_retry_prompt(status, prompt)
        llm_response_2 = await call_llm(retry_prompt)
        log(f"  Retry response length: {len(llm_response_2)} chars")

        # Save retry response too
        retry_file = ctx.session_dir / "bridge_llm_response_retry.txt"
        retry_file.write_text(llm_response_2)

        status = loop.process_response(
            llm_response=llm_response_2,
            module_name="bridge_translator",
            cfg_text=BRIDGE_CFG,
        )
        log(f"  Retry result: {status.result}")
        if status.tlc_result:
            log(f"  TLC states: {status.tlc_result.states_found} found, "
                f"{status.tlc_result.states_distinct} distinct")
            if not status.tlc_result.success:
                log(f"  TLC error: {status.tlc_result.error_message}")

    # Report final outcome
    log("\n" + "=" * 70)
    if status.result == LoopResult.PASS:
        log("SUCCESS: Bridge translator spec verified by TLC!")
        log("The one-shot loop generated a formally verified PlusCal spec.")
        log("This is the first component built BY the pipeline, not by hand.")
    elif status.result == LoopResult.FAIL:
        log("FAILED: Requirements inconsistency detected.")
        log(f"  Error: {status.error}")
        if status.tlc_result:
            log(f"  TLC output (last 1000): {status.tlc_result.raw_output[-1000:]}")
    else:
        log(f"Unexpected result: {status.result}")

    log("=" * 70)


async def call_llm(prompt: str) -> str:
    """Call Claude via the Agent SDK and collect the text response."""
    options = claude_agent_sdk.ClaudeAgentOptions(
        # No tools needed — we just want text generation
        allowed_tools=[],
        system_prompt=(
            "You are a TLA+/PlusCal expert. Generate complete, syntactically correct "
            "PlusCal specifications embedded in TLA+ modules. Output ONLY the TLA+ module "
            "content — no markdown fencing, no explanation, no commentary. The output must "
            "be directly compilable by pcal.trans and verifiable by TLC."
        ),
        max_turns=1,
        model="claude-sonnet-4-20250514",
    )

    result_text = []
    async for message in claude_agent_sdk.query(prompt=prompt, options=options):
        if isinstance(message, claude_agent_sdk.AssistantMessage):
            for block in message.content:
                if isinstance(block, claude_agent_sdk.TextBlock):
                    result_text.append(block.text)
        elif isinstance(message, claude_agent_sdk.ResultMessage):
            if message.result:
                result_text.append(message.result)

    return "\n".join(result_text)


def build_retry_prompt(status, original_prompt: str) -> str:
    """Build a retry prompt incorporating the counterexample feedback."""
    parts = [original_prompt, "\n\n## RETRY — Previous Attempt Failed\n"]

    if status.counterexample:
        parts.append(f"TLC found a counterexample:\n\n{status.counterexample.pluscal_summary}\n")

    if status.tlc_result and status.tlc_result.error_message:
        parts.append(f"Error: {status.tlc_result.error_message}\n")

    if status.tlc_result and status.tlc_result.raw_output:
        # Include relevant portion of TLC output
        raw = status.tlc_result.raw_output
        # Find error section
        error_start = raw.find("Error:")
        if error_start >= 0:
            parts.append(f"TLC output (error section):\n{raw[error_start:error_start+1000]}\n")

    parts.append(
        "\nFix the specification to resolve this issue. Output the COMPLETE "
        "corrected TLA+ module. Remember: the MODULE name MUST be bridge_translator."
    )

    return "\n".join(parts)


if __name__ == "__main__":
    asyncio.run(run_loop())
