#!/usr/bin/env python3
"""Run the one-shot loop to generate a subgraph extraction spec (Phase 7 self-hosting).

Third feature built through the pipeline:
  1. Plain language requirement → GWT behaviors (registered in DAG)
  2. Registry context → LLM prompt → PlusCal spec → TLC verification
  3. Bridge → test generation
  4. Implementation to pass the tests
"""

import asyncio
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Must unset CLAUDECODE to allow launching a sub-session from within Claude Code
os.environ.pop("CLAUDECODE", None)

import claude_agent_sdk

# Add python/ to path so registry imports work
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "python"))

LOG_FILE = PROJECT_ROOT / "subgraph_loop_output.log"
_log_fh = open(LOG_FILE, "w")

MAX_RETRIES = 5
MODULE_NAME = "subgraph_extraction"
GWT_ID = "gwt-0018"


def log(msg: str) -> None:
    print(msg, flush=True)
    _log_fh.write(msg + "\n")
    _log_fh.flush()


def banner(msg: str) -> None:
    log("")
    log("=" * 70)
    log(f"  {msg}")
    log("=" * 70)
    log("")


def step(num: int, total: int, msg: str) -> None:
    log(f"  [{num}/{total}] {msg}")


from registry.extractor import SchemaExtractor
from registry.one_shot_loop import OneShotLoop, LoopResult
from registry.bridge import run_bridge


# TLC config for the subgraph extraction spec
SUBGRAPH_CFG = """\
\\* Subgraph extraction TLC config (generated by run_subgraph_loop.py)
SPECIFICATION Spec

CONSTANTS
    MaxSteps = 15
    NumNodes = 4
    MaxEdges = 5

INVARIANTS
    ValidState
    BoundedExecution
    SubgraphCompleteness
    NoHoles
    NoDanglingEdges
    IsolatedNodeCorrect
"""


def build_initial_prompt(loop: OneShotLoop) -> str:
    """Build the initial LLM prompt from registry context + instructions."""
    loop.query(GWT_ID)
    context = loop.format_prompt()

    template_path = PROJECT_ROOT / "templates" / "pluscal" / "state_machine.tla"
    template_text = template_path.read_text()

    return f"""You are generating a PlusCal specification for a subgraph extraction query —
a function that, given a target node in a DAG, returns the minimal subgraph needed to
understand that node. The subgraph includes all ancestors (reverse closure), all
descendants (forward closure), the node itself, and all edges where both endpoints
are in that node set.

## Registry Context (from the DAG)

{context}

## State Machine Template (use this pattern)

```tla
{template_text}
```

## Requirements

Generate a COMPLETE PlusCal specification (inside a TLA+ module) for a subgraph
extraction state machine with these characteristics:

**Module name:** {MODULE_NAME} (the MODULE name MUST be {MODULE_NAME})

**The problem:** Given a directed acyclic graph with NumNodes nodes (1..NumNodes) and
an adjacency relation, and a target node T, compute:
1. **Forward closure:** all nodes reachable from T (descendants)
2. **Reverse closure:** all nodes that can reach T (ancestors)
3. **Node set:** forward closure UNION reverse closure UNION {{T}}
4. **Edge set:** all edges (i,j) in the full graph where BOTH i and j are in the node set

**CONSTANTS:** MaxSteps, NumNodes, MaxEdges

**States:** idle, building_graph, selecting_target, computing_forward,
computing_reverse, collecting_edges, done, failed

**State variables (beyond current_state):**
- adjacency: function from 1..NumNodes to sets of node IDs (successors)
- edge_count: number of edges in the graph
- target: the selected target node (0 = not selected)
- forward_set: set of nodes reachable FROM target (computed via BFS)
- reverse_set: set of nodes that can REACH target (computed via BFS on reversed graph)
- subgraph_nodes: final node set (forward_set UNION reverse_set UNION {{target}})
- subgraph_edges: set of <<i,j>> tuples where both i,j in subgraph_nodes
- fw_worklist: BFS worklist for forward traversal
- fw_visited: visited set for forward BFS
- rv_worklist: BFS worklist for reverse traversal
- rv_visited: visited set for reverse BFS
- step_count, op, result, dirty (control variables)

**Transitions:**
- idle → building_graph: initialize adjacency = [n \\in 1..NumNodes |-> {{}}], edge_count = 0

- building_graph → building_graph: nondeterministically add forward edges (i < j only,
  to maintain DAG property). Up to MaxEdges edges total.

- building_graph → selecting_target: done adding edges.

- selecting_target → computing_forward: pick target from 1..NumNodes nondeterministically.
  Initialize forward BFS: fw_worklist = adjacency[target], fw_visited = {{}}, forward_set = {{}}.

- computing_forward → computing_forward: BFS step. Pick node from fw_worklist,
  add to fw_visited and forward_set, add its unvisited successors to fw_worklist.

- computing_forward → computing_reverse: fw_worklist is empty, forward BFS complete.
  Initialize reverse BFS. Build reverse adjacency inline:
  rv_worklist = {{n \\in 1..NumNodes : target \\in adjacency[n]}},
  rv_visited = {{}}, reverse_set = {{}}.

- computing_reverse → computing_reverse: BFS step on reverse graph. Pick node from
  rv_worklist, add to rv_visited and reverse_set, add nodes that have edges TO this
  node (i.e., {{m \\in 1..NumNodes : n \\in adjacency[m]}} minus visited) to rv_worklist.

- computing_reverse → collecting_edges: rv_worklist is empty, reverse BFS complete.
  Compute subgraph_nodes = forward_set \\union reverse_set \\union {{target}}.
  Compute subgraph_edges = {{<<i,j>> \\in (subgraph_nodes \\X subgraph_nodes) :
    j \\in adjacency[i]}}.

- collecting_edges → done: finalize result.

- any state → failed: step_count >= MaxSteps

**Invariants (in define block):**
- ValidState: current_state \\in StateSet
- BoundedExecution: step_count <= MaxSteps
- SubgraphCompleteness: when done, for every node n in subgraph_nodes and every
  successor s in adjacency[n], if s is reachable from target OR target is reachable
  from s (through existing edges), then s is also in subgraph_nodes.
  Guard with dirty.
- NoHoles: when done, if node A is in subgraph_nodes and edge A→B exists in the
  full graph, and B is in the forward closure of target OR B can reach target,
  then B must also be in subgraph_nodes. Guard with dirty.
- NoDanglingEdges: when done, for every <<i,j>> in subgraph_edges, both i and j
  must be in subgraph_nodes. Guard with dirty.
- IsolatedNodeCorrect: when done, if target has no edges in or out (adjacency[target] = {{}}
  AND no node has target in its adjacency set), then subgraph_nodes = {{target}}
  AND subgraph_edges = {{}}. Guard with dirty.

**Two-phase action model:** Use a `dirty` flag. Set dirty=TRUE when mutating
primary state, then set dirty=FALSE when derived state is consistent. Gate
invariants on dirty with `dirty = TRUE \\/` prefix.

**Process:** Single fair process "main" with a while loop that terminates
when current_state is in done/failed or step_count >= MaxSteps. Use
`either/or` for nondeterministic choice between transitions.

**PlusCal LABEL RULES (CRITICAL — pcal.trans will reject without these):**

In PlusCal, when you have an `if` statement inside an `either` branch, and the
if body contains multiple assignments OR the else branch exists, you MUST add
a label AFTER the first group of assignments in the if branch. PlusCal requires
labels at "control flow join points."

CORRECT pattern (two-phase with labels):
```
either
    ActionLabel:
        if guard then
            \\* first assignments (Phase 1: mutate data)
            var1 := val1;
            dirty := TRUE;
            step_count := step_count + 1;
        ActionDecide:
            \\* second phase (Phase 2: transition state)
            current_state := "next_state";
            dirty := FALSE;
        else
            op := "skip";
        end if;
or
    ...
end either;
```

**PlusCal `with` RULES (CRITICAL — pcal.trans will reject violations):**

1. You CANNOT put a label inside a `with` statement.
2. You CANNOT assign to the same variable twice inside a single `with` block.
3. Keep `with` blocks simple: use only for nondeterministic choice (like
   picking from worklist), with assignments to DIFFERENT variables.
4. After the `with`/`end with`, you can have more assignments and labels.

Example of correct `with` usage for BFS:
```
BFSStep:
    if current_state = "computing_forward" /\\ fw_worklist # {{}} then
        with n \\in fw_worklist do
            fw_visited := fw_visited \\union {{n}};
            fw_worklist := (fw_worklist \\ {{n}}) \\union
                {{s \\in adjacency[n] : s \\notin fw_visited}};
            forward_set := forward_set \\union {{n}};
        end with;
        step_count := step_count + 1;
        dirty := TRUE;
    BFSStepDone:
        op := "fw_bfs_step";
        dirty := FALSE;
    else
        op := "skip_fw_bfs";
    end if;
```

**IMPORTANT adjacency representation:**
Initialize: adjacency = [n \\in 1..NumNodes |-> {{}}]
To add edge i→j: adjacency := [adjacency EXCEPT ![i] = adjacency[i] \\union {{j}}]
Only allow i < j during graph building (DAG constraint). No self-loops.

**IMPORTANT: Reverse adjacency for reverse BFS:**
The reverse graph successors of node n are: {{m \\in 1..NumNodes : n \\in adjacency[m]}}
This gives all nodes that have an edge TO n in the original graph.

**OUTPUT FORMAT:** Output ONLY the TLA+ module — no markdown fencing, no
explanation, no commentary. The module should contain:
1. MODULE line (MUST be `{MODULE_NAME}`)
2. EXTENDS Integers, FiniteSets, Sequences, TLC
3. CONSTANTS
4. (* --algorithm ... end algorithm; *)
5. The closing ===... line
"""


def build_retry_prompt(original_prompt: str, attempt: int, error_msg: str,
                       tlc_output: str | None, counterexample_summary: str | None) -> str:
    """Build a retry prompt with error feedback for the LLM."""
    parts = [original_prompt]
    parts.append(f"\n\n## RETRY (attempt {attempt}) — Previous Attempt Failed\n")

    if counterexample_summary:
        parts.append(f"**TLC counterexample:**\n```\n{counterexample_summary}\n```\n")

    if error_msg:
        parts.append(f"**Error:** {error_msg}\n")

    if tlc_output:
        error_start = tlc_output.find("Error:")
        if error_start >= 0:
            parts.append(f"**TLC output (error section):**\n```\n{tlc_output[error_start:error_start+1500]}\n```\n")
        elif "Unrecoverable" in tlc_output:
            recov_start = tlc_output.find("Unrecoverable")
            parts.append(f"**Compiler output:**\n```\n{tlc_output[recov_start:recov_start+1000]}\n```\n")

    parts.append(
        f"\nFix the specification to resolve this issue. Output the COMPLETE "
        f"corrected TLA+ module (not just the changed parts). "
        f"The MODULE name MUST be `{MODULE_NAME}`. "
        f"Remember: NO labels inside `with`, NO double assignment to same var in `with`, "
        f"NO Seq() in invariants (use bounded [1..N -> 1..M] instead)."
    )

    return "\n".join(parts)


async def call_llm(prompt: str) -> str:
    """Call Claude via the Agent SDK and collect the text response."""
    options = claude_agent_sdk.ClaudeAgentOptions(
        allowed_tools=[],
        system_prompt=(
            "You are a TLA+/PlusCal expert. Generate complete, syntactically correct "
            "PlusCal specifications embedded in TLA+ modules. Output ONLY the TLA+ module "
            "content — no markdown fencing, no explanation, no commentary. The output must "
            "be directly compilable by pcal.trans and verifiable by TLC."
        ),
        max_turns=1,
        model="claude-sonnet-4-20250514",
    )

    result_text = []
    async for message in claude_agent_sdk.query(prompt=prompt, options=options):
        if isinstance(message, claude_agent_sdk.AssistantMessage):
            for block in message.content:
                if isinstance(block, claude_agent_sdk.TextBlock):
                    result_text.append(block.text)
        elif isinstance(message, claude_agent_sdk.ResultMessage):
            if message.result:
                result_text.append(message.result)

    return "\n".join(result_text)


async def run_loop() -> None:
    """Execute the one-shot loop with real LLM calls and retry on failure."""
    banner("Phase 7 Self-Hosting: Subgraph Extraction Spec Generation")

    # Step 1: Load registry DAG
    step(1, 3, "Loading registry DAG...")
    extractor = SchemaExtractor(schema_dir=str(PROJECT_ROOT / "schema"))
    dag = extractor.extract()
    log(f"       DAG: {len(dag.nodes)} nodes, {len(dag.edges)} edges")

    # Step 2: Build initial prompt
    step(2, 3, f"Building prompt from registry context for {GWT_ID}...")
    loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
    initial_prompt = build_initial_prompt(loop)
    log(f"       Prompt: {len(initial_prompt)} chars")

    # Step 3: LLM generation + verification loop
    step(3, 3, f"Entering LLM loop (max {MAX_RETRIES} attempts)...")
    log("")

    current_prompt = initial_prompt
    last_response = ""
    status = None

    for attempt in range(1, MAX_RETRIES + 1):
        banner(f"Attempt {attempt}/{MAX_RETRIES}")

        # --- Call LLM ---
        log("  Calling Claude via Agent SDK...")
        llm_response = await call_llm(current_prompt)
        last_response = llm_response
        log(f"  Response: {len(llm_response)} chars")

        # Save response
        suffix = "" if attempt == 1 else f"_attempt{attempt}"
        response_file = PROJECT_ROOT / f"subgraph_llm_response{suffix}.txt"
        response_file.write_text(llm_response)
        log(f"  Saved to: {response_file.name}")

        # --- Process through pipeline ---
        log("")
        log("  Processing: extract PlusCal → compile → TLC verify...")

        # Fresh loop instance for each attempt
        loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
        loop.query(GWT_ID)

        status = loop.process_response(
            llm_response=llm_response,
            module_name=MODULE_NAME,
            cfg_text=SUBGRAPH_CFG,
        )

        # --- Report result ---
        log("")
        if status.tlc_result:
            if status.tlc_result.states_found > 0:
                log(f"  TLC explored: {status.tlc_result.states_found:,} states "
                    f"({status.tlc_result.states_distinct:,} distinct)")
            if status.tlc_result.success:
                log("  TLC result: ALL INVARIANTS HOLD")
            elif status.tlc_result.error_message:
                log(f"  TLC error: {status.tlc_result.error_message}")
        else:
            log("  TLC: did not run (compilation failed)")

        log(f"  Loop verdict: {status.result}")

        # --- Check outcome ---
        if status.result == LoopResult.PASS:
            banner("SUCCESS — Spec verified by TLC!")
            break

        # Failed — build retry prompt
        log("")
        log(f"  Sending error feedback to LLM for attempt {attempt + 1}...")

        error_msg = ""
        tlc_output = ""
        counterexample_summary = ""

        if status.tlc_result:
            error_msg = status.tlc_result.error_message or ""
            tlc_output = status.tlc_result.raw_output or ""
        if status.counterexample:
            counterexample_summary = status.counterexample.pluscal_summary
        if status.error:
            error_msg = status.error

        current_prompt = build_retry_prompt(
            initial_prompt, attempt + 1, error_msg, tlc_output, counterexample_summary,
        )

    else:
        banner(f"EXHAUSTED — Failed after {MAX_RETRIES} attempts")
        log("The LLM could not produce a spec that passes TLC verification.")
        log("Consider simplifying the requirements or adjusting CONSTANTS.")
        return

    # --- Bridge phase ---
    if status and status.result == LoopResult.PASS:
        banner("Running bridge on verified spec...")

        compiled_path = status.compiled_spec_path
        if compiled_path and compiled_path.exists():
            compiled_text = compiled_path.read_text()
            log(f"  Using compiled spec: {compiled_path}")
        else:
            compiled_text = last_response
            log("  WARNING: compiled spec not found, using raw LLM response")

        bridge_result = run_bridge(compiled_text)
        log(f"  Module:          {bridge_result.module_name}")
        log(f"  data_structures: {len(bridge_result.data_structures)}")
        log(f"  operations:      {len(bridge_result.operations)}")
        log(f"  verifiers:       {len(bridge_result.verifiers)}")
        log(f"  assertions:      {len(bridge_result.assertions)}")

        # Save bridge artifacts
        artifacts_dir = PROJECT_ROOT / "python" / "tests" / "generated"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        artifact_file = artifacts_dir / "subgraph_bridge_artifacts.json"
        artifact_file.write_text(json.dumps({
            "module_name": bridge_result.module_name,
            "data_structures": bridge_result.data_structures,
            "operations": bridge_result.operations,
            "verifiers": bridge_result.verifiers,
            "assertions": bridge_result.assertions,
        }, indent=2))
        log(f"  Artifacts saved: {artifact_file.name}")

        # Copy verified spec to instances directory
        instances_dir = PROJECT_ROOT / "templates" / "pluscal" / "instances"
        dest_tla = instances_dir / f"{MODULE_NAME}.tla"
        dest_cfg = instances_dir / f"{MODULE_NAME}.cfg"
        if compiled_path and compiled_path.exists():
            shutil.copy2(compiled_path, dest_tla)
            cfg_src = compiled_path.with_suffix(".cfg")
            if cfg_src.exists():
                shutil.copy2(cfg_src, dest_cfg)
            log(f"  Spec saved to: {dest_tla.relative_to(PROJECT_ROOT)}")

        # Generate tests mechanically from bridge artifacts
        banner("Generating tests from bridge artifacts...")
        test_path = generate_tests(bridge_result)
        log(f"  Generated: {test_path.name}")
        log(f"  Lines: {test_path.read_text().count(chr(10))}")

        # Run generated tests
        banner("Running generated tests...")
        result = subprocess.run(
            ["python3", "-m", "pytest", str(test_path), "-v", "--tb=short"],
            capture_output=True, text=True,
            cwd=str(PROJECT_ROOT / "python"),
        )
        log(result.stdout)
        if result.returncode != 0 and result.stderr:
            log(result.stderr)

        banner("Phase 7 pipeline complete!")
        if result.returncode == 0:
            log("  All generated tests PASS.")
        else:
            log("  Some tests failed — implement extract_subgraph() in dag.py.")


def generate_tests(bridge_result: "BridgeResult") -> Path:
    """Mechanically generate a pytest file from bridge verifiers and assertions.

    Maps each bridge verifier to a concrete test method that exercises the
    extract_subgraph() implementation against the invariant the TLA+ spec verified.
    """
    verifier_names = list(bridge_result.verifiers.keys())
    assertion_names = list(bridge_result.assertions.keys())

    inv_list = ", ".join(verifier_names)

    def _esc(s: str) -> str:
        return s.replace("\\", "/").replace("\n", " ").replace('"', "'")

    test_methods = []
    for vname, verifier in bridge_result.verifiers.items():
        conds = verifier.get("conditions", [])
        applies_to = verifier.get("applies_to", [])
        cond_str = " AND ".join(conds) if conds else "TRUE"

        test_methods.append(
            f'    def test_{vname.lower()}(self):\n'
            f'        """Verifier {vname}: {_esc(verifier.get("message", "")[:80])}"""\n'
            f'        # Bridge condition: {_esc(cond_str[:120])}\n'
            f'        # Applies to: {", ".join(applies_to)}\n'
            f'        self._check_invariant("{vname}")\n'
        )

    test_content = f'''\
"""Generated test suite from {MODULE_NAME}.tla via Bridge (Phase 7).

Mechanically generated from bridge artifacts by run_subgraph_loop.py.
Verifiers: {inv_list}
"""

import pytest
from registry.dag import RegistryDag, NodeNotFoundError
from registry.types import Node, Edge, EdgeType, SubgraphResult


class TestSubgraphExtractionInvariants:
    """Tests mechanically derived from {MODULE_NAME}.tla bridge verifiers."""

    def _make_chain_dag(self):
        """a -> b -> c -> d (linear chain, all resources)."""
        dag = RegistryDag()
        for nid in ("a", "b", "c", "d"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "c", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("c", "d", EdgeType.DEPENDS_ON))
        return dag

    def _make_diamond_dag(self):
        """Diamond: a -> b, a -> c, b -> d, c -> d."""
        dag = RegistryDag()
        for nid in ("a", "b", "c", "d"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("a", "c", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "d", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("c", "d", EdgeType.DEPENDS_ON))
        return dag

    def _make_isolated_dag(self):
        """Three disconnected nodes: x, y, z."""
        dag = RegistryDag()
        for nid in ("x", "y", "z"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        return dag

    def _check_invariant(self, name):
        method = getattr(self, f"_verify_{{name}}", None)
        if method:
            method()

    # -- Invariant verification methods --

    def _verify_SubgraphCompleteness(self):
        """Subgraph contains all ancestors and descendants."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("b")
        assert "a" in result.nodes, "SubgraphCompleteness: ancestor 'a' missing"
        assert "b" in result.nodes, "SubgraphCompleteness: target 'b' missing"
        assert "c" in result.nodes, "SubgraphCompleteness: descendant 'c' missing"
        assert "d" in result.nodes, "SubgraphCompleteness: descendant 'd' missing"

    def _verify_NoHoles(self):
        """No holes in the subgraph — all reachable nodes included."""
        dag = self._make_diamond_dag()
        result = dag.extract_subgraph("b")
        # b's ancestors: a; b's descendants: d
        # c is NOT in b's subgraph (c is a sibling, not ancestor/descendant of b)
        # But wait: a->c exists and a is in subgraph. c->d exists and d is in subgraph.
        # c is reachable from a (ancestor of b), so... no. The spec says forward+reverse
        # closure of THE TARGET, not of every node in the subgraph.
        # Forward of b: d. Reverse of b: a. Subgraph = {{a, b, d}}.
        # Edge a->c: c is NOT reachable from b and b is NOT reachable from c.
        # So c should NOT be in subgraph. NoHoles means no holes in closure paths.
        assert "a" in result.nodes
        assert "b" in result.nodes
        assert "d" in result.nodes

    def _verify_NoDanglingEdges(self):
        """Every edge in the result has both endpoints in the node set."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("b")
        for edge in result.edges:
            assert edge.from_id in result.nodes, f"NoDanglingEdges: {{edge.from_id}} not in nodes"
            assert edge.to_id in result.nodes, f"NoDanglingEdges: {{edge.to_id}} not in nodes"

    def _verify_IsolatedNodeCorrect(self):
        """Isolated node returns only itself and no edges."""
        dag = self._make_isolated_dag()
        result = dag.extract_subgraph("x")
        assert result.nodes == {{"x"}}, f"IsolatedNodeCorrect: expected {{{'x'}}}, got {{result.nodes}}"
        assert result.edges == [], f"IsolatedNodeCorrect: expected no edges, got {{len(result.edges)}}"

    def _verify_ValidState(self):
        """extract_subgraph returns a valid SubgraphResult."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("b")
        assert isinstance(result, SubgraphResult)
        assert result.root == "b"

    def _verify_BoundedExecution(self):
        """Result is deterministic and finite."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("a")
        assert isinstance(result, SubgraphResult)

{chr(10).join(test_methods)}
    # -- Additional invariant-derived tests --

    def test_chain_middle_node(self):
        """SubgraphCompleteness: middle node gets full chain."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("b")
        assert result.nodes == {{"a", "b", "c", "d"}}

    def test_chain_root_node(self):
        """SubgraphCompleteness: root node gets itself + all descendants."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("a")
        assert result.nodes == {{"a", "b", "c", "d"}}

    def test_chain_leaf_node(self):
        """SubgraphCompleteness: leaf node gets itself + all ancestors."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("d")
        assert result.nodes == {{"a", "b", "c", "d"}}

    def test_diamond_center(self):
        """SubgraphCompleteness: diamond center includes all paths."""
        dag = self._make_diamond_dag()
        result = dag.extract_subgraph("b")
        assert "a" in result.nodes, "ancestor a missing"
        assert "b" in result.nodes, "target b missing"
        assert "d" in result.nodes, "descendant d missing"

    def test_diamond_root(self):
        """SubgraphCompleteness: diamond root includes all descendants."""
        dag = self._make_diamond_dag()
        result = dag.extract_subgraph("a")
        assert result.nodes == {{"a", "b", "c", "d"}}

    def test_isolated_node(self):
        """IsolatedNodeCorrect: isolated node → singleton, no edges."""
        dag = self._make_isolated_dag()
        result = dag.extract_subgraph("y")
        assert result.nodes == {{"y"}}
        assert result.edges == []

    def test_no_dangling_edges_chain(self):
        """NoDanglingEdges: chain subgraph has no dangling edges."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("c")
        for edge in result.edges:
            assert edge.from_id in result.nodes
            assert edge.to_id in result.nodes

    def test_no_dangling_edges_diamond(self):
        """NoDanglingEdges: diamond subgraph has no dangling edges."""
        dag = self._make_diamond_dag()
        result = dag.extract_subgraph("d")
        for edge in result.edges:
            assert edge.from_id in result.nodes
            assert edge.to_id in result.nodes

    def test_edge_count_chain_full(self):
        """All 3 edges present when full chain is in subgraph."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("b")
        assert len(result.edges) == 3

    def test_edge_count_isolated(self):
        """No edges for isolated node."""
        dag = self._make_isolated_dag()
        result = dag.extract_subgraph("z")
        assert len(result.edges) == 0

    def test_root_is_set(self):
        """Root field matches the queried node."""
        dag = self._make_chain_dag()
        result = dag.extract_subgraph("c")
        assert result.root == "c"

    def test_missing_node_raises(self):
        """NodeNotFoundError for missing node."""
        dag = self._make_chain_dag()
        with pytest.raises(NodeNotFoundError):
            dag.extract_subgraph("nonexistent")

    def test_does_not_mutate_dag(self):
        """extract_subgraph must not modify the DAG."""
        dag = self._make_chain_dag()
        edges_before = len(dag.edges)
        nodes_before = len(dag.nodes)
        dag.extract_subgraph("b")
        assert len(dag.edges) == edges_before
        assert len(dag.nodes) == nodes_before

    def test_two_components(self):
        """Subgraph only includes the target's component."""
        dag = RegistryDag()
        for nid in ("a", "b", "c", "x", "y"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "c", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("x", "y", EdgeType.DEPENDS_ON))
        result = dag.extract_subgraph("b")
        assert result.nodes == {{"a", "b", "c"}}
        assert "x" not in result.nodes
        assert "y" not in result.nodes
'''

    output_dir = PROJECT_ROOT / "python" / "tests" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    test_path = output_dir / f"test_{MODULE_NAME}.py"
    test_path.write_text(test_content)
    return test_path


if __name__ == "__main__":
    asyncio.run(run_loop())
