#!/usr/bin/env python3
"""Run the one-shot loop to generate an impact analysis spec (Phase 5 self-hosting).

This is the first feature built ENTIRELY through the pipeline:
  1. Plain language requirement → GWT behaviors (already registered in DAG)
  2. Registry context → LLM prompt → PlusCal spec → TLC verification
  3. Bridge → test generation
  4. Implementation to pass the tests

Retry strategy: on any failure (compilation or TLC), sends the error back to
the LLM for correction, up to MAX_RETRIES attempts.
"""

import asyncio
import json
import os
import sys
from pathlib import Path

# Must unset CLAUDECODE to allow launching a sub-session from within Claude Code
os.environ.pop("CLAUDECODE", None)

import claude_agent_sdk

# Add python/ to path so registry imports work
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "python"))

LOG_FILE = PROJECT_ROOT / "impact_loop_output.log"
_log_fh = open(LOG_FILE, "w")

MAX_RETRIES = 5


def log(msg: str) -> None:
    """Print to both log file and stdout."""
    print(msg, flush=True)
    _log_fh.write(msg + "\n")
    _log_fh.flush()


def banner(msg: str) -> None:
    """Print a prominent banner."""
    log("")
    log("=" * 70)
    log(f"  {msg}")
    log("=" * 70)
    log("")


def step(num: int, total: int, msg: str) -> None:
    """Print a step marker."""
    log(f"  [{num}/{total}] {msg}")


from registry.extractor import SchemaExtractor
from registry.one_shot_loop import OneShotLoop, LoopResult
from registry.bridge import run_bridge


# TLC config for the impact analysis spec
IMPACT_CFG = """\
\\* Impact analysis TLC config (generated by run_impact_loop.py)
SPECIFICATION Spec

CONSTANTS
    MaxSteps = 15
    NumNodes = 4
    MaxEdges = 6

INVARIANTS
    ValidState
    BoundedExecution
    ReverseClosureComplete
    LeafHasNoImpact
    DirectDependentsIncluded
    MonotonicGrowth
"""


def build_initial_prompt(loop: OneShotLoop) -> str:
    """Build the initial LLM prompt from registry context + instructions."""
    loop.query("gwt-0012")
    context = loop.format_prompt()

    template_path = PROJECT_ROOT / "templates" / "pluscal" / "state_machine.tla"
    template_text = template_path.read_text()

    return f"""You are generating a PlusCal specification for an impact analysis query —
a reverse dependency traversal that finds all nodes transitively depending on a target node.

## Registry Context (from the DAG)

{context}

## State Machine Template (use this pattern)

```tla
{template_text}
```

## Requirements

Generate a COMPLETE PlusCal specification (inside a TLA+ module) for an impact
analysis state machine with these characteristics:

**Module name:** impact_analysis (the MODULE name MUST be impact_analysis)

**The problem:** Given a directed graph (DAG), and a target node, compute the
"reverse closure" — all nodes that can reach the target through directed edges.
If A→B→C, then impact(C) = {{A, B}} because both A and B transitively depend on C.

**CONSTANTS:** MaxSteps, NumNodes, MaxEdges

**States:** idle, building_graph, selecting_target, computing_reverse,
collecting_results, done, failed

**State variables (beyond current_state):**
- adjacency: a function from node IDs (1..NumNodes) to sets of node IDs (their successors)
- edge_count: number of edges added so far
- target: the node being queried (0 means not selected yet)
- reverse_set: the set of nodes whose closure contains target (the result)
- visited: set of nodes already checked during BFS
- worklist: set of nodes still to process in reverse BFS
- direct_dependents: set of nodes with a direct edge TO target
- step_count, op, result, dirty (control variables)

**Transitions:**
- idle → building_graph: start building
- building_graph → building_graph: nondeterministically add edges (up to MaxEdges).
  Use one either/or branch per possible edge (1→2, 1→3, 1→4, 2→3, 2→4, 3→4).
- building_graph → selecting_target: done adding edges
- selecting_target → computing_reverse: pick a target node (1..NumNodes).
  Use one either/or branch per possible target.
- computing_reverse → computing_reverse: process one node from worklist (BFS step)
- computing_reverse → collecting_results: worklist is empty
- collecting_results → done: finalize results
- any state → failed: step_count >= MaxSteps

**Reverse BFS algorithm in computing_reverse:**
1. Initialize (during target selection): worklist = {{target}}, visited = {{}}, reverse_set = {{}}
2. Pick any node n from worklist (use `with n \\in worklist do`), remove it, add to visited
3. Find predecessors: {{p \\in 1..NumNodes : n \\in adjacency[p] /\\ p \\notin visited /\\ p # n}}
4. Add predecessors to BOTH worklist AND reverse_set
5. Repeat until worklist = {{}}
6. Note: target itself is NOT in reverse_set (we only want dependents)

**Computing direct_dependents:** In each SelectTarget branch, FIRST set target
to the chosen value and dirty=TRUE. Then in the SECOND PHASE (after the label),
compute direct_dependents := {{p \\in 1..NumNodes : target \\in adjacency[p]}}.
This ensures `target` has its new value when computing dependents (PlusCal
assignments within a label are sequential — later assignments see earlier values).

**Invariants (in define block):**
- ValidState: current_state \\in StateSet
- BoundedExecution: step_count <= MaxSteps
- ReverseClosureComplete: when done AND target # 0, for every node n in reverse_set,
  there exists a bounded path (length 1..NumNodes) from n to target through adjacency.
  Use: \\E path_len \\in 1..NumNodes : \\E path \\in [1..path_len -> 1..NumNodes] : ...
  (DO NOT use Seq() — it's infinite and TLC cannot evaluate it)
- LeafHasNoImpact: when done, if no node has target in its adjacency set, reverse_set = {{}}
- DirectDependentsIncluded: when done, direct_dependents \\subseteq reverse_set
- MonotonicGrowth: dirty = TRUE \\/ TRUE (simplified)

**Two-phase action model:** Use a `dirty` flag. Set dirty=TRUE when mutating
primary state, then set dirty=FALSE when derived state is consistent. Gate
invariants on dirty with `dirty = TRUE \\/` prefix.

**Process:** Single fair process "main" with a while loop that terminates
when current_state is in done/failed or step_count >= MaxSteps. Use
`either/or` for nondeterministic choice between transitions.

**PlusCal LABEL RULES (CRITICAL — pcal.trans will reject without these):**

In PlusCal, when you have an `if` statement inside an `either` branch, and the
if body contains multiple assignments OR the else branch exists, you MUST add
a label AFTER the first group of assignments in the if branch. PlusCal requires
labels at "control flow join points."

CORRECT pattern (two-phase with labels):
```
either
    ActionLabel:
        if guard then
            \\* first assignments (Phase 1: mutate data)
            var1 := val1;
            dirty := TRUE;
            step_count := step_count + 1;
        ActionDecide:
            \\* second phase (Phase 2: transition state)
            current_state := "next_state";
            dirty := FALSE;
        else
            op := "skip";
        end if;
or
    ...
end either;
```

**PlusCal `with` RULES (CRITICAL — pcal.trans will reject violations):**

1. You CANNOT put a label inside a `with` statement.
2. You CANNOT assign to the same variable twice inside a single `with` block.
3. Keep `with` blocks simple: use only for nondeterministic choice (like
   picking from worklist), with assignments to DIFFERENT variables.
4. After the `with`/`end with`, you can have more assignments and labels.

Example of correct `with` usage for BFS:
```
BFSStep:
    if current_state = "computing_reverse" /\\ worklist # {{}} then
        with n \\in worklist do
            visited := visited \\union {{n}};
            worklist := (worklist \\ {{n}}) \\union
                {{p \\in 1..NumNodes : n \\in adjacency[p] /\\ p \\notin visited /\\ p # n}};
            reverse_set := reverse_set \\union
                {{p \\in 1..NumNodes : n \\in adjacency[p] /\\ p \\notin visited /\\ p # n}};
        end with;
        step_count := step_count + 1;
        dirty := TRUE;
    BFSStepDone:
        op := "bfs_step";
        dirty := FALSE;
    else
        op := "skip_bfs";
    end if;
```

**IMPORTANT adjacency representation:**
Initialize: adjacency = [n \\in 1..NumNodes |-> {{}}]
To add edge i→j: adjacency := [adjacency EXCEPT ![i] = adjacency[i] \\union {{j}}]
Only allow i < j (DAG constraint). No self-loops.

**OUTPUT FORMAT:** Output ONLY the TLA+ module — no markdown fencing, no
explanation, no commentary. The module should contain:
1. MODULE line (MUST be `impact_analysis`)
2. EXTENDS Integers, FiniteSets, Sequences, TLC
3. CONSTANTS
4. (* --algorithm ... end algorithm; *)
5. The closing ===... line
"""


def build_retry_prompt(original_prompt: str, attempt: int, error_msg: str,
                       tlc_output: str | None, counterexample_summary: str | None) -> str:
    """Build a retry prompt with error feedback for the LLM."""
    parts = [original_prompt]
    parts.append(f"\n\n## RETRY (attempt {attempt}) — Previous Attempt Failed\n")

    if counterexample_summary:
        parts.append(f"**TLC counterexample:**\n```\n{counterexample_summary}\n```\n")

    if error_msg:
        parts.append(f"**Error:** {error_msg}\n")

    if tlc_output:
        # Include relevant portion
        error_start = tlc_output.find("Error:")
        if error_start >= 0:
            parts.append(f"**TLC output (error section):**\n```\n{tlc_output[error_start:error_start+1500]}\n```\n")
        elif "Unrecoverable" in tlc_output:
            recov_start = tlc_output.find("Unrecoverable")
            parts.append(f"**Compiler output:**\n```\n{tlc_output[recov_start:recov_start+1000]}\n```\n")

    parts.append(
        "\nFix the specification to resolve this issue. Output the COMPLETE "
        "corrected TLA+ module (not just the changed parts). "
        "The MODULE name MUST be `impact_analysis`. "
        "Remember: NO labels inside `with`, NO double assignment to same var in `with`, "
        "NO Seq() in invariants (use bounded [1..N -> 1..M] instead)."
    )

    return "\n".join(parts)


async def call_llm(prompt: str) -> str:
    """Call Claude via the Agent SDK and collect the text response."""
    options = claude_agent_sdk.ClaudeAgentOptions(
        allowed_tools=[],
        system_prompt=(
            "You are a TLA+/PlusCal expert. Generate complete, syntactically correct "
            "PlusCal specifications embedded in TLA+ modules. Output ONLY the TLA+ module "
            "content — no markdown fencing, no explanation, no commentary. The output must "
            "be directly compilable by pcal.trans and verifiable by TLC."
        ),
        max_turns=1,
        model="claude-sonnet-4-20250514",
    )

    result_text = []
    async for message in claude_agent_sdk.query(prompt=prompt, options=options):
        if isinstance(message, claude_agent_sdk.AssistantMessage):
            for block in message.content:
                if isinstance(block, claude_agent_sdk.TextBlock):
                    result_text.append(block.text)
        elif isinstance(message, claude_agent_sdk.ResultMessage):
            if message.result:
                result_text.append(message.result)

    return "\n".join(result_text)


async def run_loop() -> None:
    """Execute the one-shot loop with real LLM calls and retry on failure."""
    banner("Phase 5 Self-Hosting: Impact Analysis Spec Generation")

    # Step 1: Load registry DAG
    step(1, 3, "Loading registry DAG...")
    extractor = SchemaExtractor(schema_dir=str(PROJECT_ROOT / "schema"))
    dag = extractor.extract()
    log(f"       DAG: {len(dag.nodes)} nodes, {len(dag.edges)} edges")

    # Step 2: Build initial prompt
    step(2, 3, "Building prompt from registry context for gwt-0012...")
    loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
    initial_prompt = build_initial_prompt(loop)
    log(f"       Prompt: {len(initial_prompt)} chars")

    # Step 3: LLM generation + verification loop
    step(3, 3, f"Entering LLM loop (max {MAX_RETRIES} attempts)...")
    log("")

    current_prompt = initial_prompt
    last_response = ""

    for attempt in range(1, MAX_RETRIES + 1):
        banner(f"Attempt {attempt}/{MAX_RETRIES}")

        # --- Call LLM ---
        log("  Calling Claude via Agent SDK...")
        llm_response = await call_llm(current_prompt)
        last_response = llm_response
        log(f"  Response: {len(llm_response)} chars")

        # Save response
        suffix = "" if attempt == 1 else f"_attempt{attempt}"
        response_file = PROJECT_ROOT / f"impact_llm_response{suffix}.txt"
        response_file.write_text(llm_response)
        log(f"  Saved to: {response_file.name}")

        # --- Process through pipeline ---
        log("")
        log("  Processing: extract PlusCal → compile → TLC verify...")

        # Fresh loop instance for each attempt (resets failure counter)
        loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
        loop.query("gwt-0012")

        status = loop.process_response(
            llm_response=llm_response,
            module_name="impact_analysis",
            cfg_text=IMPACT_CFG,
        )

        # --- Report result ---
        log("")
        if status.tlc_result:
            if status.tlc_result.states_found > 0:
                log(f"  TLC explored: {status.tlc_result.states_found:,} states "
                    f"({status.tlc_result.states_distinct:,} distinct)")
            if status.tlc_result.success:
                log("  TLC result: ALL INVARIANTS HOLD")
            elif status.tlc_result.error_message:
                log(f"  TLC error: {status.tlc_result.error_message}")
        else:
            log("  TLC: did not run (compilation failed)")

        log(f"  Loop verdict: {status.result}")

        # --- Check outcome ---
        if status.result == LoopResult.PASS:
            banner("SUCCESS — Spec verified by TLC!")
            break

        # Failed — build retry prompt with error feedback
        log("")
        log(f"  Sending error feedback to LLM for attempt {attempt + 1}...")

        error_msg = ""
        tlc_output = ""
        counterexample_summary = ""

        if status.tlc_result:
            error_msg = status.tlc_result.error_message or ""
            tlc_output = status.tlc_result.raw_output or ""
        if status.counterexample:
            counterexample_summary = status.counterexample.pluscal_summary
        if status.error:
            error_msg = status.error

        current_prompt = build_retry_prompt(
            initial_prompt, attempt + 1, error_msg, tlc_output, counterexample_summary,
        )

    else:
        banner(f"EXHAUSTED — Failed after {MAX_RETRIES} attempts")
        log("The LLM could not produce a spec that passes TLC verification.")
        log("Consider simplifying the requirements or adjusting CONSTANTS.")
        return

    # --- Bridge phase ---
    if status.result == LoopResult.PASS:
        banner("Running bridge on verified spec...")

        # Use the compiled TLA+ (after pcal.trans), not the raw LLM response
        compiled_path = status.compiled_spec_path
        if compiled_path and compiled_path.exists():
            compiled_text = compiled_path.read_text()
            log(f"  Using compiled spec: {compiled_path}")
        else:
            compiled_text = last_response
            log("  WARNING: compiled spec not found, using raw LLM response")

        bridge_result = run_bridge(compiled_text)
        log(f"  Module:          {bridge_result.module_name}")
        log(f"  data_structures: {len(bridge_result.data_structures)}")
        log(f"  operations:      {len(bridge_result.operations)}")
        log(f"  verifiers:       {len(bridge_result.verifiers)}")
        log(f"  assertions:      {len(bridge_result.assertions)}")

        # Save bridge artifacts
        artifacts_dir = PROJECT_ROOT / "python" / "tests" / "generated"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        artifact_file = artifacts_dir / "impact_analysis_bridge_artifacts.json"
        artifact_file.write_text(json.dumps({
            "module_name": bridge_result.module_name,
            "data_structures": bridge_result.data_structures,
            "operations": bridge_result.operations,
            "verifiers": bridge_result.verifiers,
            "assertions": bridge_result.assertions,
        }, indent=2))
        log(f"  Artifacts saved: {artifact_file.name}")

        # Copy verified spec to instances directory
        instances_dir = PROJECT_ROOT / "templates" / "pluscal" / "instances"
        dest_tla = instances_dir / "impact_analysis.tla"
        dest_cfg = instances_dir / "impact_analysis.cfg"
        if compiled_path and compiled_path.exists():
            import shutil
            shutil.copy2(compiled_path, dest_tla)
            cfg_src = compiled_path.with_suffix(".cfg")
            if cfg_src.exists():
                shutil.copy2(cfg_src, dest_cfg)
            log(f"  Spec saved to: {dest_tla.relative_to(PROJECT_ROOT)}")

        banner("Phase 5 pipeline complete!")
        log("  Next: implement query_impact() in dag.py to pass generated tests.")


if __name__ == "__main__":
    asyncio.run(run_loop())
