#!/usr/bin/env python3
"""Run the one-shot loop to generate a dependency validation spec (Phase 6 self-hosting).

Second feature built through the pipeline:
  1. Plain language requirement → GWT behaviors (registered in DAG)
  2. Registry context → LLM prompt → PlusCal spec → TLC verification
  3. Bridge → test generation
  4. Implementation to pass the tests

Retry strategy: on any failure (compilation or TLC), sends the error back to
the LLM for correction, up to MAX_RETRIES attempts.
"""

import asyncio
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Must unset CLAUDECODE to allow launching a sub-session from within Claude Code
os.environ.pop("CLAUDECODE", None)

import claude_agent_sdk

# Add python/ to path so registry imports work
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "python"))

from registry.context import ProjectContext
ctx = ProjectContext.self_hosting(PROJECT_ROOT)
ctx.session_dir.mkdir(parents=True, exist_ok=True)

LOG_FILE = ctx.session_dir / "dep_validation_loop_output.log"
_log_fh = open(LOG_FILE, "w")

MAX_RETRIES = 5
MODULE_NAME = "dep_validation"
GWT_ID = "gwt-0015"


def log(msg: str) -> None:
    print(msg, flush=True)
    _log_fh.write(msg + "\n")
    _log_fh.flush()


def banner(msg: str) -> None:
    log("")
    log("=" * 70)
    log(f"  {msg}")
    log("=" * 70)
    log("")


def step(num: int, total: int, msg: str) -> None:
    log(f"  [{num}/{total}] {msg}")


from registry.extractor import SchemaExtractor
from registry.one_shot_loop import OneShotLoop, LoopResult
from registry.bridge import run_bridge


# TLC config for the dependency validation spec
DEP_VALIDATION_CFG = """\
\\* Dependency validation TLC config (generated by run_dep_validation_loop.py)
SPECIFICATION Spec

CONSTANTS
    MaxSteps = 12
    NumNodes = 4
    MaxEdges = 6
    NumKinds = 3

INVARIANTS
    ValidState
    BoundedExecution
    AcyclicityPreserved
    DuplicateRejected
    KindCompatibilityEnforced
    ValidEdgeAccepted
"""


def build_initial_prompt(loop: OneShotLoop) -> str:
    """Build the initial LLM prompt from registry context + instructions."""
    loop.query(GWT_ID)
    context = loop.format_prompt()

    template_path = ctx.template_dir / "state_machine.tla"
    template_text = template_path.read_text()

    return f"""You are generating a PlusCal specification for a dependency validation pre-check —
a function that determines whether a proposed edge can be safely added to a DAG without
violating acyclicity, duplication, or node-kind compatibility constraints.

## Registry Context (from the DAG)

{context}

## State Machine Template (use this pattern)

```tla
{template_text}
```

## Requirements

Generate a COMPLETE PlusCal specification (inside a TLA+ module) for a dependency
validation state machine with these characteristics:

**Module name:** {MODULE_NAME} (the MODULE name MUST be {MODULE_NAME})

**The problem:** Given a directed graph (DAG) with typed nodes (each node has a "kind"),
and a proposed edge (from_node, to_node, edge_type), determine whether adding that edge
would maintain all DAG invariants:
1. **Acyclicity:** adding from→to must not create a cycle (no path from to→from after addition)
2. **No duplicates:** if from→to already exists with the same edge type, reject it
3. **Kind compatibility:** certain node-kind pairings are forbidden. Specifically:
   - A behavior node (kind=2) CANNOT have a depends_on edge TO a test node (kind=3)
   - A requirement node (kind=1) CANNOT have a depends_on edge TO a test node (kind=3)
   (Kind 1=requirement, 2=behavior, 3=test; kind 0=resource is unconstrained)

**CONSTANTS:** MaxSteps, NumNodes, MaxEdges, NumKinds

**States:** idle, building_graph, proposing_edge, checking_acyclicity,
checking_duplicate, checking_kind, computing_result, done, failed

**State variables (beyond current_state):**
- adjacency: a function from node IDs (1..NumNodes) to sets of node IDs (their successors)
- node_kind: a function from node IDs (1..NumNodes) to kind values (0..NumKinds-1)
- edge_count: number of edges added so far
- proposed_from: the source of the proposed edge (0 means not selected)
- proposed_to: the target of the proposed edge (0 means not selected)
- proposed_edge_type: type of the proposed edge (0=other, 1=depends_on)
- is_valid: boolean result of validation (TRUE = edge can be added)
- rejection_reason: string ("" = none, "cycle" = would create cycle, "duplicate" = already exists, "kind" = incompatible kinds)
- reachable: set of nodes reachable from proposed_to (for cycle check)
- visited: set of nodes already checked during BFS
- worklist: set of nodes still to process in BFS
- step_count, op, result, dirty (control variables)

**Transitions:**
- idle → building_graph: start building. Assign each node a random kind:
  node_kind := [n \\in 1..NumNodes |-> 0] then nondeterministically set kinds.
  Use `with k1 \\in 0..NumKinds-1, k2 \\in 0..NumKinds-1 do` etc.
  Actually, simpler: use a single `with` to assign all kinds at once:
  `with kf \\in [1..NumNodes -> 0..NumKinds-1] do node_kind := kf; end with;`

- building_graph → building_graph: nondeterministically add edges (up to MaxEdges).
  Only add forward edges (i < j) to maintain acyclicity during construction.
  Use one either/or branch per possible edge pair.

- building_graph → proposing_edge: done adding edges, propose an edge to validate.

- proposing_edge → checking_acyclicity: pick from_node and to_node (any pair, including
  backwards edges that might create cycles). Pick an edge_type (0 or 1).
  Initialize: is_valid := TRUE, rejection_reason := "".

- checking_acyclicity → checking_acyclicity: BFS from proposed_to to see if proposed_from
  is reachable. Initialize worklist := {{proposed_to}}, visited := {{}}, reachable := {{}}.
  Process one node from worklist per step.

- checking_acyclicity → checking_duplicate: worklist empty.
  If proposed_from \\in reachable OR proposed_from = proposed_to:
    is_valid := FALSE, rejection_reason := "cycle"

- checking_duplicate → checking_kind: Check if proposed edge already exists.
  If proposed_to \\in adjacency[proposed_from]:
    is_valid := FALSE, rejection_reason := "duplicate"
  (Only reject if still is_valid = TRUE — don't overwrite a cycle rejection)

- checking_kind → computing_result: Check kind compatibility.
  If is_valid = TRUE AND proposed_edge_type = 1 (depends_on):
    If (node_kind[proposed_from] = 2 AND node_kind[proposed_to] = 3)  \\* behavior→test
       OR (node_kind[proposed_from] = 1 AND node_kind[proposed_to] = 3):  \\* requirement→test
      is_valid := FALSE, rejection_reason := "kind"

- computing_result → done: finalize

- any state → failed: step_count >= MaxSteps

**Invariants (in define block):**
- ValidState: current_state \\in StateSet
- BoundedExecution: step_count <= MaxSteps
- AcyclicityPreserved: when done AND is_valid = TRUE, there is no path from proposed_to
  to proposed_from in the graph extended with proposed_from→proposed_to.
  Check: proposed_from \\notin reachable (already computed by BFS).
  Guard with dirty: dirty = TRUE \\/ (current_state = "done" => ...)
- DuplicateRejected: when done AND rejection_reason = "", proposed_to should NOT already
  be in adjacency[proposed_from]. Guard with dirty.
- KindCompatibilityEnforced: when done AND is_valid = TRUE AND proposed_edge_type = 1,
  it's NOT the case that (node_kind[proposed_from] \\in {{1,2}} AND node_kind[proposed_to] = 3).
  Guard with dirty.
- ValidEdgeAccepted: when done AND there is no cycle AND no duplicate AND kinds are compatible,
  then is_valid = TRUE. This is the "happy path" invariant.
  Guard with dirty.

**Two-phase action model:** Use a `dirty` flag. Set dirty=TRUE when mutating
primary state, then set dirty=FALSE when derived state is consistent. Gate
invariants on dirty with `dirty = TRUE \\/` prefix.

**Process:** Single fair process "main" with a while loop that terminates
when current_state is in done/failed or step_count >= MaxSteps. Use
`either/or` for nondeterministic choice between transitions.

**PlusCal LABEL RULES (CRITICAL — pcal.trans will reject without these):**

In PlusCal, when you have an `if` statement inside an `either` branch, and the
if body contains multiple assignments OR the else branch exists, you MUST add
a label AFTER the first group of assignments in the if branch. PlusCal requires
labels at "control flow join points."

CORRECT pattern (two-phase with labels):
```
either
    ActionLabel:
        if guard then
            \\* first assignments (Phase 1: mutate data)
            var1 := val1;
            dirty := TRUE;
            step_count := step_count + 1;
        ActionDecide:
            \\* second phase (Phase 2: transition state)
            current_state := "next_state";
            dirty := FALSE;
        else
            op := "skip";
        end if;
or
    ...
end either;
```

**PlusCal `with` RULES (CRITICAL — pcal.trans will reject violations):**

1. You CANNOT put a label inside a `with` statement.
2. You CANNOT assign to the same variable twice inside a single `with` block.
3. Keep `with` blocks simple: use only for nondeterministic choice (like
   picking from worklist), with assignments to DIFFERENT variables.
4. After the `with`/`end with`, you can have more assignments and labels.

Example of correct `with` usage for BFS:
```
BFSStep:
    if current_state = "checking_acyclicity" /\\ worklist # {{}} then
        with n \\in worklist do
            visited := visited \\union {{n}};
            worklist := (worklist \\ {{n}}) \\union
                {{s \\in adjacency[n] : s \\notin visited}};
            reachable := reachable \\union {{s \\in adjacency[n] : s \\notin visited}};
        end with;
        step_count := step_count + 1;
        dirty := TRUE;
    BFSStepDone:
        op := "bfs_step";
        dirty := FALSE;
    else
        op := "skip_bfs";
    end if;
```

**IMPORTANT adjacency representation:**
Initialize: adjacency = [n \\in 1..NumNodes |-> {{}}]
To add edge i→j: adjacency := [adjacency EXCEPT ![i] = adjacency[i] \\union {{j}}]
Only allow i < j during graph building (DAG constraint). No self-loops.
The proposed edge may be any pair (including i > j) to test cycle detection.

**OUTPUT FORMAT:** Output ONLY the TLA+ module — no markdown fencing, no
explanation, no commentary. The module should contain:
1. MODULE line (MUST be `{MODULE_NAME}`)
2. EXTENDS Integers, FiniteSets, Sequences, TLC
3. CONSTANTS
4. (* --algorithm ... end algorithm; *)
5. The closing ===... line
"""


def build_retry_prompt(original_prompt: str, attempt: int, error_msg: str,
                       tlc_output: str | None, counterexample_summary: str | None) -> str:
    """Build a retry prompt with error feedback for the LLM."""
    parts = [original_prompt]
    parts.append(f"\n\n## RETRY (attempt {attempt}) — Previous Attempt Failed\n")

    if counterexample_summary:
        parts.append(f"**TLC counterexample:**\n```\n{counterexample_summary}\n```\n")

    if error_msg:
        parts.append(f"**Error:** {error_msg}\n")

    if tlc_output:
        error_start = tlc_output.find("Error:")
        if error_start >= 0:
            parts.append(f"**TLC output (error section):**\n```\n{tlc_output[error_start:error_start+1500]}\n```\n")
        elif "Unrecoverable" in tlc_output:
            recov_start = tlc_output.find("Unrecoverable")
            parts.append(f"**Compiler output:**\n```\n{tlc_output[recov_start:recov_start+1000]}\n```\n")

    parts.append(
        f"\nFix the specification to resolve this issue. Output the COMPLETE "
        f"corrected TLA+ module (not just the changed parts). "
        f"The MODULE name MUST be `{MODULE_NAME}`. "
        f"Remember: NO labels inside `with`, NO double assignment to same var in `with`, "
        f"NO Seq() in invariants (use bounded [1..N -> 1..M] instead)."
    )

    return "\n".join(parts)


async def call_llm(prompt: str) -> str:
    """Call Claude via the Agent SDK and collect the text response."""
    options = claude_agent_sdk.ClaudeAgentOptions(
        allowed_tools=[],
        system_prompt=(
            "You are a TLA+/PlusCal expert. Generate complete, syntactically correct "
            "PlusCal specifications embedded in TLA+ modules. Output ONLY the TLA+ module "
            "content — no markdown fencing, no explanation, no commentary. The output must "
            "be directly compilable by pcal.trans and verifiable by TLC."
        ),
        max_turns=1,
        model="claude-sonnet-4-20250514",
    )

    result_text = []
    async for message in claude_agent_sdk.query(prompt=prompt, options=options):
        if isinstance(message, claude_agent_sdk.AssistantMessage):
            for block in message.content:
                if isinstance(block, claude_agent_sdk.TextBlock):
                    result_text.append(block.text)
        elif isinstance(message, claude_agent_sdk.ResultMessage):
            if message.result:
                result_text.append(message.result)

    return "\n".join(result_text)


async def run_loop() -> None:
    """Execute the one-shot loop with real LLM calls and retry on failure."""
    banner("Phase 6 Self-Hosting: Dependency Validation Spec Generation")

    # Step 1: Load registry DAG
    step(1, 3, "Loading registry DAG...")
    extractor = SchemaExtractor(schema_dir=str(ctx.schema_dir))
    dag = extractor.extract()
    log(f"       DAG: {len(dag.nodes)} nodes, {len(dag.edges)} edges")

    # Step 2: Build initial prompt
    step(2, 3, f"Building prompt from registry context for {GWT_ID}...")
    loop = OneShotLoop(dag=dag, ctx=ctx)
    initial_prompt = build_initial_prompt(loop)
    log(f"       Prompt: {len(initial_prompt)} chars")

    # Step 3: LLM generation + verification loop
    step(3, 3, f"Entering LLM loop (max {MAX_RETRIES} attempts)...")
    log("")

    current_prompt = initial_prompt
    last_response = ""
    status = None

    for attempt in range(1, MAX_RETRIES + 1):
        banner(f"Attempt {attempt}/{MAX_RETRIES}")

        # --- Call LLM ---
        log("  Calling Claude via Agent SDK...")
        llm_response = await call_llm(current_prompt)
        last_response = llm_response
        log(f"  Response: {len(llm_response)} chars")

        # Save response
        suffix = "" if attempt == 1 else f"_attempt{attempt}"
        response_file = ctx.session_dir / f"dep_validation_llm_response{suffix}.txt"
        response_file.write_text(llm_response)
        log(f"  Saved to: {response_file.name}")

        # --- Process through pipeline ---
        log("")
        log("  Processing: extract PlusCal → compile → TLC verify...")

        # Fresh loop instance for each attempt
        loop = OneShotLoop(dag=dag, ctx=ctx)
        loop.query(GWT_ID)

        status = loop.process_response(
            llm_response=llm_response,
            module_name=MODULE_NAME,
            cfg_text=DEP_VALIDATION_CFG,
        )

        # --- Report result ---
        log("")
        if status.tlc_result:
            if status.tlc_result.states_found > 0:
                log(f"  TLC explored: {status.tlc_result.states_found:,} states "
                    f"({status.tlc_result.states_distinct:,} distinct)")
            if status.tlc_result.success:
                log("  TLC result: ALL INVARIANTS HOLD")
            elif status.tlc_result.error_message:
                log(f"  TLC error: {status.tlc_result.error_message}")
        else:
            log("  TLC: did not run (compilation failed)")

        log(f"  Loop verdict: {status.result}")

        # --- Check outcome ---
        if status.result == LoopResult.PASS:
            banner("SUCCESS — Spec verified by TLC!")
            break

        # Failed — build retry prompt
        log("")
        log(f"  Sending error feedback to LLM for attempt {attempt + 1}...")

        error_msg = ""
        tlc_output = ""
        counterexample_summary = ""

        if status.tlc_result:
            error_msg = status.tlc_result.error_message or ""
            tlc_output = status.tlc_result.raw_output or ""
        if status.counterexample:
            counterexample_summary = status.counterexample.pluscal_summary
        if status.error:
            error_msg = status.error

        current_prompt = build_retry_prompt(
            initial_prompt, attempt + 1, error_msg, tlc_output, counterexample_summary,
        )

    else:
        banner(f"EXHAUSTED — Failed after {MAX_RETRIES} attempts")
        log("The LLM could not produce a spec that passes TLC verification.")
        log("Consider simplifying the requirements or adjusting CONSTANTS.")
        return

    # --- Bridge phase ---
    if status and status.result == LoopResult.PASS:
        banner("Running bridge on verified spec...")

        compiled_path = status.compiled_spec_path
        if compiled_path and compiled_path.exists():
            compiled_text = compiled_path.read_text()
            log(f"  Using compiled spec: {compiled_path}")
        else:
            compiled_text = last_response
            log("  WARNING: compiled spec not found, using raw LLM response")

        bridge_result = run_bridge(compiled_text)
        log(f"  Module:          {bridge_result.module_name}")
        log(f"  data_structures: {len(bridge_result.data_structures)}")
        log(f"  operations:      {len(bridge_result.operations)}")
        log(f"  verifiers:       {len(bridge_result.verifiers)}")
        log(f"  assertions:      {len(bridge_result.assertions)}")

        # Save bridge artifacts
        ctx.artifact_dir.mkdir(parents=True, exist_ok=True)
        artifact_file = ctx.artifact_dir / "dep_validation_bridge_artifacts.json"
        artifact_file.write_text(json.dumps({
            "module_name": bridge_result.module_name,
            "data_structures": bridge_result.data_structures,
            "operations": bridge_result.operations,
            "verifiers": bridge_result.verifiers,
            "assertions": bridge_result.assertions,
        }, indent=2))
        log(f"  Artifacts saved: {artifact_file.name}")

        # Copy verified spec to instances directory
        instances_dir = ctx.spec_dir
        dest_tla = instances_dir / f"{MODULE_NAME}.tla"
        dest_cfg = instances_dir / f"{MODULE_NAME}.cfg"
        if compiled_path and compiled_path.exists():
            shutil.copy2(compiled_path, dest_tla)
            cfg_src = compiled_path.with_suffix(".cfg")
            if cfg_src.exists():
                shutil.copy2(cfg_src, dest_cfg)
            log(f"  Spec saved to: {dest_tla.relative_to(ctx.engine_root)}")

        # Generate tests mechanically from bridge artifacts
        banner("Generating tests from bridge artifacts...")
        test_path = generate_tests(bridge_result)
        log(f"  Generated: {test_path.name}")
        log(f"  Lines: {test_path.read_text().count(chr(10))}")

        # Run generated tests
        banner("Running generated tests...")
        result = subprocess.run(
            ["python3", "-m", "pytest", str(test_path), "-v", "--tb=short"],
            capture_output=True, text=True,
            cwd=str(ctx.python_dir),
        )
        log(result.stdout)
        if result.returncode != 0 and result.stderr:
            log(result.stderr)

        banner("Phase 6 pipeline complete!")
        if result.returncode == 0:
            log("  All generated tests PASS.")
        else:
            log("  Some tests failed — implement validate_edge() in dag.py.")


def generate_tests(bridge_result: "BridgeResult") -> Path:
    """Mechanically generate a pytest file from bridge verifiers and assertions.

    Maps each bridge verifier to a concrete test method that exercises the
    validate_edge() implementation against the invariant the TLA+ spec verified.
    """
    verifier_names = list(bridge_result.verifiers.keys())
    assertion_names = list(bridge_result.assertions.keys())

    inv_list = ", ".join(verifier_names)

    def _esc(s: str) -> str:
        return s.replace("\\", "/").replace("\n", " ").replace('"', "'")

    test_methods = []
    for vname, verifier in bridge_result.verifiers.items():
        conds = verifier.get("conditions", [])
        applies_to = verifier.get("applies_to", [])
        cond_str = " AND ".join(conds) if conds else "TRUE"

        test_methods.append(
            f'    def test_{vname.lower()}(self):\n'
            f'        """Verifier {vname}: {_esc(verifier.get("message", "")[:80])}"""\n'
            f'        # Bridge condition: {_esc(cond_str[:120])}\n'
            f'        # Applies to: {", ".join(applies_to)}\n'
            f'        self._check_invariant("{vname}")\n'
        )

    test_content = f'''\
"""Generated test suite from {MODULE_NAME}.tla via Bridge (Phase 6).

Mechanically generated from bridge artifacts by run_dep_validation_loop.py.
Verifiers: {inv_list}
"""

import pytest
from registry.dag import RegistryDag, CycleError, NodeNotFoundError
from registry.types import Node, Edge, EdgeType, NodeKind, ValidationResult


class TestDepValidationInvariants:
    """Tests mechanically derived from {MODULE_NAME}.tla bridge verifiers."""

    def _make_chain_dag(self):
        """a -> b -> c (linear chain, all resources)."""
        dag = RegistryDag()
        for nid in ("a", "b", "c"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "c", EdgeType.DEPENDS_ON))
        return dag

    def _make_typed_dag(self):
        """DAG with mixed node kinds: req-r1, behavior-b1, resource-x1, test-t1."""
        dag = RegistryDag()
        dag.add_node(Node.requirement("r1", "a requirement"))
        dag.add_node(Node.behavior("b1", "a_behavior", "given", "when", "then"))
        dag.add_node(Node.resource("x1", "a_resource", description="test"))
        dag.add_node(Node(id="t1", kind=NodeKind.TEST, name="a_test"))
        # r1 → b1 → x1 (valid chain)
        dag.add_edge(Edge("r1", "b1", EdgeType.DECOMPOSES))
        dag.add_edge(Edge("b1", "x1", EdgeType.IMPLEMENTS))
        return dag

    def _check_invariant(self, name):
        method = getattr(self, f"_verify_{{name}}", None)
        if method:
            method()

    # -- Invariant verification methods --

    def _verify_AcyclicityPreserved(self):
        """Edge that would create cycle is rejected."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("c", "a", EdgeType.DEPENDS_ON)
        assert not result.valid, "AcyclicityPreserved: cycle-creating edge should be invalid"
        assert "cycle" in result.reason.lower()

    def _verify_DuplicateRejected(self):
        """Duplicate edge is rejected."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "b", EdgeType.DEPENDS_ON)
        assert not result.valid, "DuplicateRejected: duplicate edge should be invalid"
        assert "duplicate" in result.reason.lower()

    def _verify_KindCompatibilityEnforced(self):
        """Behavior depending on test is rejected."""
        dag = self._make_typed_dag()
        result = dag.validate_edge("b1", "t1", EdgeType.DEPENDS_ON)
        assert not result.valid, "KindCompatibilityEnforced: behavior→test should be invalid"
        assert "kind" in result.reason.lower()

    def _verify_ValidEdgeAccepted(self):
        """Valid edge passes validation."""
        dag = self._make_chain_dag()
        dag.add_node(Node.resource("d", "node_d", description="test"))
        result = dag.validate_edge("c", "d", EdgeType.DEPENDS_ON)
        assert result.valid, f"ValidEdgeAccepted: valid edge rejected with reason: {{result.reason}}"

    def _verify_ValidState(self):
        """validate_edge returns a valid ValidationResult."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "c", EdgeType.DEPENDS_ON)
        assert isinstance(result, ValidationResult)
        assert result.from_id == "a"
        assert result.to_id == "c"

    def _verify_BoundedExecution(self):
        """Result is deterministic and finite."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "b", EdgeType.DEPENDS_ON)
        assert isinstance(result, ValidationResult)

{chr(10).join(test_methods)}
    # -- Additional invariant-derived tests --

    def test_valid_new_edge(self):
        """ValidEdgeAccepted: new edge to new node passes."""
        dag = self._make_chain_dag()
        dag.add_node(Node.resource("d", "node_d", description="test"))
        result = dag.validate_edge("a", "d", EdgeType.DEPENDS_ON)
        assert result.valid
        assert result.reason == ""

    def test_cycle_direct(self):
        """AcyclicityPreserved: direct back-edge rejected."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("b", "a", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "cycle" in result.reason.lower()

    def test_cycle_transitive(self):
        """AcyclicityPreserved: transitive cycle rejected."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("c", "a", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "cycle" in result.reason.lower()

    def test_self_loop_rejected(self):
        """AcyclicityPreserved: self-loop is a cycle."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "a", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "cycle" in result.reason.lower()

    def test_duplicate_exact(self):
        """DuplicateRejected: exact same edge rejected."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "b", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "duplicate" in result.reason.lower()

    def test_same_nodes_different_type_ok(self):
        """DuplicateRejected: same nodes but different edge type is OK."""
        dag = self._make_chain_dag()
        result = dag.validate_edge("a", "b", EdgeType.REFERENCES)
        assert result.valid

    def test_requirement_to_test_rejected(self):
        """KindCompatibilityEnforced: requirement→test depends_on rejected."""
        dag = self._make_typed_dag()
        result = dag.validate_edge("r1", "t1", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "kind" in result.reason.lower()

    def test_behavior_to_test_rejected(self):
        """KindCompatibilityEnforced: behavior→test depends_on rejected."""
        dag = self._make_typed_dag()
        result = dag.validate_edge("b1", "t1", EdgeType.DEPENDS_ON)
        assert not result.valid
        assert "kind" in result.reason.lower()

    def test_resource_to_test_ok(self):
        """KindCompatibilityEnforced: resource→test depends_on is allowed."""
        dag = self._make_typed_dag()
        result = dag.validate_edge("x1", "t1", EdgeType.DEPENDS_ON)
        assert result.valid

    def test_kind_check_only_on_depends_on(self):
        """KindCompatibilityEnforced: kind check only applies to depends_on edges."""
        dag = self._make_typed_dag()
        result = dag.validate_edge("b1", "t1", EdgeType.REFERENCES)
        assert result.valid

    def test_missing_from_node(self):
        """NodeNotFoundError for missing source node."""
        dag = self._make_chain_dag()
        with pytest.raises(NodeNotFoundError):
            dag.validate_edge("nonexistent", "a", EdgeType.DEPENDS_ON)

    def test_missing_to_node(self):
        """NodeNotFoundError for missing target node."""
        dag = self._make_chain_dag()
        with pytest.raises(NodeNotFoundError):
            dag.validate_edge("a", "nonexistent", EdgeType.DEPENDS_ON)

    def test_does_not_mutate_dag(self):
        """validate_edge must not modify the DAG."""
        dag = self._make_chain_dag()
        edges_before = len(dag.edges)
        nodes_before = len(dag.nodes)
        dag.add_node(Node.resource("d", "node_d", description="test"))
        dag.validate_edge("a", "d", EdgeType.DEPENDS_ON)
        assert len(dag.edges) == edges_before
        assert len(dag.nodes) == nodes_before + 1
'''

    ctx.test_output_dir.mkdir(parents=True, exist_ok=True)
    test_path = ctx.test_output_dir / f"test_{MODULE_NAME}.py"
    test_path.write_text(test_content)
    return test_path


if __name__ == "__main__":
    asyncio.run(run_loop())
