#!/usr/bin/env python3
"""Run the one-shot loop to generate a change propagation spec (Phase 8 self-hosting).

Fourth feature built through the pipeline:
  1. Plain language requirement → GWT behaviors (registered in DAG)
  2. Registry context → LLM prompt → PlusCal spec → TLC verification
  3. Bridge → test generation
  4. Implementation to pass the tests
"""

import asyncio
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Must unset CLAUDECODE to allow launching a sub-session from within Claude Code
os.environ.pop("CLAUDECODE", None)

import claude_agent_sdk

# Add python/ to path so registry imports work
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "python"))

LOG_FILE = PROJECT_ROOT / "change_prop_loop_output.log"
_log_fh = open(LOG_FILE, "w")

MAX_RETRIES = 5
MODULE_NAME = "change_propagation"
GWT_ID = "gwt-0021"


def log(msg: str) -> None:
    print(msg, flush=True)
    _log_fh.write(msg + "\n")
    _log_fh.flush()


def banner(msg: str) -> None:
    log("")
    log("=" * 70)
    log(f"  {msg}")
    log("=" * 70)
    log("")


def step(num: int, total: int, msg: str) -> None:
    log(f"  [{num}/{total}] {msg}")


from registry.extractor import SchemaExtractor
from registry.one_shot_loop import OneShotLoop, LoopResult
from registry.bridge import run_bridge


# TLC config for the change propagation spec
CHANGE_PROP_CFG = """\
\\* Change propagation TLC config (generated by run_change_prop_loop.py)
SPECIFICATION Spec

CONSTANTS
    MaxSteps = 15
    NumNodes = 4
    MaxEdges = 5
    MaxArtifacts = 3

INVARIANTS
    ValidState
    BoundedExecution
    NoFalsePositives
    NoFalseNegatives
    SelfTestIncluded
"""


def build_initial_prompt(loop: OneShotLoop) -> str:
    """Build the initial LLM prompt from registry context + instructions."""
    loop.query(GWT_ID)
    context = loop.format_prompt()

    template_path = PROJECT_ROOT / "templates" / "pluscal" / "state_machine.tla"
    template_text = template_path.read_text()

    return f"""You are generating a PlusCal specification for a change propagation query —
a function that, given a target node in a DAG and a mapping from node IDs to test file
paths (test_artifacts), returns the list of test file paths affected by a change to
the target node. The function works by computing the impact set (all nodes that
transitively depend on the target) and then looking up which of those nodes (plus the
target itself) have entries in the test_artifacts mapping.

## Registry Context (from the DAG)

{context}

## State Machine Template (use this pattern)

```tla
{template_text}
```

## Requirements

Generate a COMPLETE PlusCal specification (inside a TLA+ module) for a change
propagation state machine with these characteristics:

**Module name:** {MODULE_NAME} (the MODULE name MUST be {MODULE_NAME})

**The problem:** Given a directed acyclic graph with NumNodes nodes (1..NumNodes),
an adjacency relation, a test_artifacts mapping (partial function from nodes to
artifact IDs 1..MaxArtifacts), and a target node T, compute:
1. **Impact set:** all nodes that transitively depend on T (reverse closure — nodes
   whose forward closure contains T)
2. **Candidates:** impact set UNION {{T}}
3. **Affected tests:** for each node in candidates that has an entry in test_artifacts,
   include that artifact ID in the result set

**CONSTANTS:** MaxSteps, NumNodes, MaxEdges, MaxArtifacts

**States:** idle, building_graph, assigning_artifacts, selecting_target,
computing_impact, collecting_tests, done, failed

**State variables (beyond current_state):**
- adjacency: function from 1..NumNodes to sets of node IDs (successors)
- edge_count: number of edges in the graph
- test_artifacts: function from 1..NumNodes to 0..MaxArtifacts (0 = no artifact)
- artifact_count: number of nodes with artifacts assigned
- target: the selected target node (0 = not selected)
- impact_set: set of nodes that transitively depend on target (reverse closure)
- candidates: impact_set UNION {{target}}
- affected_tests: set of artifact IDs in the result
- step_count, op, result, dirty (control variables)

**Transitions:**
- idle → building_graph: initialize adjacency = [n \\in 1..NumNodes |-> {{}}],
  edge_count = 0, test_artifacts = [n \\in 1..NumNodes |-> 0], artifact_count = 0

- building_graph → building_graph: nondeterministically add forward edges (i < j only,
  to maintain DAG property). Up to MaxEdges edges total.

- building_graph → assigning_artifacts: done adding edges.

- assigning_artifacts → assigning_artifacts: nondeterministically pick a node with no
  artifact and assign it an artifact ID (1..MaxArtifacts). Up to MaxArtifacts assignments.

- assigning_artifacts → selecting_target: done assigning artifacts.

- selecting_target → computing_impact: pick target from 1..NumNodes nondeterministically.
  Initialize: impact_set = {{}}.

- computing_impact: Compute reverse closure. For each node n in 1..NumNodes (n # target),
  check if target is in the forward closure of n. If yes, add n to impact_set.
  The forward closure of n is computed by BFS from n following adjacency edges.
  This can be done in a single step (iterate all nodes, for each do reachability check).

- computing_impact → collecting_tests: impact computation complete.
  Set candidates = impact_set \\union {{target}}.

- collecting_tests: For each node in candidates, if test_artifacts[node] # 0,
  add test_artifacts[node] to affected_tests.
  This can also be done in a single step.

- collecting_tests → done: finalize result.

- any state → failed: step_count >= MaxSteps

**Invariants (in define block):**
- ValidState: current_state \\in StateSet
- BoundedExecution: step_count <= MaxSteps
- NoFalsePositives: when done, for every artifact ID a in affected_tests, there exists
  a node n in candidates such that test_artifacts[n] = a. Guard with dirty.
- NoFalseNegatives: when done, for every node n in candidates where
  test_artifacts[n] # 0, test_artifacts[n] \\in affected_tests. Guard with dirty.
- SelfTestIncluded: when done, if test_artifacts[target] # 0, then
  test_artifacts[target] \\in affected_tests. Guard with dirty.

**Two-phase action model:** Use a `dirty` flag. Set dirty=TRUE when mutating
primary state, then set dirty=FALSE when derived state is consistent. Gate
invariants on dirty with `dirty = TRUE \\/` prefix.

**Process:** Single fair process "main" with a while loop that terminates
when current_state is in done/failed or step_count >= MaxSteps. Use
`either/or` for nondeterministic choice between transitions.

**Implementation note on reachability:**
To check if target is reachable from node n, compute BFS from n following
adjacency. You can define a helper operator Reachable(start, adj) in the define
block that returns the set of all nodes reachable from start via adj.
Use: target \\in Reachable(n, adjacency) to test.

A simple recursive/fixpoint definition:
```
Reachable(start, adj) ==
    LET RECURSIVE Reach(_)
        Reach(visited) ==
            LET next == UNION {{adj[n] : n \\in visited}} \\ visited
            IN IF next = {{}} THEN visited ELSE Reach(visited \\union next)
    IN Reach({{start}})
```

**PlusCal LABEL RULES (CRITICAL — pcal.trans will reject without these):**

In PlusCal, when you have an `if` statement inside an `either` branch, and the
if body contains multiple assignments OR the else branch exists, you MUST add
a label AFTER the first group of assignments in the if branch. PlusCal requires
labels at "control flow join points."

CORRECT pattern (two-phase with labels):
```
either
    ActionLabel:
        if guard then
            \\* first assignments (Phase 1: mutate data)
            var1 := val1;
            dirty := TRUE;
            step_count := step_count + 1;
        ActionDecide:
            \\* second phase (Phase 2: transition state)
            current_state := "next_state";
            dirty := FALSE;
        else
            op := "skip";
        end if;
or
    ...
end either;
```

**PlusCal `with` RULES (CRITICAL — pcal.trans will reject violations):**

1. You CANNOT put a label inside a `with` statement.
2. You CANNOT assign to the same variable twice inside a single `with` block.
3. Keep `with` blocks simple: use only for nondeterministic choice (like
   picking from worklist), with assignments to DIFFERENT variables.
4. After the `with`/`end with`, you can have more assignments and labels.

**IMPORTANT adjacency representation:**
Initialize: adjacency = [n \\in 1..NumNodes |-> {{}}]
To add edge i→j: adjacency := [adjacency EXCEPT ![i] = adjacency[i] \\union {{j}}]
Only allow i < j during graph building (DAG constraint). No self-loops.

**IMPORTANT test_artifacts representation:**
Initialize: test_artifacts = [n \\in 1..NumNodes |-> 0]
0 means no artifact. Assign: test_artifacts := [test_artifacts EXCEPT ![n] = artifactId]

**OUTPUT FORMAT:** Output ONLY the TLA+ module — no markdown fencing, no
explanation, no commentary. The module should contain:
1. MODULE line (MUST be `{MODULE_NAME}`)
2. EXTENDS Integers, FiniteSets, Sequences, TLC
3. CONSTANTS
4. (* --algorithm ... end algorithm; *)
5. The closing ===... line
"""


def build_retry_prompt(original_prompt: str, attempt: int, error_msg: str,
                       tlc_output: str | None, counterexample_summary: str | None) -> str:
    """Build a retry prompt with error feedback for the LLM."""
    parts = [original_prompt]
    parts.append(f"\n\n## RETRY (attempt {attempt}) — Previous Attempt Failed\n")

    if counterexample_summary:
        parts.append(f"**TLC counterexample:**\n```\n{counterexample_summary}\n```\n")

    if error_msg:
        parts.append(f"**Error:** {error_msg}\n")

    if tlc_output:
        error_start = tlc_output.find("Error:")
        if error_start >= 0:
            parts.append(f"**TLC output (error section):**\n```\n{tlc_output[error_start:error_start+1500]}\n```\n")
        elif "Unrecoverable" in tlc_output:
            recov_start = tlc_output.find("Unrecoverable")
            parts.append(f"**Compiler output:**\n```\n{tlc_output[recov_start:recov_start+1000]}\n```\n")

    parts.append(
        f"\nFix the specification to resolve this issue. Output the COMPLETE "
        f"corrected TLA+ module (not just the changed parts). "
        f"The MODULE name MUST be `{MODULE_NAME}`. "
        f"Remember: NO labels inside `with`, NO double assignment to same var in `with`, "
        f"NO Seq() in invariants (use bounded [1..N -> 1..M] instead)."
    )

    return "\n".join(parts)


async def call_llm(prompt: str) -> str:
    """Call Claude via the Agent SDK and collect the text response."""
    options = claude_agent_sdk.ClaudeAgentOptions(
        allowed_tools=[],
        system_prompt=(
            "You are a TLA+/PlusCal expert. Generate complete, syntactically correct "
            "PlusCal specifications embedded in TLA+ modules. Output ONLY the TLA+ module "
            "content — no markdown fencing, no explanation, no commentary. The output must "
            "be directly compilable by pcal.trans and verifiable by TLC."
        ),
        max_turns=1,
        model="claude-sonnet-4-20250514",
    )

    result_text = []
    async for message in claude_agent_sdk.query(prompt=prompt, options=options):
        if isinstance(message, claude_agent_sdk.AssistantMessage):
            for block in message.content:
                if isinstance(block, claude_agent_sdk.TextBlock):
                    result_text.append(block.text)
        elif isinstance(message, claude_agent_sdk.ResultMessage):
            if message.result:
                result_text.append(message.result)

    return "\n".join(result_text)


async def run_loop() -> None:
    """Execute the one-shot loop with real LLM calls and retry on failure."""
    banner("Phase 8 Self-Hosting: Change Propagation Spec Generation")

    # Step 1: Load registry DAG
    step(1, 3, "Loading registry DAG...")
    extractor = SchemaExtractor(schema_dir=str(PROJECT_ROOT / "schema"))
    dag = extractor.extract()
    log(f"       DAG: {len(dag.nodes)} nodes, {len(dag.edges)} edges")

    # Step 2: Build initial prompt
    step(2, 3, f"Building prompt from registry context for {GWT_ID}...")
    loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
    initial_prompt = build_initial_prompt(loop)
    log(f"       Prompt: {len(initial_prompt)} chars")

    # Step 3: LLM generation + verification loop
    step(3, 3, f"Entering LLM loop (max {MAX_RETRIES} attempts)...")
    log("")

    current_prompt = initial_prompt
    last_response = ""
    status = None

    for attempt in range(1, MAX_RETRIES + 1):
        banner(f"Attempt {attempt}/{MAX_RETRIES}")

        # --- Call LLM ---
        log("  Calling Claude via Agent SDK...")
        llm_response = await call_llm(current_prompt)
        last_response = llm_response
        log(f"  Response: {len(llm_response)} chars")

        # Save response
        suffix = "" if attempt == 1 else f"_attempt{attempt}"
        response_file = PROJECT_ROOT / f"change_prop_llm_response{suffix}.txt"
        response_file.write_text(llm_response)
        log(f"  Saved to: {response_file.name}")

        # --- Process through pipeline ---
        log("")
        log("  Processing: extract PlusCal → compile → TLC verify...")

        # Fresh loop instance for each attempt
        loop = OneShotLoop(dag=dag, project_root=str(PROJECT_ROOT))
        loop.query(GWT_ID)

        status = loop.process_response(
            llm_response=llm_response,
            module_name=MODULE_NAME,
            cfg_text=CHANGE_PROP_CFG,
        )

        # --- Report result ---
        log("")
        if status.tlc_result:
            if status.tlc_result.states_found > 0:
                log(f"  TLC explored: {status.tlc_result.states_found:,} states "
                    f"({status.tlc_result.states_distinct:,} distinct)")
            if status.tlc_result.success:
                log("  TLC result: ALL INVARIANTS HOLD")
            elif status.tlc_result.error_message:
                log(f"  TLC error: {status.tlc_result.error_message}")
        else:
            log("  TLC: did not run (compilation failed)")

        log(f"  Loop verdict: {status.result}")

        # --- Check outcome ---
        if status.result == LoopResult.PASS:
            banner("SUCCESS — Spec verified by TLC!")
            break

        # Failed — build retry prompt
        log("")
        log(f"  Sending error feedback to LLM for attempt {attempt + 1}...")

        error_msg = ""
        tlc_output = ""
        counterexample_summary = ""

        if status.tlc_result:
            error_msg = status.tlc_result.error_message or ""
            tlc_output = status.tlc_result.raw_output or ""
        if status.counterexample:
            counterexample_summary = status.counterexample.pluscal_summary
        if status.error:
            error_msg = status.error

        current_prompt = build_retry_prompt(
            initial_prompt, attempt + 1, error_msg, tlc_output, counterexample_summary,
        )

    else:
        banner(f"EXHAUSTED — Failed after {MAX_RETRIES} attempts")
        log("The LLM could not produce a spec that passes TLC verification.")
        log("Consider simplifying the requirements or adjusting CONSTANTS.")
        return

    # --- Bridge phase ---
    if status and status.result == LoopResult.PASS:
        banner("Running bridge on verified spec...")

        compiled_path = status.compiled_spec_path
        if compiled_path and compiled_path.exists():
            compiled_text = compiled_path.read_text()
            log(f"  Using compiled spec: {compiled_path}")
        else:
            compiled_text = last_response
            log("  WARNING: compiled spec not found, using raw LLM response")

        bridge_result = run_bridge(compiled_text)
        log(f"  Module:          {bridge_result.module_name}")
        log(f"  data_structures: {len(bridge_result.data_structures)}")
        log(f"  operations:      {len(bridge_result.operations)}")
        log(f"  verifiers:       {len(bridge_result.verifiers)}")
        log(f"  assertions:      {len(bridge_result.assertions)}")

        # Save bridge artifacts
        artifacts_dir = PROJECT_ROOT / "python" / "tests" / "generated"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        artifact_file = artifacts_dir / "change_prop_bridge_artifacts.json"
        artifact_file.write_text(json.dumps({
            "module_name": bridge_result.module_name,
            "data_structures": bridge_result.data_structures,
            "operations": bridge_result.operations,
            "verifiers": bridge_result.verifiers,
            "assertions": bridge_result.assertions,
        }, indent=2))
        log(f"  Artifacts saved: {artifact_file.name}")

        # Copy verified spec to instances directory
        instances_dir = PROJECT_ROOT / "templates" / "pluscal" / "instances"
        dest_tla = instances_dir / f"{MODULE_NAME}.tla"
        dest_cfg = instances_dir / f"{MODULE_NAME}.cfg"
        if compiled_path and compiled_path.exists():
            shutil.copy2(compiled_path, dest_tla)
            cfg_src = compiled_path.with_suffix(".cfg")
            if cfg_src.exists():
                shutil.copy2(cfg_src, dest_cfg)
            log(f"  Spec saved to: {dest_tla.relative_to(PROJECT_ROOT)}")

        # Generate tests mechanically from bridge artifacts
        banner("Generating tests from bridge artifacts...")
        test_path = generate_tests(bridge_result)
        log(f"  Generated: {test_path.name}")
        log(f"  Lines: {test_path.read_text().count(chr(10))}")

        # Run generated tests
        banner("Running generated tests...")
        result = subprocess.run(
            ["python3", "-m", "pytest", str(test_path), "-v", "--tb=short"],
            capture_output=True, text=True,
            cwd=str(PROJECT_ROOT / "python"),
        )
        log(result.stdout)
        if result.returncode != 0 and result.stderr:
            log(result.stderr)

        banner("Phase 8 pipeline complete!")
        if result.returncode == 0:
            log("  All generated tests PASS.")
        else:
            log("  Some tests failed — implement query_affected_tests() in dag.py.")


def generate_tests(bridge_result: "BridgeResult") -> Path:
    """Mechanically generate a pytest file from bridge verifiers and assertions.

    Maps each bridge verifier to a concrete test method that exercises the
    query_affected_tests() implementation against the invariant the TLA+ spec verified.
    """
    verifier_names = list(bridge_result.verifiers.keys())
    assertion_names = list(bridge_result.assertions.keys())

    inv_list = ", ".join(verifier_names)

    def _esc(s: str) -> str:
        return s.replace("\\", "/").replace("\n", " ").replace('"', "'")

    test_methods = []
    for vname, verifier in bridge_result.verifiers.items():
        conds = verifier.get("conditions", [])
        applies_to = verifier.get("applies_to", [])
        cond_str = " AND ".join(conds) if conds else "TRUE"

        test_methods.append(
            f'    def test_{vname.lower()}(self):\n'
            f'        """Verifier {vname}: {_esc(verifier.get("message", "")[:80])}"""\n'
            f'        # Bridge condition: {_esc(cond_str[:120])}\n'
            f'        # Applies to: {", ".join(applies_to)}\n'
            f'        self._check_invariant("{vname}")\n'
        )

    test_content = f'''\
"""Generated test suite from {MODULE_NAME}.tla via Bridge (Phase 8).

Mechanically generated from bridge artifacts by run_change_prop_loop.py.
Verifiers: {inv_list}
"""

import pytest
from registry.dag import RegistryDag, NodeNotFoundError
from registry.types import Node, Edge, EdgeType


class TestChangePropagationInvariants:
    """Tests mechanically derived from {MODULE_NAME}.tla bridge verifiers."""

    def _make_chain_dag(self):
        """a -> b -> c -> d (linear chain, all resources)."""
        dag = RegistryDag()
        for nid in ("a", "b", "c", "d"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "c", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("c", "d", EdgeType.DEPENDS_ON))
        # Assign test artifacts: only "a" has a test
        dag.test_artifacts = {{"a": "tests/generated/test_a.py"}}
        return dag

    def _make_diamond_dag(self):
        """Diamond: a -> b, a -> c, b -> d, c -> d. a and d have tests."""
        dag = RegistryDag()
        for nid in ("a", "b", "c", "d"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("a", "b", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("a", "c", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("b", "d", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("c", "d", EdgeType.DEPENDS_ON))
        dag.test_artifacts = {{
            "a": "tests/generated/test_a.py",
            "d": "tests/generated/test_d.py",
        }}
        return dag

    def _make_no_artifact_dag(self):
        """Three nodes, none with test artifacts."""
        dag = RegistryDag()
        for nid in ("x", "y", "z"):
            dag.add_node(Node.resource(nid, f"node_{{nid}}", description="test"))
        dag.add_edge(Edge("x", "y", EdgeType.DEPENDS_ON))
        dag.add_edge(Edge("y", "z", EdgeType.DEPENDS_ON))
        dag.test_artifacts = {{}}
        return dag

    def _check_invariant(self, name):
        method = getattr(self, f"_verify_{{name}}", None)
        if method:
            method()

    # -- Invariant verification methods --

    def _verify_NoFalsePositives(self):
        """Every returned test path corresponds to a node in the impact set."""
        dag = self._make_chain_dag()
        # Change d (leaf). Impact set of d = nodes that depend on d = {{a, b, c}}.
        # a has a test, so test_a.py should be in result.
        result = dag.query_affected_tests("d")
        for path in result:
            # Verify each path maps to a node in candidates (impact + self)
            found = False
            impact = dag.query_impact("d")
            candidates = impact.affected | {{"d"}}
            for nid in candidates:
                if dag.test_artifacts.get(nid) == path:
                    found = True
                    break
            assert found, f"NoFalsePositives: {{path}} not backed by a candidate node"

    def _verify_NoFalseNegatives(self):
        """Every candidate with a test artifact has its test in the result."""
        dag = self._make_chain_dag()
        result = dag.query_affected_tests("d")
        impact = dag.query_impact("d")
        candidates = impact.affected | {{"d"}}
        for nid in candidates:
            if nid in dag.test_artifacts:
                assert dag.test_artifacts[nid] in result, \\
                    f"NoFalseNegatives: {{nid}}'s test not in result"

    def _verify_SelfTestIncluded(self):
        """If the target itself has a test, it's in the result."""
        dag = self._make_chain_dag()
        # a has a test artifact
        result = dag.query_affected_tests("a")
        assert "tests/generated/test_a.py" in result, \\
            "SelfTestIncluded: target's own test missing"

    def _verify_ValidState(self):
        """query_affected_tests returns a list of strings."""
        dag = self._make_chain_dag()
        result = dag.query_affected_tests("b")
        assert isinstance(result, list)
        for item in result:
            assert isinstance(item, str)

    def _verify_BoundedExecution(self):
        """Result is deterministic and finite."""
        dag = self._make_chain_dag()
        result = dag.query_affected_tests("c")
        assert isinstance(result, list)

{chr(10).join(test_methods)}
    # -- Additional invariant-derived tests --

    def test_upstream_change_propagates(self):
        """gwt-0021: change to upstream node surfaces downstream test."""
        dag = self._make_chain_dag()
        # d is downstream of a (a->b->c->d). Change d, a depends on b->c->d.
        # Actually in DEPENDS_ON: a depends on b, b on c, c on d.
        # So changing d affects c, b, a. a has a test.
        result = dag.query_affected_tests("d")
        assert "tests/generated/test_a.py" in result

    def test_no_downstream_tests_empty(self):
        """gwt-0022: node with no downstream test artifacts returns empty."""
        dag = self._make_no_artifact_dag()
        result = dag.query_affected_tests("z")
        assert result == []

    def test_self_test_included(self):
        """gwt-0023: node that IS test-bearing includes its own test."""
        dag = self._make_diamond_dag()
        result = dag.query_affected_tests("a")
        assert "tests/generated/test_a.py" in result

    def test_diamond_leaf_change(self):
        """Changing d in diamond: a and d have tests, both should appear."""
        dag = self._make_diamond_dag()
        result = dag.query_affected_tests("d")
        assert "tests/generated/test_d.py" in result
        # a depends on b and c, which depend on d, so a is affected
        assert "tests/generated/test_a.py" in result

    def test_diamond_middle_change(self):
        """Changing b in diamond: a depends on b, a has test."""
        dag = self._make_diamond_dag()
        result = dag.query_affected_tests("b")
        assert "tests/generated/test_a.py" in result

    def test_no_false_positives_isolated(self):
        """Node with no dependents returns only its own test (if any)."""
        dag = RegistryDag()
        dag.add_node(Node.resource("solo", "solo_node", description="test"))
        dag.test_artifacts = {{"solo": "tests/generated/test_solo.py"}}
        result = dag.query_affected_tests("solo")
        assert result == ["tests/generated/test_solo.py"]

    def test_no_false_positives_no_artifact(self):
        """Node with no test artifact and no dependents returns empty."""
        dag = RegistryDag()
        dag.add_node(Node.resource("bare", "bare_node", description="test"))
        dag.test_artifacts = {{}}
        result = dag.query_affected_tests("bare")
        assert result == []

    def test_result_sorted(self):
        """Result is sorted for deterministic output."""
        dag = self._make_diamond_dag()
        result = dag.query_affected_tests("d")
        assert result == sorted(result)

    def test_result_deduplicated(self):
        """No duplicate paths in result."""
        dag = self._make_diamond_dag()
        result = dag.query_affected_tests("d")
        assert len(result) == len(set(result))

    def test_missing_node_raises(self):
        """NodeNotFoundError for missing node."""
        dag = self._make_chain_dag()
        with pytest.raises(NodeNotFoundError):
            dag.query_affected_tests("nonexistent")

    def test_does_not_mutate_dag(self):
        """query_affected_tests must not modify the DAG."""
        dag = self._make_chain_dag()
        edges_before = len(dag.edges)
        nodes_before = len(dag.nodes)
        artifacts_before = dict(dag.test_artifacts)
        dag.query_affected_tests("b")
        assert len(dag.edges) == edges_before
        assert len(dag.nodes) == nodes_before
        assert dag.test_artifacts == artifacts_before

    def test_chain_leaf_no_dependents(self):
        """Leaf node with no dependents: only itself in candidates."""
        dag = self._make_chain_dag()
        # a is leaf in dependency direction (nothing depends on a)
        result = dag.query_affected_tests("a")
        # a has test, and nothing depends on a, so only a's test
        assert result == ["tests/generated/test_a.py"]
'''

    output_dir = PROJECT_ROOT / "python" / "tests" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    test_path = output_dir / f"test_{MODULE_NAME}.py"
    test_path.write_text(test_content)
    return test_path


if __name__ == "__main__":
    asyncio.run(run_loop())
