"""cw9 CLI — entry point for using CodeWriter9 on external projects.

Usage:
    cw9 init [target_dir]     Initialize .cw9/ in the target directory
    cw9 status [target_dir]   Show project context and DAG summary
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from collections.abc import Callable
from pathlib import Path

from registry.context import ProjectContext
from registry._resources import is_installed_mode, get_template_dir


def _get_engine_root() -> Path | None:
    """Get ENGINE_ROOT if running from repo checkout, else None."""
    if is_installed_mode():
        return None
    return Path(__file__).resolve().parent.parent.parent


# For backwards compatibility with test imports
ENGINE_ROOT = _get_engine_root()

_CONFIG_TEMPLATE_DEV = """\
# CodeWriter9 project configuration
# Generated by: cw9 init

[engine]
root = "{engine_root}"

[project]
# Add project-specific settings here
"""

_CONFIG_TEMPLATE_INSTALLED = """\
# CodeWriter9 project configuration
# Generated by: cw9 init (installed mode)

[project]
# Add project-specific settings here
"""

_EMPTY_DAG = {
    "nodes": {},
    "edges": [],
    "test_artifacts": {},
}

# ── Module-level constants ──────────────────────────────────────────────
DEFAULT_MODEL = "claude-sonnet-4-6"
SKELETON_SENTINEL = "SKELETON_ONLY"
PLACEHOLDER_UUID = "00000000-0000-0000-0000-000000000000"
DEFAULT_CONCURRENCY = 10
DEFAULT_MAX_RETRIES = 5


def _require_cw9(target: Path) -> Path | None:
    """Return the .cw9 state_root under *target*, or print an error and return None."""
    state_root = target / ".cw9"
    if not state_root.exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        print("Run: cw9 init", file=sys.stderr)
        return None
    return state_root


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()

    if not target.is_dir():
        print(f"Error: {target} is not a directory", file=sys.stderr)
        return 1

    if args.ensure and args.force:
        print("Error: --ensure and --force are mutually exclusive", file=sys.stderr)
        return 1

    state_root = target / ".cw9"

    if args.ensure and state_root.exists():
        return 0

    if state_root.exists() and not args.force:
        print(f".cw9/ already exists in {target}")
        print("Use --force to reinitialize.")
        return 1

    # Create directory structure
    dirs = [
        state_root / "schema",
        state_root / "specs",
        state_root / "bridge",
        state_root / "sessions",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # Write config
    config_path = state_root / "config.toml"
    engine_root = _get_engine_root()
    if engine_root:
        config_path.write_text(
            _CONFIG_TEMPLATE_DEV.format(engine_root=str(engine_root))
        )
    else:
        config_path.write_text(_CONFIG_TEMPLATE_INSTALLED)

    # Write empty DAG
    dag_path = state_root / "dag.json"
    dag_path.write_text(json.dumps(_EMPTY_DAG, indent=2) + "\n")

    # Verify it loads
    ctx = ProjectContext.from_target(target, engine_root)

    # Copy starter schema templates if schema dir is empty
    if ctx.is_self_hosting:
        schema_templates_dir = get_template_dir("schema")
    else:
        schema_templates_dir = get_template_dir("schema_external")
    if schema_templates_dir.is_dir() and not list((state_root / "schema").glob("*.json")):
        for tmpl in schema_templates_dir.glob("*.json"):
            shutil.copy2(tmpl, state_root / "schema" / tmpl.name)

    print(f"Initialized .cw9/ in {target}")
    print()
    print(f"  engine_root:    {ctx.engine_root or '(installed mode)'}")
    print(f"  target_root:    {ctx.target_root}")
    print(f"  state_root:     {ctx.state_root}")
    print(f"  schema_dir:     {ctx.schema_dir}")
    print(f"  spec_dir:       {ctx.spec_dir}")
    print(f"  artifact_dir:   {ctx.artifact_dir}")
    print(f"  session_dir:    {ctx.session_dir}")
    print(f"  test_output_dir:{ctx.test_output_dir}")
    print()
    schemas = list(ctx.schema_dir.glob("*.json"))
    if schemas:
        print(f"  Starter schemas copied ({len(schemas)}):")
        for s in sorted(schemas):
            print(f"    - {s.name}")
        print()
    print("Next steps:")
    print("  1. Edit schemas in .cw9/schema/ to match your project")
    print("  2. Run: cw9 status")

    return 0


def cmd_status(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    from registry.status import gather_status
    status = gather_status(target)

    if getattr(args, "output_json", False):
        print(json.dumps(status.to_dict(), indent=2))
        return 0

    ctx = ProjectContext.from_target(target)
    print(f"CodeWriter9 project: {ctx.target_root}")
    print(f"  engine: {ctx.engine_root or '(installed mode)'}")
    print()

    # Scoreboard
    parts = []
    if status.verified:
        parts.append(f"{status.verified} verified")
    if status.failed:
        parts.append(f"{status.failed} failed")
    if status.in_progress:
        parts.append(f"{status.in_progress} in progress")
    if status.pending:
        parts.append(f"{status.pending} pending")
    print(f"Pipeline: {', '.join(parts) or 'no GWTs'} ({status.total} total)")
    if status.verified:
        print(f"Bridge:   {status.bridge_complete}/{status.verified} complete")
    print()

    if not status.gwts:
        return 0

    # Per-GWT table
    print(f"  {'GWT':<16} {'SPEC':<14} {'ATTEMPTS':<10} {'BRIDGE':<8}")
    for gwt_id, gs in sorted(status.gwts.items()):
        result_str = gs.result.upper()
        attempts_str = str(gs.attempts) if gs.attempts > 0 else "-"
        bridge_str = "DONE" if gs.bridge_done else "-"
        print(f"  {gwt_id:<16} {result_str:<14} {attempts_str:<10} {bridge_str:<8}")

    # Failed summary
    failed = {gid: gs for gid, gs in status.gwts.items() if gs.result == "fail"}
    if failed:
        print()
        print(f"Failed ({len(failed)}):")
        for gwt_id, gs in sorted(failed.items()):
            err = gs.error or "unknown error"
            print(f"  {gwt_id}  {err}")

    return 0


def cmd_extract(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    ctx = ProjectContext.from_target(target)
    dag_path = state_root / "dag.json"

    # Load old DAG for diff summary
    old_nodes, old_edges = 0, 0
    if dag_path.exists():
        from registry.dag import RegistryDag
        old_dag = RegistryDag.load(dag_path)
        old_nodes = old_dag.node_count
        old_edges = old_dag.edge_count

    # Extract fresh DAG from schemas
    from registry.extractor import SchemaExtractor
    extractor = SchemaExtractor(schema_dir=str(ctx.schema_dir), self_host=ctx.is_self_hosting)
    dag = extractor.extract()

    # Save
    dag.save(dag_path)

    # Diff summary
    new_nodes = dag.node_count
    new_edges = dag.edge_count
    dn = new_nodes - old_nodes
    de = new_edges - old_edges
    sign = lambda x: f"+{x}" if x > 0 else str(x)
    print(f"DAG updated: {new_nodes} nodes ({sign(dn)}), {new_edges} edges ({sign(de)})")

    return 0


def _run_loop_core(
    target: Path,
    gwt_id: str,
    max_retries: int = 4,
    context_file: Path | None = None,
) -> int:
    """Core loop logic with explicit parameters (no argparse.Namespace)."""
    import asyncio

    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    from registry.loop_runner import run_loop
    from registry.one_shot_loop import LoopResult

    ctx = ProjectContext.from_target(target)
    dag_path = state_root / "dag.json"
    context_text = ""
    if context_file and context_file.exists():
        context_text = context_file.read_text()
    result, spec_path = asyncio.run(run_loop(
        ctx=ctx,
        gwt_id=gwt_id,
        max_retries=max_retries,
        context_text=context_text,
        dag_path=dag_path,
    ))

    if result == LoopResult.PASS:
        print(f"Verified: {spec_path}")
        return 0
    else:
        print("Loop failed.", file=sys.stderr)
        return 1


def cmd_loop(args: argparse.Namespace) -> int:
    return _run_loop_core(
        target=Path(args.target_dir).resolve(),
        gwt_id=args.gwt_id,
        max_retries=args.max_retries,
        context_file=args.context_file,
    )


def _run_bridge_core(target: Path, gwt_id: str) -> int:
    """Core bridge logic with explicit parameters (no argparse.Namespace)."""
    if _require_cw9(target) is None:
        return 1

    ctx = ProjectContext.from_target(target)

    spec_path = ctx.spec_dir / f"{gwt_id}.tla"
    if not spec_path.exists():
        print(f"No verified spec found: {spec_path}", file=sys.stderr)
        print(f"Run: cw9 loop {gwt_id}", file=sys.stderr)
        return 1

    from registry.bridge import run_bridge, TlcTrace
    tla_text = spec_path.read_text()

    # Load counterexample traces (from retry failures)
    traces_path = ctx.spec_dir / f"{gwt_id}_traces.json"
    traces = []
    if traces_path.exists():
        traces_data = json.loads(traces_path.read_text())
        traces = [TlcTrace(**td) for td in traces_data]

    result = run_bridge(tla_text, traces=traces)

    artifacts = {
        "gwt_id": gwt_id,
        "module_name": result.module_name,
        "data_structures": result.data_structures,
        "operations": result.operations,
        "verifiers": result.verifiers,
        "assertions": result.assertions,
        "test_scenarios": [
            {"name": s.name, "setup": s.setup, "steps": s.steps,
             "expected_outcome": s.expected_outcome, "invariant_tested": s.invariant_tested}
            for s in result.test_scenarios
        ],
    }

    # v5: Load simulation traces (primary context for gen-tests)
    sim_traces_path = ctx.spec_dir / f"{gwt_id}_sim_traces.json"
    if sim_traces_path.exists():
        artifacts["simulation_traces"] = json.loads(sim_traces_path.read_text())
    else:
        artifacts["simulation_traces"] = []

    ctx.artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact_path = ctx.artifact_dir / f"{gwt_id}_bridge_artifacts.json"
    artifact_path.write_text(json.dumps(artifacts, indent=2) + "\n")

    print(f"Bridge artifacts saved: {artifact_path}")
    print(f"  data_structures: {len(result.data_structures)}")
    print(f"  operations: {len(result.operations)}")
    print(f"  verifiers: {len(result.verifiers)}")
    print(f"  assertions: {len(result.assertions)}")

    return 0


def cmd_bridge(args: argparse.Namespace) -> int:
    return _run_bridge_core(
        target=Path(args.target_dir).resolve(),
        gwt_id=args.gwt_id,
    )


def cmd_gen_tests(args: argparse.Namespace) -> int:
    import asyncio

    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    ctx = ProjectContext.from_target(target)
    gwt_id = args.gwt_id

    # Load bridge artifacts
    artifact_path = ctx.artifact_dir / f"{gwt_id}_bridge_artifacts.json"
    if not artifact_path.exists():
        print(f"No bridge artifacts found: {artifact_path}", file=sys.stderr)
        print(f"Run: cw9 bridge {gwt_id}", file=sys.stderr)
        return 1

    bridge_artifacts = json.loads(artifact_path.read_text())
    module_name = bridge_artifacts.get("module_name", gwt_id)

    # Load GWT text from DAG
    from registry.dag import RegistryDag
    dag_path = state_root / "dag.json"
    gwt_text = {"given": "", "when": "", "then": ""}
    if dag_path.exists():
        dag = RegistryDag.load(dag_path)
        if gwt_id in dag.nodes:
            node = dag.nodes[gwt_id]
            gwt_text = {
                "given": node.given or "",
                "when": node.when or "",
                "then": node.then or "",
            }

    # Build context
    from registry.lang import TargetLanguage, get_profile
    from registry.test_gen_loop import (
        TestGenContext, build_compiler_hints, discover_api_context,
        run_test_gen_loop,
    )

    lang_profile = get_profile(TargetLanguage(args.lang))
    compiler_hints = build_compiler_hints(bridge_artifacts, lang_profile)
    api_context = lang_profile.discover_api_context(ctx.python_dir, module_name)
    test_scenarios = bridge_artifacts.get("test_scenarios", [])

    # v5: Load simulation traces (PRIMARY context for test generation)
    simulation_traces = bridge_artifacts.get("simulation_traces", [])
    if not simulation_traces:
        sim_traces_path = ctx.spec_dir / f"{gwt_id}_sim_traces.json"
        if sim_traces_path.exists():
            simulation_traces = json.loads(sim_traces_path.read_text())

    # v5: Load TLA+ spec text (full picture, rank 4 context)
    tla_spec_text = ""
    spec_path = ctx.spec_dir / f"{gwt_id}.tla"
    if spec_path.exists():
        tla_spec_text = spec_path.read_text()

    gen_ctx = TestGenContext(
        gwt_id=gwt_id,
        gwt_text=gwt_text,
        module_name=module_name,
        bridge_artifacts=bridge_artifacts,
        compiler_hints=compiler_hints,
        api_context=api_context,
        test_scenarios=test_scenarios,
        simulation_traces=simulation_traces,
        tla_spec_text=tla_spec_text,
        output_dir=ctx.test_output_dir,
        source_dir=ctx.python_dir,
        lang_profile=lang_profile,
    )

    from registry.loop_runner import call_llm

    session_dir = ctx.state_root / "sessions"
    result = asyncio.run(run_test_gen_loop(
        gen_ctx, call_llm,
        max_attempts=args.max_attempts,
        session_dir=session_dir,
    ))

    if result.passed:
        output_name = lang_profile.test_file_name(gwt_id)
        test_path = ctx.test_output_dir / output_name
        print(f"Generated: {test_path} ({result.attempt} attempt(s))")
        return 0
    else:
        print(f"Failed after {result.attempt} attempts", file=sys.stderr)
        for err in result.errors:
            print(f"  {err}", file=sys.stderr)
        return 1


def _register_payload(target: Path, payload: dict) -> dict:
    """Register requirements + GWT behaviors from a dict. Returns result dict.

    Returns:
        {"requirements": [{"id": cw7_id, "req_id": req_id}, ...],
         "gwts": [{"criterion_id": criterion_id, "gwt_id": gwt_id}, ...]}
    """
    from registry.dag import RegistryDag
    from registry.bindings import load_bindings, save_bindings

    state_root = target / ".cw9"
    ctx = ProjectContext.from_target(target)
    dag_path = state_root / "dag.json"
    dag = RegistryDag.load(dag_path)
    bindings = load_bindings(state_root)

    requirements = payload.get("requirements", [])
    gwts = payload.get("gwts", [])

    # Phase 1: Register requirements
    req_output = []
    req_id_map = {}  # CW7 id -> CW9 req-NNNN
    for req in requirements:
        cw7_id = req["id"]
        binding_key = f"req:{cw7_id}"

        if binding_key in bindings:
            req_id = bindings[binding_key]
        else:
            req_id = dag.register_requirement(
                text=req.get("text", cw7_id),
                name=req.get("name"),
            )
            bindings[binding_key] = req_id

        req_id_map[cw7_id] = req_id
        req_output.append({"id": cw7_id, "req_id": req_id})

    # Phase 2: Register GWTs
    gwt_output = []
    for gwt in gwts:
        criterion_id = gwt["criterion_id"]
        binding_key = f"gwt:{criterion_id}"

        if binding_key in bindings:
            gwt_id = bindings[binding_key]
        else:
            # Resolve parent_req: CW7 id -> CW9 req-NNNN
            parent_req = None
            if gwt.get("parent_req"):
                cw7_req_id = gwt["parent_req"]
                parent_req = req_id_map.get(cw7_req_id)
                if parent_req is None:
                    # Check if it's already a CW9 req-NNNN ID in the DAG
                    if cw7_req_id in dag.nodes:
                        parent_req = cw7_req_id
                    else:
                        # Check bindings from a prior run
                        parent_req = bindings.get(f"req:{cw7_req_id}")

            gwt_id = dag.register_gwt(
                given=gwt["given"],
                when=gwt["when"],
                then=gwt["then"],
                parent_req=parent_req,
                name=gwt.get("name"),
            )
            bindings[binding_key] = gwt_id

            # Wire DEPENDS_ON edges to crawl-originated RESOURCE nodes
            from registry.types import Edge, EdgeType
            for dep_uuid in gwt.get("depends_on", []):
                if dep_uuid in dag.nodes:
                    try:
                        dag.add_edge(Edge(gwt_id, dep_uuid, EdgeType.DEPENDS_ON))
                    except Exception:
                        pass  # silently skip invalid edges (matching _add_edge_safe)

        gwt_output.append({"criterion_id": criterion_id, "gwt_id": gwt_id})

    # Save
    dag.save(dag_path)
    save_bindings(state_root, bindings)

    return {"requirements": req_output, "gwts": gwt_output}


def cmd_register(args: argparse.Namespace) -> int:
    """Register requirements + GWT behaviors from JSON stdin. Emit JSON stdout."""
    target = Path(args.target_dir).resolve()
    if _require_cw9(target) is None:
        return 1

    # Read and parse stdin
    try:
        payload = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, ValueError) as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}), file=sys.stderr)
        return 1

    # Validate requirements have id
    for i, req in enumerate(payload.get("requirements", [])):
        if "id" not in req:
            print(json.dumps({"error": f"requirements[{i}]: missing required field 'id'"}),
                  file=sys.stderr)
            return 1

    # Validate GWTs have criterion_id and given/when/then
    for i, gwt in enumerate(payload.get("gwts", [])):
        if "criterion_id" not in gwt:
            print(json.dumps({"error": f"gwts[{i}]: missing required field 'criterion_id'"}),
                  file=sys.stderr)
            return 1
        for field in ("given", "when", "then"):
            if field not in gwt:
                print(json.dumps({"error": f"gwts[{i}]: missing required field '{field}'"}),
                      file=sys.stderr)
                return 1

    result = _register_payload(target, payload)
    print(json.dumps(result, indent=2))
    return 0


def _resolve_gwt_ids(
    project_dir: Path,
    register_output: dict | None,
    explicit_gwts: list | None,
) -> list[str]:
    """Determine which GWT IDs to process.

    Resolution order:
    1. Explicit --gwt args (if provided)
    2. register_output from setup phase (if available)
    3. DAG nodes (fallback)
    """
    if explicit_gwts:
        return explicit_gwts
    if register_output and register_output.get("gwts"):
        return [g["gwt_id"] for g in register_output["gwts"]]
    dag_path = project_dir / ".cw9" / "dag.json"
    if dag_path.exists():
        dag_data = json.loads(dag_path.read_text())
        return sorted(nid for nid in dag_data.get("nodes", {}) if nid.startswith("gwt-"))
    return []


def _find_context_file(project_dir: Path, gwt_id: str, gwt_to_criterion: dict | None) -> Path | None:
    """Find context file for a GWT in .cw9/context/."""
    context_dir = project_dir / ".cw9" / "context"
    if not context_dir.exists():
        return None
    if gwt_to_criterion:
        crit_id = gwt_to_criterion.get(gwt_id)
        if crit_id:
            ctx_file = context_dir / f"{crit_id}.md"
            if ctx_file.exists():
                return ctx_file
    return None


def cmd_pipeline(args: argparse.Namespace) -> int:
    """Run full CW9 pipeline: setup -> loop -> bridge."""
    target = Path(args.target_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)

    need_setup = not args.skip_setup and not args.bridge_only

    # DB validation
    if need_setup:
        db = args.db or (Path(os.environ["CW7_DB"]) if os.environ.get("CW7_DB") else None)
        if not db:
            print("Error: --db required (or set CW7_DB)", file=sys.stderr)
            return 1
        if not db.exists():
            print(f"Error: CW7 database not found: {db}", file=sys.stderr)
            return 1
    else:
        db = None

    # Session inference from plan_path_dir
    session_id = args.session
    if session_id is None and args.plan_path_dir is not None:
        dirname = args.plan_path_dir.name
        if dirname.startswith("session-"):
            session_id = dirname

    # Phase 0: Setup
    register_output = None
    gwt_to_criterion: dict[str, str] = {}
    if need_setup:
        # init
        rc = main(["init", str(target), "--ensure"])
        if rc != 0:
            return rc

        # extract
        rc = main(["extract", str(target)])
        if rc != 0:
            return rc

        # CW7 extract + register
        from registry.cw7 import extract as cw7_extract, build_plan_path_map, copy_context_files
        payload = cw7_extract(db, session_id)

        # Copy plan_path context files
        if args.plan_path_dir is not None:
            context_dir = target / ".cw9" / "context"
            pp_map = build_plan_path_map(db, session_id) if session_id else None
            copy_context_files(args.plan_path_dir, context_dir, payload["gwts"], pp_map)

        register_output = _register_payload(target, payload)

        # Build gwt_id -> criterion_id mapping
        if register_output and register_output.get("gwts"):
            for g in register_output["gwts"]:
                gwt_to_criterion[g["gwt_id"]] = g["criterion_id"]

    # Resolve targets
    gwt_ids = _resolve_gwt_ids(target, register_output, args.gwts)
    if not gwt_ids:
        print("Error: No GWT IDs found. Provide --gwt or ensure register ran.", file=sys.stderr)
        return 1

    # Phase 1: Loop
    loop_results: dict[str, bool] = {}
    if not args.bridge_only:
        for gwt_id in gwt_ids:
            ctx_file_path = _find_context_file(target, gwt_id, gwt_to_criterion)
            rc = _run_loop_core(
                target=target,
                gwt_id=gwt_id,
                max_retries=args.max_retries,
                context_file=ctx_file_path,
            )
            loop_results[gwt_id] = (rc == 0)

    # Determine which GWTs to bridge
    if args.bridge_only:
        verified_ids = [
            gid for gid in gwt_ids
            if (target / ".cw9" / "specs" / f"{gid}.tla").exists()
        ]
    else:
        verified_ids = [gid for gid, passed in loop_results.items() if passed]

    # Phase 2: Bridge
    bridge_results: dict[str, bool] = {}
    if not args.loop_only and verified_ids:
        for gwt_id in verified_ids:
            spec_path = target / ".cw9" / "specs" / f"{gwt_id}.tla"
            if not spec_path.exists():
                continue
            rc = _run_bridge_core(target=target, gwt_id=gwt_id)
            bridge_results[gwt_id] = (rc == 0)

    # Exit code: 0 if all attempted steps passed
    all_passed = (
        all(loop_results.values()) if loop_results else True
    ) and (
        all(bridge_results.values()) if bridge_results else True
    )
    return 0 if all_passed else 1


def cmd_test(args: argparse.Namespace) -> int:
    import subprocess as sp

    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    ctx = ProjectContext.from_target(target)
    test_dir = ctx.test_output_dir

    if not test_dir.exists() or not list(test_dir.glob("test_*.py")):
        print(f"No generated tests in {test_dir}", file=sys.stderr)
        print("Run: cw9 gen-tests <gwt-id>", file=sys.stderr)
        return 1

    test_files = []

    if args.node_id:
        from registry.dag import RegistryDag
        dag_path = state_root / "dag.json"
        if not dag_path.exists():
            print("No DAG found. Run: cw9 extract", file=sys.stderr)
            return 1
        dag = RegistryDag.load(dag_path)

        # Populate test_artifacts from bridge artifact files
        for artifact_file in ctx.artifact_dir.glob("*_bridge_artifacts.json"):
            data = json.loads(artifact_file.read_text())
            gid = data.get("gwt_id", "")
            test_path = test_dir / f"test_{gid.replace('-', '_')}.py"
            if test_path.exists():
                dag.test_artifacts[gid] = str(test_path)

        affected = dag.query_affected_tests(args.node_id)
        if not affected:
            print(f"No tests affected by {args.node_id}")
            return 0
        test_files = affected
        print(f"Running {len(test_files)} affected test(s) for {args.node_id}")
    else:
        test_files = [str(f) for f in sorted(test_dir.glob("test_*.py"))]
        print(f"Running {len(test_files)} generated test(s)")

    result = sp.run(
        [sys.executable, "-m", "pytest"] + test_files + ["-v"],
        cwd=str(ctx.python_dir),
    )
    return result.returncode


def _detect_language(root: Path) -> str:
    """Auto-detect the primary language of a codebase from manifest files."""
    # Check for JS/TS (package.json is the strongest signal)
    if (root / "package.json").exists():
        # Distinguish TS from JS by looking for tsconfig
        if (root / "tsconfig.json").exists():
            return "typescript"
        return "javascript"
    # Go
    if (root / "go.mod").exists():
        return "go"
    # Rust
    if (root / "Cargo.toml").exists():
        return "rust"
    # Python (pyproject.toml, setup.py, requirements.txt)
    if any((root / f).exists() for f in ("pyproject.toml", "setup.py", "requirements.txt")):
        return "python"
    # Fallback: count file extensions
    ext_counts: dict[str, int] = {}
    for p in root.rglob("*"):
        if p.is_file() and not any(part.startswith(".") for part in p.parts):
            ext_counts[p.suffix] = ext_counts.get(p.suffix, 0) + 1
    ext_to_lang = {
        ".py": "python", ".js": "javascript", ".jsx": "javascript",
        ".ts": "typescript", ".tsx": "typescript",
        ".go": "go", ".rs": "rust",
    }
    best_lang = "python"
    best_count = 0
    for ext, lang in ext_to_lang.items():
        if ext_counts.get(ext, 0) > best_count:
            best_count = ext_counts[ext]
            best_lang = lang
    return best_lang


def _get_scanner(lang: str):
    """Return the scan_directory function for the given language."""
    if lang == "javascript":
        from registry.scanner_javascript import scan_directory
    elif lang == "typescript":
        from registry.scanner_typescript import scan_directory
    elif lang == "go":
        from registry.scanner_go import scan_directory
    elif lang == "rust":
        from registry.scanner_rust import scan_directory
    else:
        from registry.scanner_python import scan_directory
    return scan_directory


def _ingest_scan(ingest_path: Path, lang: str, max_functions: int | None):
    """Scan phase: discover skeletons and entry points, normalize paths."""
    from registry.entry_points import detect_codebase_type, discover_entry_points

    codebase_type = detect_codebase_type(ingest_path, lang=lang)
    scan_directory = _get_scanner(lang)

    skeletons = scan_directory(ingest_path)
    if max_functions and len(skeletons) > max_functions:
        skeletons = skeletons[:max_functions]

    # Normalize file_path to relative (project-root-relative) so UUIDs
    # are stable across worktrees / checkout locations.
    for skel in skeletons:
        if os.path.isabs(skel.file_path):
            skel.file_path = os.path.relpath(skel.file_path, ingest_path)

    entry_points = discover_entry_points(ingest_path, codebase_type, lang=lang, skeletons=skeletons)
    for ep in entry_points:
        if os.path.isabs(ep.file_path):
            ep.file_path = os.path.relpath(ep.file_path, ingest_path)

    return skeletons, entry_points, codebase_type


def _ingest_adopt_donor(store, skel, uid, donor):
    """Adopt phase: migrate extraction data from a donor record to a new UUID.

    Returns (record, disposition) where disposition is 'adopted' or 'updated'.
    """
    from registry.crawl_types import FnRecord

    record = FnRecord(
        uuid=uid,
        function_name=skel.function_name,
        class_name=skel.class_name,
        file_path=skel.file_path,
        line_number=skel.line_number,
        src_hash=skel.file_hash,
        is_external=False,
        ins=donor.ins,
        do_description=donor.do_description,
        do_steps=donor.do_steps,
        do_branches=donor.do_branches,
        do_loops=donor.do_loops,
        do_errors=donor.do_errors,
        outs=donor.outs,
        failure_modes=donor.failure_modes,
        operational_claim=donor.operational_claim,
        skeleton=skel,
    )
    store.adopt_donor_record(donor.uuid)
    existing = store.get_record(uid)
    if existing:
        store.upsert_record(record)
        return "updated"
    else:
        store.insert_record(record)
        return "adopted"


def _ingest_upsert_skeleton(store, skel, uid):
    """Upsert phase: create or update a skeleton-only record.

    Returns 'created' or 'updated'.
    """
    from registry.crawl_types import FnRecord

    record = FnRecord(
        uuid=uid,
        function_name=skel.function_name,
        class_name=skel.class_name,
        file_path=skel.file_path,
        line_number=skel.line_number,
        src_hash=skel.file_hash,
        is_external=False,
        ins=[],
        do_description="SKELETON_ONLY",
        do_steps=[],
        outs=[],
        failure_modes=[],
        operational_claim=f"{skel.function_name} (skeleton only, awaiting LLM extraction)",
        skeleton=skel,
    )
    existing = store.get_record(uid)
    if existing:
        store.upsert_record(record)
        return "updated"
    else:
        store.insert_record(record)
        return "created"


def _ingest_store_records(store, skeletons, entry_points, ingest_path, lang,
                          codebase_type, is_incremental):
    """Store phase: write skeleton records and entry points to crawl.db.

    Returns (created, updated, skipped, failed, adopted) counters.
    """
    from registry.crawl_types import make_record_uuid

    run_id = store.start_crawl_run(
        str(ingest_path), lang, codebase_type, is_incremental,
    )
    created, updated, skipped, failed, adopted = 0, 0, 0, 0, 0

    for skel in skeletons:
        uid = make_record_uuid(skel.file_path, skel.function_name, skel.class_name)

        # Check if already up-to-date (incremental mode)
        if is_incremental:
            existing = store.get_record(uid)
            if existing and existing.src_hash == skel.file_hash:
                skipped += 1
                continue

        # Check for an already-extracted record under a different path
        donor = store.find_extracted_by_identity(
            skel.function_name, skel.class_name, skel.file_hash,
        )
        if donor and donor.uuid != uid:
            disposition = _ingest_adopt_donor(store, skel, uid, donor)
            if disposition == "updated":
                updated += 1
            else:
                adopted += 1
            continue

        # Create a skeleton-only record
        disposition = _ingest_upsert_skeleton(store, skel, uid)
        if disposition == "updated":
            updated += 1
        else:
            created += 1

    for ep in entry_points:
        store.insert_entry_point(ep)

    store.finish_crawl_run(run_id, created, updated, skipped, failed)
    store.backfill_source_uuids()

    return created, updated, skipped, failed, adopted


def _ingest_bridge(crawl_db_path: Path, dag_path: Path) -> dict:
    """Bridge phase: sync crawl.db records into dag.json."""
    from registry.crawl_bridge import bridge_crawl_to_dag
    from registry.dag import RegistryDag

    dag = RegistryDag.load(dag_path) if dag_path.exists() else RegistryDag()
    counters = bridge_crawl_to_dag(crawl_db_path, dag)
    dag.save(dag_path)
    return counters


def cmd_ingest(args: argparse.Namespace) -> int:
    """Ingest an external codebase into the crawl store and DAG."""
    target = Path(args.target_dir).resolve()
    ingest_path = Path(args.ingest_path).resolve()

    if _require_cw9(target) is None:
        return 1
    if not ingest_path.exists():
        print(f"Path not found: {ingest_path}", file=sys.stderr)
        return 1

    from registry.context import ProjectContext
    from registry.crawl_store import CrawlStore

    ctx = ProjectContext.from_target(target)
    state_root = ctx.state_root
    crawl_db_path = state_root / "crawl.db"
    dag_path = state_root / "dag.json"

    lang = getattr(args, "lang", None) or _detect_language(ingest_path)
    is_incremental = getattr(args, "incremental", False)
    max_functions = getattr(args, "max_functions", None)

    # Scan phase
    skeletons, entry_points, codebase_type = _ingest_scan(
        ingest_path, lang, max_functions,
    )
    print(f"Ingesting {ingest_path} ({lang}, detected: {codebase_type})", file=sys.stderr)
    print(f"Phase 0: {len(skeletons)} skeletons extracted", file=sys.stderr)
    print(f"Entry points: {len(entry_points)}", file=sys.stderr)

    # Store phase
    with CrawlStore(crawl_db_path) as store:
        created, updated, skipped, failed, adopted = _ingest_store_records(
            store, skeletons, entry_points, ingest_path, lang,
            codebase_type, is_incremental,
        )

    # Bridge phase
    counters = _ingest_bridge(crawl_db_path, dag_path)

    print(
        f"Phase 1: {created} created, {updated} updated, "
        f"{skipped} skipped, {failed} failed"
        + (f", {adopted} adopted" if adopted else ""),
        file=sys.stderr,
    )
    print(
        f"Bridge: {counters['nodes_added']} RESOURCE nodes, "
        f"{counters['edges_added']} edges, "
        f"{counters['orphans_removed']} orphans removed",
        file=sys.stderr,
    )

    if getattr(args, "output_json", False):
        print(json.dumps({
            "created": created, "updated": updated,
            "skipped": skipped, "failed": failed,
            "bridge": counters,
        }))
    return 0


def _short_path(file_path: str, root: Path) -> str:
    """Make a file path relative to root for display."""
    try:
        return str(Path(file_path).relative_to(root))
    except ValueError:
        return file_path


def _positive_int(value):
    """Argparse type validator: positive integer only."""
    ivalue = int(value)
    if ivalue <= 0:
        raise argparse.ArgumentTypeError(f"must be positive, got {value}")
    return ivalue


def _format_elapsed(seconds: float) -> str:
    """Format seconds into a human-readable duration."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds) // 60
    secs = seconds - minutes * 60
    if minutes < 60:
        return f"{minutes}m{secs:04.1f}s"
    hours = minutes // 60
    minutes = minutes % 60
    return f"{hours}h{minutes:02d}m"


class _ProgressReporter:
    """Tracks crawl progress and emits ANSI-formatted status lines."""

    def __init__(self, target: Path, max_retries: int, err=None):
        import time
        self._target = target
        self._max_retries = max_retries
        self._err = err or sys.stderr
        self._time = time
        self.ok = 0
        self.fail = 0
        self.skip = 0
        self.retries = 0
        self._t_start = time.monotonic()
        self._t_last = time.monotonic()

    def __call__(self, event: str, **kw):
        now = self._time.monotonic()
        elapsed = now - self._t_start
        fn_name = kw.get("function_name", "?")
        fpath = _short_path(kw.get("file_path", ""), self._target)
        err = self._err

        if event == "extracted":
            self.ok += 1
            dt = now - self._t_last
            self._t_last = now
            n = self.ok + self.fail + self.skip
            attempt = kw.get("attempt", 1)
            retry_tag = f" \033[33m(attempt {attempt})\033[0m" if attempt > 1 else ""
            print(
                f"  \033[32m+\033[0m [{n}] {fn_name}{retry_tag}  "
                f"{kw.get('ins', 0)} in / {kw.get('outs', 0)} out  "
                f"\033[2m{fpath}  {dt:.1f}s  [{_format_elapsed(elapsed)}]\033[0m",
                file=err,
            )

        elif event == "retry":
            self.retries += 1
            attempt = kw.get("attempt", 1)
            max_r = kw.get("max_retries", self._max_retries)
            error_msg = kw.get("error", "")[:60]
            print(
                f"  \033[33m~\033[0m {fn_name} retry {attempt}/{max_r}: "
                f"\033[2m{error_msg}\033[0m",
                file=err,
            )

        elif event == "failed":
            self.fail += 1
            n = self.ok + self.fail + self.skip
            error_msg = kw.get("error", "")[:80]
            print(
                f"  \033[31mx\033[0m [{n}] FAILED {fn_name}  "
                f"\033[2m{fpath}\033[0m\n"
                f"    \033[31m{error_msg}\033[0m",
                file=err,
            )

        elif event == "skipped":
            self.skip += 1
            n = self.ok + self.fail + self.skip
            if self.skip <= 3 or self.skip % 50 == 0:
                print(
                    f"  \033[2m- [{n}] skipped {fn_name}  {fpath}\033[0m",
                    file=err,
                )


def _resolve_entry_points(store, entry_names: list[str]) -> list[str]:
    """Resolve crawl entry points via three fallback tiers.

    1. Explicit --entry flag values (passed in as entry_names)
    2. Stored entry_points table in the CrawlStore
    3. All records with SKELETON_ONLY description
    """
    if entry_names:
        return entry_names

    stored_eps = store.get_entry_points() if hasattr(store, "get_entry_points") else []
    if stored_eps:
        return [ep.function_name for ep in stored_eps]

    all_recs = store.get_all_records()
    return [
        r.function_name for r in all_recs
        if r.do_description == SKELETON_SENTINEL
    ]


def _print_crawl_header(target: Path, total: int, model_name: str,
                         max_retries: int, max_fns: int | None,
                         incremental: bool, err) -> None:
    """Print the crawl header banner."""
    print(f"\n{'='*60}", file=err)
    print(f"  DFS Crawl: {target.name}", file=err)
    print(f"  {total} entry points | model: {model_name} | retries: {max_retries}", file=err)
    if max_fns:
        print(f"  limit: {max_fns} functions", file=err)
    if incremental:
        print(f"  mode: incremental (skip unchanged)", file=err)
    print(f"{'='*60}\n", file=err)


def _print_crawl_summary(result: dict, retries: int, elapsed: float, err) -> None:
    """Print the post-crawl summary banner."""
    ok = result["extracted"]
    fail = result["failed"]
    skip = result["skipped"]
    ax = result["ax_records"]

    print(f"\n{'─'*60}", file=err)
    parts = []
    if ok:
        parts.append(f"\033[32m{ok} extracted\033[0m")
    if fail:
        parts.append(f"\033[31m{fail} failed\033[0m")
    if skip:
        parts.append(f"\033[2m{skip} skipped\033[0m")
    if ax:
        parts.append(f"{ax} AX boundaries")
    if retries:
        parts.append(f"\033[33m{retries} retries\033[0m")
    print(f"  {' | '.join(parts)}", file=err)
    if ok:
        avg = elapsed / ok
        print(f"  {_format_elapsed(elapsed)} elapsed ({avg:.1f}s avg per function)", file=err)
    print(f"{'─'*60}\n", file=err)


def cmd_crawl(args: argparse.Namespace) -> int:
    """Run DFS crawl with LLM extraction over ingested skeleton records."""
    import asyncio
    import shutil
    import time

    from registry.context import ProjectContext
    from registry.crawl_orchestrator import CrawlOrchestrator
    from registry.crawl_store import CrawlStore

    target = Path(args.target_dir).resolve()
    ctx = ProjectContext.from_target(target)
    state_root = ctx.state_root
    err = sys.stderr

    crawl_db_path = state_root / "crawl.db"
    if not crawl_db_path.exists():
        print(f"No crawl.db found. Run: cw9 ingest <path> first", file=err)
        return 1

    # Auto-backup before crawl — cheap insurance against corruption
    bak_path = crawl_db_path.with_suffix(".db.pre-crawl")
    shutil.copy2(crawl_db_path, bak_path)
    print(f"  Backup: {bak_path.name}", file=err)

    # Resolve parameters
    max_fns = getattr(args, "max_functions", None)
    max_retries = getattr(args, "max_retries", None) or DEFAULT_MAX_RETRIES
    model_name = getattr(args, "model", None) or DEFAULT_MODEL
    incremental = getattr(args, "incremental", False)
    concurrency = getattr(args, "concurrency", DEFAULT_CONCURRENCY)

    with CrawlStore(crawl_db_path) as store:
        entry_names = _resolve_entry_points(
            store, getattr(args, "entry", None) or []
        )
        if not entry_names:
            print("No entry points found. Specify with --entry or run cw9 ingest first.", file=err)
            return 1

        _print_crawl_header(target, len(entry_names), model_name,
                            max_retries, max_fns, incremental, err)

        progress = _ProgressReporter(target, max_retries, err)
        extract_fn = _build_async_extract_fn(model=model_name)

        t0 = time.monotonic()
        orch = CrawlOrchestrator(
            store=store,
            entry_points=entry_names,
            extract_fn=extract_fn,
            max_functions=max_fns,
            incremental=incremental,
            max_retries=max_retries,
            on_progress=progress,
            concurrency=concurrency,
            project_root=target,
        )
        result = asyncio.run(orch.run())
        elapsed = time.monotonic() - t0

    _print_crawl_summary(result, progress.retries, elapsed, err)

    if getattr(args, "output_json", False):
        print(json.dumps(result))
    return 0


def _build_llm_fn(
    model: str = DEFAULT_MODEL,
    system_prompt: str | None = None,
    output_schema: dict | None = None,
):
    """Build a synchronous LLM call function using the Claude Agent SDK.

    Returns a callable: (prompt: str) -> str | dict
    When output_schema is provided, returns the parsed dict from structured_output.
    """
    import asyncio
    import os

    os.environ.pop("CLAUDECODE", None)
    import claude_agent_sdk
    from claude_agent_sdk import (
        ClaudeSDKClient, ClaudeAgentOptions,
        AssistantMessage, ResultMessage, TextBlock,
    )

    def llm_fn(prompt: str) -> str | dict:
        async def _call():
            options = ClaudeAgentOptions(
                allowed_tools=[],
                system_prompt=system_prompt or "You are a helpful assistant.",
                max_turns=4 if output_schema else 1,
                model=model,
            )
            if output_schema is not None:
                options.output_format = {"type": "json_schema", "schema": output_schema}
            client = ClaudeSDKClient(options)
            await client.connect()
            try:
                await client.query(prompt)
                result_text = []
                async for message in client.receive_response():
                    if isinstance(message, AssistantMessage):
                        for block in message.content:
                            if isinstance(block, TextBlock):
                                result_text.append(block.text)
                    elif isinstance(message, ResultMessage):
                        if output_schema is not None and message.structured_output:
                            return message.structured_output
                        if message.result:
                            result_text.append(message.result)
                return "".join(result_text)
            finally:
                try:
                    await asyncio.wait_for(client.disconnect(), timeout=10.0)
                except Exception:
                    pass

        return asyncio.run(_call())

    return llm_fn


_EXTRACT_SYSTEM_PROMPT = """\
You are a code analysis expert. Given a function's skeleton (signature) and body, \
extract its behavioral IN:DO:OUT card.

For "source" field on inputs:
- "parameter": comes from function arguments
- "state": reads from instance/global state
- "literal": hardcoded constant
- "internal_call": return value of another function in this codebase (set source_function and source_file)
- "external": return value from an external library/service (set source_function to the call expression)\
"""

# JSON Schema for structured output — enforced by the Agent SDK
_EXTRACT_OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "ins": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type_str": {"type": "string"},
                    "source": {
                        "type": "string",
                        "enum": ["parameter", "state", "literal", "internal_call", "external"],
                    },
                    "source_function": {"type": ["string", "null"]},
                    "source_file": {"type": ["string", "null"]},
                    "description": {"type": "string"},
                },
                "required": ["name", "type_str", "source", "description"],
            },
        },
        "do_description": {"type": "string"},
        "do_steps": {"type": "array", "items": {"type": "string"}},
        "outs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "enum": ["ok", "err", "side_effect", "mutation"],
                    },
                    "type_str": {"type": "string"},
                    "description": {"type": "string"},
                },
                "required": ["name", "type_str", "description"],
            },
        },
        "failure_modes": {"type": "array", "items": {"type": "string"}},
        "operational_claim": {"type": "string"},
    },
    "required": ["ins", "do_description", "do_steps", "outs", "failure_modes", "operational_claim"],
}


def _extract_json_object(text: str) -> dict:
    """Extract the first valid JSON object from text that may contain surrounding prose."""
    start = text.find("{")
    if start == -1:
        raise ValueError(f"No JSON object found in response: {text[:200]}")

    # Use a brace-depth counter to find matching close braces.
    # Re-anchor `start` each time depth transitions 0→1 so that after a
    # failed balanced block we try the NEXT top-level object, not the slice
    # from the original `{`.
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(text)):
        ch = text[i]
        if escape:
            escape = False
            continue
        if ch == "\\":
            if in_string:
                escape = True
            continue
        if ch == '"' and not escape:
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            if depth == 0:
                start = i  # anchor to this top-level brace
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i + 1])
                except json.JSONDecodeError:
                    # This balanced block wasn't valid JSON; keep scanning
                    # depth is already 0, so the next '{' will re-anchor start
                    continue

    raise ValueError(f"Could not parse JSON from response: {text[:200]}")


def _build_extraction_prompt(skeleton, body: str, error_feedback: str | None = None) -> str:
    """Build the LLM prompt for IN:DO:OUT extraction from a function skeleton."""
    parts = [
        f"## Function: {skeleton.function_name}",
        f"File: {skeleton.file_path}:{skeleton.line_number}",
    ]
    if skeleton.class_name:
        parts.append(f"Class: {skeleton.class_name}")
    if skeleton.params:
        param_strs = [f"{p.name}: {p.type or 'Any'}" for p in skeleton.params]
        parts.append(f"Params: {', '.join(param_strs)}")
    if skeleton.return_type:
        parts.append(f"Returns: {skeleton.return_type}")
    parts.append(f"\n## Body\n```\n{body}\n```")
    if error_feedback:
        parts.append(f"\n## Previous Error\n{error_feedback}\nPlease fix the JSON output.")
    return "\n".join(parts)


def _data_to_fn_record(data: dict, skeleton) -> "FnRecord":
    """Convert parsed JSON extraction data to a FnRecord."""
    from registry.crawl_types import (
        FnRecord, InField, InSource, OutField, OutKind,
    )

    source_map = {
        "parameter": InSource.PARAMETER,
        "state": InSource.STATE,
        "literal": InSource.LITERAL,
        "internal_call": InSource.INTERNAL_CALL,
        "external": InSource.EXTERNAL,
    }
    kind_map = {
        "ok": OutKind.OK,
        "err": OutKind.ERR,
        "side_effect": OutKind.SIDE_EFFECT,
        "mutation": OutKind.MUTATION,
    }

    ins = [
        InField(
            name=i["name"],
            type_str=i.get("type_str", "Any"),
            source=source_map.get(i.get("source", "parameter"), InSource.PARAMETER),
            source_function=i.get("source_function"),
            source_file=i.get("source_file"),
            description=i.get("description", ""),
        )
        for i in data.get("ins", [])
    ]
    outs = [
        OutField(
            name=kind_map.get(o.get("name", "ok"), OutKind.OK),
            type_str=o.get("type_str", "Any"),
            description=o.get("description", ""),
        )
        for o in data.get("outs", [])
    ]

    return FnRecord(
        uuid=PLACEHOLDER_UUID,
        function_name=skeleton.function_name,
        class_name=skeleton.class_name,
        file_path=skeleton.file_path,
        line_number=skeleton.line_number,
        src_hash=skeleton.file_hash,
        ins=ins,
        do_description=data.get("do_description", ""),
        do_steps=data.get("do_steps", []),
        outs=outs,
        failure_modes=data.get("failure_modes", []),
        operational_claim=data.get("operational_claim", ""),
        skeleton=skeleton,
    )


def _build_async_extract_fn(model: str = DEFAULT_MODEL):
    """Build an async extract_fn using standalone query() — fresh context per call.

    Each invocation of the returned coroutine creates a completely independent
    session via the SDK's standalone query() function. No persistent client is
    constructed — context isolation is guaranteed by design.
    """
    import os
    import sys
    os.environ.pop("CLAUDECODE", None)
    from claude_agent_sdk import query as _query, ClaudeAgentOptions, AssistantMessage, ResultMessage, TextBlock
    from registry.crawl_types import FnRecord, Skeleton
    # Store query at module level so it can be patched in tests
    sys.modules[__name__].query = _query

    async def extract_fn(skeleton: Skeleton, body: str, error_feedback: str | None = None) -> FnRecord:
        prompt = _build_extraction_prompt(skeleton, body, error_feedback)

        options = ClaudeAgentOptions(
            allowed_tools=[],
            system_prompt=_EXTRACT_SYSTEM_PROMPT,
            max_turns=4,  # model may waste turns on prose; SDK needs extra for structured output
            model=model,
            output_format={"type": "json_schema", "schema": _EXTRACT_OUTPUT_SCHEMA},
        )

        data = None
        result_subtype = None
        result_text = []
        # Use module-level query (supports test patching)
        _cli_mod = sys.modules[__name__]
        async for message in _cli_mod.query(prompt=prompt, options=options):
            if isinstance(message, ResultMessage):
                result_subtype = getattr(message, "subtype", None)
                if message.structured_output:
                    data = message.structured_output
                elif message.result:
                    result_text.append(message.result)
            elif isinstance(message, AssistantMessage):
                for block in message.content:
                    if isinstance(block, TextBlock):
                        result_text.append(block.text)

        if data is not None:
            pass  # structured output succeeded
        else:
            import sys as _sys
            print(
                f"  [debug] {skeleton.function_name}: structured_output=None "
                f"subtype={result_subtype} text_len={sum(len(t) for t in result_text)} "
                f"preview={(''.join(result_text))[:80]!r}",
                file=_sys.stderr,
            )
        if data is not None:
            pass
        elif result_subtype in ("error_max_turns", "error_max_structured_output_retries"):
            raw_preview = "".join(result_text)[:200]
            raise ValueError(
                f"Structured output failed ({result_subtype}): {raw_preview}"
            )
        else:
            # No structured_output but no error either (success without it,
            # or no ResultMessage at all e.g. in tests) — fall back to text parsing
            raw = "".join(result_text)
            data = _extract_json_object(raw)

        return _data_to_fn_record(data, skeleton)

    return extract_fn


def cmd_cleanup(args: argparse.Namespace) -> int:
    """Remove stale cw9 temp directories from /tmp."""
    import time

    max_age_hours = getattr(args, "max_age", 24)
    dry_run = getattr(args, "dry_run", False)
    tmp = Path("/tmp")
    prefixes = ("cw9_",)
    cutoff = time.time() - (max_age_hours * 3600)

    removed = 0
    freed_bytes = 0
    errors = 0

    for entry in sorted(tmp.iterdir()):
        if not entry.is_dir():
            continue
        if not any(entry.name.startswith(p) for p in prefixes):
            continue
        try:
            mtime = entry.stat().st_mtime
        except OSError:
            continue
        if mtime > cutoff:
            continue

        # Calculate size before removal
        dir_size = 0
        try:
            for f in entry.rglob("*"):
                try:
                    dir_size += f.stat().st_size
                except OSError:
                    pass
        except OSError:
            pass

        if dry_run:
            age_h = (time.time() - mtime) / 3600
            print(f"  [dry-run] {entry.name}  {_fmt_size(dir_size)}  {age_h:.0f}h old")
            removed += 1
            freed_bytes += dir_size
            continue

        try:
            shutil.rmtree(entry)
            removed += 1
            freed_bytes += dir_size
        except OSError as e:
            print(f"  ! Failed to remove {entry.name}: {e}", file=sys.stderr)
            errors += 1

    # Also prune git worktrees if any were in /tmp
    if not dry_run:
        import subprocess
        try:
            subprocess.run(
                ["git", "worktree", "prune"],
                cwd=str(Path.cwd()),
                capture_output=True,
                timeout=10,
            )
        except Exception:
            pass

    action = "Would remove" if dry_run else "Removed"
    print(f"\n{action} {removed} director{'y' if removed == 1 else 'ies'}, freeing {_fmt_size(freed_bytes)}")
    if errors:
        print(f"  ({errors} failed)")
    return 0


def _fmt_size(nbytes: int) -> str:
    """Format byte count as human-readable size."""
    for unit in ("B", "KB", "MB", "GB"):
        if nbytes < 1024:
            return f"{nbytes:.1f}{unit}"
        nbytes /= 1024
    return f"{nbytes:.1f}TB"


def cmd_stale(args: argparse.Namespace) -> int:
    """Check which ingested nodes are stale (file hashes changed)."""
    import hashlib

    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    crawl_db_path = state_root / "crawl.db"
    if not crawl_db_path.exists():
        print("No crawl.db found. Run: cw9 ingest", file=sys.stderr)
        return 1

    from registry.crawl_store import CrawlStore

    with CrawlStore(crawl_db_path) as store:
        # Compute current file hashes
        records = store.get_all_records()
        file_paths = {r.file_path for r in records}
        current_hashes: dict[str, str] = {}
        for fp in file_paths:
            p = Path(fp)
            if p.exists():
                current_hashes[fp] = hashlib.sha256(p.read_bytes()).hexdigest()

        direct_stale = store.get_stale_records(current_hashes)
        all_stale = store.get_transitive_stale(direct_stale) if direct_stale else []

    if not all_stale:
        print("No stale records.")
        return 0

    print(f"{len(all_stale)} stale record(s) ({len(direct_stale)} directly changed):")
    for uid in all_stale:
        rec = next((r for r in records if r.uuid == uid), None)
        if rec:
            marker = " [direct]" if uid in direct_stale else " [transitive]"
            print(f"  {rec.function_name} @ {rec.file_path}{marker}")
    return 0


def cmd_seams(args: argparse.Namespace) -> int:
    """Check seam compatibility across function boundaries in crawl.db."""
    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1

    crawl_db_path = state_root / "crawl.db"
    if not crawl_db_path.exists():
        print("No crawl.db found. Run: cw9 ingest", file=sys.stderr)
        return 1

    from registry.crawl_store import CrawlStore
    from registry.seam_checker import check_all_seams, render_seam_report, seam_report_to_json

    # Load cross-cutting rules if requested
    behavioral_report = None
    if getattr(args, "cross_cutting", False):
        from registry.seam_checker import (
            check_behavioral_contracts,
            load_cross_cutting_rules,
        )
        rules_path = state_root / "schema" / "cross_cutting_rules.json"
        if not rules_path.exists():
            print(f"Cross-cutting rules file not found: {rules_path}", file=sys.stderr)
            return 1
        try:
            rules = load_cross_cutting_rules(rules_path)
        except (ValueError, FileNotFoundError) as exc:
            print(f"Error loading cross-cutting rules: {exc}", file=sys.stderr)
            return 1

    with CrawlStore(crawl_db_path) as store:
        report = check_all_seams(store)
        if getattr(args, "cross_cutting", False):
            behavioral_report = check_behavioral_contracts(store, rules)

    if getattr(args, "output_json", False):
        import json
        data = seam_report_to_json(report)
        if behavioral_report is not None:
            from registry.seam_checker import behavioral_report_to_json
            data["behavioral"] = behavioral_report_to_json(behavioral_report)
        print(json.dumps(data, indent=2))
    else:
        print(render_seam_report(report, verbose=getattr(args, "verbose", False)))
        if behavioral_report is not None:
            from registry.seam_checker import render_behavioral_report
            print(render_behavioral_report(behavioral_report))

    return 1 if report.mismatches else 0


def cmd_show(args: argparse.Namespace) -> int:
    """Show information about a node. With --card, show IN:DO:OUT card."""
    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1
    node_id = args.node_id

    if getattr(args, "card", False):
        crawl_db_path = state_root / "crawl.db"
        if not crawl_db_path.exists():
            print("No crawl.db found. Run: cw9 ingest", file=sys.stderr)
            return 1
        from registry.crawl_store import CrawlStore
        with CrawlStore(crawl_db_path) as store:
            text = store.get_card_text(node_id)
            print(text)
        return 0

    # Default: show DAG node info
    dag_path = state_root / "dag.json"
    if not dag_path.exists():
        print("No dag.json found. Run: cw9 extract or cw9 ingest", file=sys.stderr)
        return 1

    from registry.dag import RegistryDag
    dag = RegistryDag.load(dag_path)
    if node_id not in dag.nodes:
        print(f"Node not found: {node_id}", file=sys.stderr)
        return 1

    node = dag.nodes[node_id]
    print(f"ID: {node.id}")
    print(f"Kind: {node.kind.value}")
    print(f"Name: {node.name}")
    if node.description:
        print(f"Description: {node.description}")
    if node.given:
        print(f"Given: {node.given}")
    if node.when:
        print(f"When: {node.when}")
    if node.then:
        print(f"Then: {node.then}")

    # Show edges
    edges = [e for e in dag.edges if e.from_id == node_id or e.to_id == node_id]
    if edges:
        print(f"\nEdges ({len(edges)}):")
        for e in edges:
            print(f"  {e.from_id} --{e.edge_type.value}--> {e.to_id}")

    return 0


def cmd_gwt_author(args: argparse.Namespace) -> int:
    """Generate GWT specifications from research notes and crawl.db cards."""
    target = Path(args.target_dir).resolve()
    state_root = _require_cw9(target)
    if state_root is None:
        return 1
    research_path = Path(args.research).resolve()

    if not research_path.exists():
        print(f"Research file not found: {research_path}", file=sys.stderr)
        return 1

    from registry.gwt_author import run_gwt_author

    # Build Agent SDK LLM function
    llm_fn = _build_llm_fn()

    try:
        payload = run_gwt_author(target, research_path, llm_fn=llm_fn)
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        return 1

    import json
    print(json.dumps(payload, indent=2))
    return 0


def _add_core_commands(sub: argparse._SubParsersAction) -> None:
    """Add core project subcommands: init, status, extract, register."""
    p_init = sub.add_parser("init", help="Initialize .cw9/ in a target directory")
    p_init.add_argument("target_dir", nargs="?", default=".", help="Target project directory (default: .)")
    p_init.add_argument("--force", action="store_true", help="Reinitialize existing .cw9/")
    p_init.add_argument("--ensure", action="store_true",
                         help="No-op if .cw9/ already exists (idempotent init)")

    p_status = sub.add_parser("status", help="Show pipeline progress and per-GWT status")
    p_status.add_argument("target_dir", nargs="?", default=".", help="Target project directory (default: .)")
    p_status.add_argument("--json", action="store_true", dest="output_json", help="Output machine-readable JSON")

    p_extract = sub.add_parser("extract", help="Extract DAG from schemas")
    p_extract.add_argument("target_dir", nargs="?", default=".")

    p_reg = sub.add_parser("register", help="Register requirements + GWTs from JSON stdin")
    p_reg.add_argument("target_dir", nargs="?", default=".")


def _add_pipeline_commands(sub: argparse._SubParsersAction) -> None:
    """Add verification pipeline subcommands: loop, bridge, gen-tests, test, pipeline."""
    p_loop = sub.add_parser("loop", help="Run LLM → PlusCal → TLC for a GWT behavior")
    p_loop.add_argument("gwt_id", help="GWT behavior ID (e.g., gwt-0024)")
    p_loop.add_argument("target_dir", nargs="?", default=".")
    p_loop.add_argument("--max-retries", type=int, default=8)
    p_loop.add_argument("--context-file", type=Path, default=None,
                        help="Supplementary context file passed verbatim to LLM")

    p_bridge = sub.add_parser("bridge", help="Translate verified spec → bridge artifacts")
    p_bridge.add_argument("gwt_id", help="GWT behavior ID")
    p_bridge.add_argument("target_dir", nargs="?", default=".")

    p_gen = sub.add_parser("gen-tests", help="Generate test file from bridge artifacts (LLM loop)")
    p_gen.add_argument("gwt_id", help="GWT behavior ID")
    p_gen.add_argument("target_dir", nargs="?", default=".")
    p_gen.add_argument("--max-attempts", type=int, default=3, help="Max generation attempts")
    p_gen.add_argument(
        "--lang", default="python",
        choices=["python", "typescript", "rust", "go"],
        help="Target language for test generation (default: python)",
    )

    p_test = sub.add_parser("test", help="Run generated tests (smart targeting optional)")
    p_test.add_argument("--node", dest="node_id", help="Only run tests affected by this node")
    p_test.add_argument("target_dir", nargs="?", default=".")

    p_pipeline = sub.add_parser("pipeline", help="Run full CW9 pipeline: setup -> loop -> bridge")
    p_pipeline.add_argument("target_dir", nargs="?", default=".")
    p_pipeline.add_argument("--db", type=Path, default=None,
                             help="CW7 SQLite database path (or set CW7_DB env var)")
    p_pipeline.add_argument("--session", default=None)
    p_pipeline.add_argument("--gwt", action="append", dest="gwts", default=None)
    p_pipeline.add_argument("--max-retries", type=int, default=8)
    p_pipeline.add_argument("--skip-setup", action="store_true")
    p_pipeline.add_argument("--loop-only", action="store_true")
    p_pipeline.add_argument("--bridge-only", action="store_true")
    p_pipeline.add_argument("--plan-path-dir", type=Path, default=None)


def _add_crawl_commands(sub: argparse._SubParsersAction) -> None:
    """Add crawl-related subcommands: ingest, crawl, stale, show, gwt-author."""
    p_ingest = sub.add_parser("ingest", help="Ingest an external codebase into the registry")
    p_ingest.add_argument("ingest_path", help="Path to the codebase to ingest")
    p_ingest.add_argument("target_dir", nargs="?", default=".")
    p_ingest.add_argument("--lang", default=None,
                          choices=["python", "javascript", "typescript", "go", "rust"],
                          help="Source language (default: auto-detect)")
    p_ingest.add_argument("--incremental", action="store_true",
                          help="Only re-ingest stale records")
    p_ingest.add_argument("--max-functions", type=int, default=None,
                          help="Limit DFS to N functions")
    p_ingest.add_argument("--json", action="store_true", dest="output_json",
                          help="Output machine-readable JSON")

    p_crawl = sub.add_parser("crawl", help="Run DFS LLM extraction over ingested skeletons")
    p_crawl.add_argument("target_dir", nargs="?", default=".")
    p_crawl.add_argument("--entry", action="append", default=None,
                         help="Entry point function name(s) to start from (repeatable)")
    p_crawl.add_argument("--incremental", action="store_true",
                         help="Skip already-extracted records whose files haven't changed")
    p_crawl.add_argument("--max-functions", type=int, default=None,
                         help="Limit extraction to N functions")
    p_crawl.add_argument("--max-retries", type=int, default=DEFAULT_MAX_RETRIES,
                         help=f"Max LLM retries per function (default: {DEFAULT_MAX_RETRIES})")
    p_crawl.add_argument("--model", default=None,
                         help=f"Claude model to use (default: {DEFAULT_MODEL})")
    p_crawl.add_argument("--json", action="store_true", dest="output_json",
                         help="Output machine-readable JSON")
    p_crawl.add_argument("--concurrency", type=_positive_int, default=DEFAULT_CONCURRENCY,
                         help=f"Max concurrent LLM extractions in sweep phase (default: {DEFAULT_CONCURRENCY})")

    p_stale = sub.add_parser("stale", help="Check which ingested nodes are stale")
    p_stale.add_argument("target_dir", nargs="?", default=".")

    p_show = sub.add_parser("show", help="Show information about a node")
    p_show.add_argument("node_id", help="Node ID to show")
    p_show.add_argument("target_dir", nargs="?", default=".")
    p_show.add_argument("--card", action="store_true", help="Show IN:DO:OUT card from crawl.db")

    p_seams = sub.add_parser("seams", help="Check seam compatibility across function boundaries")
    p_seams.add_argument("target_dir", nargs="?", default=".")
    p_seams.add_argument("--json", action="store_true", dest="output_json")
    p_seams.add_argument("--verbose", action="store_true")
    p_seams.add_argument("--file", default=None, help="Filter to functions in this file")
    p_seams.add_argument("--function", default=None, help="Filter to this function name")
    p_seams.add_argument("--cross-cutting", action="store_true", dest="cross_cutting",
                         help="Include behavioral contract checks from cross-cutting rules")

    p_gwt_author = sub.add_parser("gwt-author", help="Generate GWT specs from research notes + crawl.db")
    p_gwt_author.add_argument("target_dir", nargs="?", default=".", help="Target project directory (default: .)")
    p_gwt_author.add_argument("--research", required=True, help="Path to research notes file")


def cmd_loop_status(args: argparse.Namespace) -> int:
    """Show live progress of running cw9 loop processes."""
    import time as _time

    target = Path(args.target_dir).resolve()
    ctx = ProjectContext.from_target(target)
    session_dir = ctx.session_dir

    if not session_dir.exists():
        print("No sessions directory found.", file=sys.stderr)
        return 1

    progress_files = sorted(session_dir.glob("*_progress.json"))
    if not progress_files:
        print("No running loops detected (no progress files).")
        return 0

    now = _time.time()
    output = {"loops": []}

    for pf in progress_files:
        try:
            data = json.loads(pf.read_text())
        except (json.JSONDecodeError, OSError):
            continue

        gwt_id = data.get("gwt_id", pf.stem.replace("_progress", ""))
        phase = data.get("phase", "unknown")
        attempt = data.get("attempt", 0)
        max_attempts = data.get("max_attempts", 0)
        detail = data.get("detail", "")
        pid = data.get("pid", 0)
        updated_at = data.get("updated_at", 0)
        elapsed = int(now - updated_at) if updated_at else 0

        # Check if the process is still alive
        alive = False
        if pid:
            try:
                os.kill(pid, 0)
                alive = True
            except (OSError, ProcessLookupError):
                pass

        # Check for result file (loop finished)
        result_path = session_dir / f"{gwt_id}_result.json"
        finished = result_path.exists()

        entry = {
            "gwt_id": gwt_id,
            "attempt": f"{attempt}/{max_attempts}",
            "phase": phase,
            "detail": detail,
            "elapsed_seconds": elapsed,
            "pid": pid,
            "alive": alive,
            "finished": finished,
        }
        output["loops"].append(entry)

    if getattr(args, "json_output", False):
        print(json.dumps(output, indent=2))
    else:
        for entry in output["loops"]:
            status_icon = "." if entry["finished"] else (">" if entry["alive"] else "?")
            elapsed_str = f"{entry['elapsed_seconds']}s ago"
            print(
                f"  {status_icon} {entry['gwt_id']}  "
                f"attempt {entry['attempt']}  "
                f"phase={entry['phase']}  "
                f"{elapsed_str}"
                f"{'  ' + entry['detail'] if entry['detail'] else ''}"
            )
        # Legend
        running = sum(1 for e in output["loops"] if e["alive"] and not e["finished"])
        done = sum(1 for e in output["loops"] if e["finished"])
        stale = sum(1 for e in output["loops"] if not e["alive"] and not e["finished"])
        parts = []
        if running:
            parts.append(f"{running} running")
        if done:
            parts.append(f"{done} done")
        if stale:
            parts.append(f"{stale} stale (process dead, no result)")
        if parts:
            print(f"\n  {', '.join(parts)}")

    return 0


def _add_utility_commands(sub: argparse._SubParsersAction) -> None:
    """Add utility subcommands: cleanup, loop-status."""
    p_cleanup = sub.add_parser("cleanup", help="Remove stale cw9 temp directories from /tmp")
    p_cleanup.add_argument("--max-age", type=int, default=24,
                           help="Remove dirs older than N hours (default: 24, use 0 for all)")
    p_cleanup.add_argument("--dry-run", action="store_true",
                           help="Show what would be removed without deleting")

    p_loop_status = sub.add_parser("loop-status", help="Show live progress of running loops")
    p_loop_status.add_argument("target_dir", nargs="?", default=".")
    p_loop_status.add_argument("--json", dest="json_output", action="store_true",
                               help="Output as JSON")


# Dispatch table mapping subcommand names to handler functions.
_DISPATCH: dict[str, Callable[[argparse.Namespace], int]] = {
    "init": cmd_init,
    "status": cmd_status,
    "extract": cmd_extract,
    "loop": cmd_loop,
    "bridge": cmd_bridge,
    "gen-tests": cmd_gen_tests,
    "register": cmd_register,
    "test": cmd_test,
    "pipeline": cmd_pipeline,
    "ingest": cmd_ingest,
    "crawl": cmd_crawl,
    "stale": cmd_stale,
    "seams": cmd_seams,
    "show": cmd_show,
    "gwt-author": cmd_gwt_author,
    "cleanup": cmd_cleanup,
    "loop-status": cmd_loop_status,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="cw9",
        description="CodeWriter9 — formally verified code generation",
    )
    sub = parser.add_subparsers(dest="command")

    _add_core_commands(sub)
    _add_pipeline_commands(sub)
    _add_crawl_commands(sub)
    _add_utility_commands(sub)

    args = parser.parse_args(argv)

    handler = _DISPATCH.get(args.command)
    if handler is not None:
        return handler(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
