"""cw9 CLI — entry point for using CodeWriter9 on external projects.

Usage:
    cw9 init [target_dir]     Initialize .cw9/ in the target directory
    cw9 status [target_dir]   Show project context and DAG summary
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

from registry.context import ProjectContext
from registry._resources import is_installed_mode, get_template_dir


def _get_engine_root() -> Path | None:
    """Get ENGINE_ROOT if running from repo checkout, else None."""
    if is_installed_mode():
        return None
    return Path(__file__).resolve().parent.parent.parent


# For backwards compatibility with test imports
ENGINE_ROOT = _get_engine_root()

_CONFIG_TEMPLATE_DEV = """\
# CodeWriter9 project configuration
# Generated by: cw9 init

[engine]
root = "{engine_root}"

[project]
# Add project-specific settings here
"""

_CONFIG_TEMPLATE_INSTALLED = """\
# CodeWriter9 project configuration
# Generated by: cw9 init (installed mode)

[project]
# Add project-specific settings here
"""

_EMPTY_DAG = {
    "nodes": {},
    "edges": [],
    "test_artifacts": {},
}


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()

    if not target.is_dir():
        print(f"Error: {target} is not a directory", file=sys.stderr)
        return 1

    if args.ensure and args.force:
        print("Error: --ensure and --force are mutually exclusive", file=sys.stderr)
        return 1

    state_root = target / ".cw9"

    if args.ensure and state_root.exists():
        return 0

    if state_root.exists() and not args.force:
        print(f".cw9/ already exists in {target}")
        print("Use --force to reinitialize.")
        return 1

    # Create directory structure
    dirs = [
        state_root / "schema",
        state_root / "specs",
        state_root / "bridge",
        state_root / "sessions",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # Write config
    config_path = state_root / "config.toml"
    engine_root = _get_engine_root()
    if engine_root:
        config_path.write_text(
            _CONFIG_TEMPLATE_DEV.format(engine_root=str(engine_root))
        )
    else:
        config_path.write_text(_CONFIG_TEMPLATE_INSTALLED)

    # Write empty DAG
    dag_path = state_root / "dag.json"
    dag_path.write_text(json.dumps(_EMPTY_DAG, indent=2) + "\n")

    # Verify it loads
    ctx = ProjectContext.from_target(target, engine_root)

    # Copy starter schema templates if schema dir is empty
    if ctx.is_self_hosting:
        schema_templates_dir = get_template_dir("schema")
    else:
        schema_templates_dir = get_template_dir("schema_external")
    if schema_templates_dir.is_dir() and not list((state_root / "schema").glob("*.json")):
        for tmpl in schema_templates_dir.glob("*.json"):
            shutil.copy2(tmpl, state_root / "schema" / tmpl.name)

    print(f"Initialized .cw9/ in {target}")
    print()
    print(f"  engine_root:    {ctx.engine_root or '(installed mode)'}")
    print(f"  target_root:    {ctx.target_root}")
    print(f"  state_root:     {ctx.state_root}")
    print(f"  schema_dir:     {ctx.schema_dir}")
    print(f"  spec_dir:       {ctx.spec_dir}")
    print(f"  artifact_dir:   {ctx.artifact_dir}")
    print(f"  session_dir:    {ctx.session_dir}")
    print(f"  test_output_dir:{ctx.test_output_dir}")
    print()
    schemas = list(ctx.schema_dir.glob("*.json"))
    if schemas:
        print(f"  Starter schemas copied ({len(schemas)}):")
        for s in sorted(schemas):
            print(f"    - {s.name}")
        print()
    print("Next steps:")
    print("  1. Edit schemas in .cw9/schema/ to match your project")
    print("  2. Run: cw9 status")

    return 0


def cmd_status(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()
    state_root = target / ".cw9"

    if not state_root.exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        print("Run: cw9 init", file=sys.stderr)
        return 1

    from registry.status import gather_status
    status = gather_status(target)

    if getattr(args, "output_json", False):
        print(json.dumps(status.to_dict(), indent=2))
        return 0

    ctx = ProjectContext.from_target(target)
    print(f"CodeWriter9 project: {ctx.target_root}")
    print(f"  engine: {ctx.engine_root or '(installed mode)'}")
    print()

    # Scoreboard
    parts = []
    if status.verified:
        parts.append(f"{status.verified} verified")
    if status.failed:
        parts.append(f"{status.failed} failed")
    if status.in_progress:
        parts.append(f"{status.in_progress} in progress")
    if status.pending:
        parts.append(f"{status.pending} pending")
    print(f"Pipeline: {', '.join(parts) or 'no GWTs'} ({status.total} total)")
    if status.verified:
        print(f"Bridge:   {status.bridge_complete}/{status.verified} complete")
    print()

    if not status.gwts:
        return 0

    # Per-GWT table
    print(f"  {'GWT':<16} {'SPEC':<14} {'ATTEMPTS':<10} {'BRIDGE':<8}")
    for gwt_id, gs in sorted(status.gwts.items()):
        result_str = gs.result.upper()
        attempts_str = str(gs.attempts) if gs.attempts > 0 else "-"
        bridge_str = "DONE" if gs.bridge_done else "-"
        print(f"  {gwt_id:<16} {result_str:<14} {attempts_str:<10} {bridge_str:<8}")

    # Failed summary
    failed = {gid: gs for gid, gs in status.gwts.items() if gs.result == "fail"}
    if failed:
        print()
        print(f"Failed ({len(failed)}):")
        for gwt_id, gs in sorted(failed.items()):
            err = gs.error or "unknown error"
            print(f"  {gwt_id}  {err}")

    return 0


def cmd_extract(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()
    state_root = target / ".cw9"

    if not state_root.exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        print("Run: cw9 init", file=sys.stderr)
        return 1

    ctx = ProjectContext.from_target(target)
    dag_path = state_root / "dag.json"

    # Load old DAG for diff summary AND GWT preservation
    old_dag = None
    old_nodes, old_edges = 0, 0
    if dag_path.exists():
        from registry.dag import RegistryDag
        old_dag = RegistryDag.load(dag_path)
        old_nodes = old_dag.node_count
        old_edges = old_dag.edge_count

    # Extract fresh DAG from schemas
    from registry.extractor import SchemaExtractor
    extractor = SchemaExtractor(schema_dir=str(ctx.schema_dir), self_host=ctx.is_self_hosting)
    dag = extractor.extract()

    # Merge registered GWTs from old DAG back in
    merged = 0
    if old_dag is not None:
        merged = dag.merge_registered_nodes(old_dag)

    # Save
    dag.save(dag_path)

    # Diff summary
    new_nodes = dag.node_count
    new_edges = dag.edge_count
    dn = new_nodes - old_nodes
    de = new_edges - old_edges
    sign = lambda x: f"+{x}" if x > 0 else str(x)
    print(f"DAG updated: {new_nodes} nodes ({sign(dn)}), {new_edges} edges ({sign(de)})")
    if merged > 0:
        print(f"  (preserved {merged} registered node(s) from previous DAG)")

    return 0


def cmd_loop(args: argparse.Namespace) -> int:
    import asyncio

    target = Path(args.target_dir).resolve()
    if not (target / ".cw9").exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        return 1

    from registry.loop_runner import run_loop
    from registry.one_shot_loop import LoopResult

    ctx = ProjectContext.from_target(target)
    context_text = ""
    if args.context_file and args.context_file.exists():
        context_text = args.context_file.read_text()
    result, spec_path = asyncio.run(run_loop(
        ctx=ctx,
        gwt_id=args.gwt_id,
        max_retries=args.max_retries,
        context_text=context_text,
    ))

    if result == LoopResult.PASS:
        print(f"Verified: {spec_path}")
        return 0
    else:
        print("Loop failed.", file=sys.stderr)
        return 1


def cmd_bridge(args: argparse.Namespace) -> int:
    target = Path(args.target_dir).resolve()
    if not (target / ".cw9").exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        return 1

    ctx = ProjectContext.from_target(target)
    gwt_id = args.gwt_id

    spec_path = ctx.spec_dir / f"{gwt_id}.tla"
    if not spec_path.exists():
        print(f"No verified spec found: {spec_path}", file=sys.stderr)
        print(f"Run: cw9 loop {gwt_id}", file=sys.stderr)
        return 1

    from registry.bridge import run_bridge, TlcTrace
    tla_text = spec_path.read_text()

    # Load counterexample traces (from retry failures)
    traces_path = ctx.spec_dir / f"{gwt_id}_traces.json"
    traces = []
    if traces_path.exists():
        traces_data = json.loads(traces_path.read_text())
        traces = [TlcTrace(**td) for td in traces_data]

    result = run_bridge(tla_text, traces=traces)

    artifacts = {
        "gwt_id": gwt_id,
        "module_name": result.module_name,
        "data_structures": result.data_structures,
        "operations": result.operations,
        "verifiers": result.verifiers,
        "assertions": result.assertions,
        "test_scenarios": [
            {"name": s.name, "setup": s.setup, "steps": s.steps,
             "expected_outcome": s.expected_outcome, "invariant_tested": s.invariant_tested}
            for s in result.test_scenarios
        ],
    }

    # v5: Load simulation traces (primary context for gen-tests)
    sim_traces_path = ctx.spec_dir / f"{gwt_id}_sim_traces.json"
    if sim_traces_path.exists():
        artifacts["simulation_traces"] = json.loads(sim_traces_path.read_text())
    else:
        artifacts["simulation_traces"] = []

    ctx.artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact_path = ctx.artifact_dir / f"{gwt_id}_bridge_artifacts.json"
    artifact_path.write_text(json.dumps(artifacts, indent=2) + "\n")

    print(f"Bridge artifacts saved: {artifact_path}")
    print(f"  data_structures: {len(result.data_structures)}")
    print(f"  operations: {len(result.operations)}")
    print(f"  verifiers: {len(result.verifiers)}")
    print(f"  assertions: {len(result.assertions)}")

    return 0


def cmd_gen_tests(args: argparse.Namespace) -> int:
    import asyncio

    target = Path(args.target_dir).resolve()
    if not (target / ".cw9").exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        return 1

    ctx = ProjectContext.from_target(target)
    gwt_id = args.gwt_id

    # Load bridge artifacts
    artifact_path = ctx.artifact_dir / f"{gwt_id}_bridge_artifacts.json"
    if not artifact_path.exists():
        print(f"No bridge artifacts found: {artifact_path}", file=sys.stderr)
        print(f"Run: cw9 bridge {gwt_id}", file=sys.stderr)
        return 1

    bridge_artifacts = json.loads(artifact_path.read_text())
    module_name = bridge_artifacts.get("module_name", gwt_id)

    # Load GWT text from DAG
    from registry.dag import RegistryDag
    dag_path = ctx.state_root / "dag.json"
    gwt_text = {"given": "", "when": "", "then": ""}
    if dag_path.exists():
        dag = RegistryDag.load(dag_path)
        if gwt_id in dag.nodes:
            node = dag.nodes[gwt_id]
            gwt_text = {
                "given": node.given or "",
                "when": node.when or "",
                "then": node.then or "",
            }

    # Build context
    from registry.lang import TargetLanguage, get_profile
    from registry.test_gen_loop import (
        TestGenContext, build_compiler_hints, discover_api_context,
        run_test_gen_loop,
    )

    lang_profile = get_profile(TargetLanguage(args.lang))
    compiler_hints = build_compiler_hints(bridge_artifacts, lang_profile)
    api_context = lang_profile.discover_api_context(ctx.python_dir, module_name)
    test_scenarios = bridge_artifacts.get("test_scenarios", [])

    # v5: Load simulation traces (PRIMARY context for test generation)
    simulation_traces = bridge_artifacts.get("simulation_traces", [])
    if not simulation_traces:
        sim_traces_path = ctx.spec_dir / f"{gwt_id}_sim_traces.json"
        if sim_traces_path.exists():
            simulation_traces = json.loads(sim_traces_path.read_text())

    # v5: Load TLA+ spec text (full picture, rank 4 context)
    tla_spec_text = ""
    spec_path = ctx.spec_dir / f"{gwt_id}.tla"
    if spec_path.exists():
        tla_spec_text = spec_path.read_text()

    gen_ctx = TestGenContext(
        gwt_id=gwt_id,
        gwt_text=gwt_text,
        module_name=module_name,
        bridge_artifacts=bridge_artifacts,
        compiler_hints=compiler_hints,
        api_context=api_context,
        test_scenarios=test_scenarios,
        simulation_traces=simulation_traces,
        tla_spec_text=tla_spec_text,
        output_dir=ctx.test_output_dir,
        source_dir=ctx.python_dir,
        lang_profile=lang_profile,
    )

    from registry.loop_runner import call_llm

    session_dir = ctx.state_root / "sessions"
    result = asyncio.run(run_test_gen_loop(
        gen_ctx, call_llm,
        max_attempts=args.max_attempts,
        session_dir=session_dir,
    ))

    if result.passed:
        output_name = lang_profile.test_file_name(gwt_id)
        test_path = ctx.test_output_dir / output_name
        print(f"Generated: {test_path} ({result.attempt} attempt(s))")
        return 0
    else:
        print(f"Failed after {result.attempt} attempts", file=sys.stderr)
        for err in result.errors:
            print(f"  {err}", file=sys.stderr)
        return 1


def _register_payload(target: Path, payload: dict) -> dict:
    """Register requirements + GWT behaviors from a dict. Returns result dict.

    Returns:
        {"requirements": [{"id": cw7_id, "req_id": req_id}, ...],
         "gwts": [{"criterion_id": criterion_id, "gwt_id": gwt_id}, ...]}
    """
    from registry.dag import RegistryDag
    from registry.bindings import load_bindings, save_bindings

    ctx = ProjectContext.from_target(target)
    dag_path = ctx.state_root / "dag.json"
    dag = RegistryDag.load(dag_path)
    bindings = load_bindings(ctx.state_root)

    requirements = payload.get("requirements", [])
    gwts = payload.get("gwts", [])

    # Phase 1: Register requirements
    req_output = []
    req_id_map = {}  # CW7 id -> CW9 req-NNNN
    for req in requirements:
        cw7_id = req["id"]
        binding_key = f"req:{cw7_id}"

        if binding_key in bindings:
            req_id = bindings[binding_key]
        else:
            req_id = dag.register_requirement(
                text=req.get("text", cw7_id),
                name=req.get("name"),
            )
            bindings[binding_key] = req_id

        req_id_map[cw7_id] = req_id
        req_output.append({"id": cw7_id, "req_id": req_id})

    # Phase 2: Register GWTs
    gwt_output = []
    for gwt in gwts:
        criterion_id = gwt["criterion_id"]
        binding_key = f"gwt:{criterion_id}"

        if binding_key in bindings:
            gwt_id = bindings[binding_key]
        else:
            # Resolve parent_req: CW7 id -> CW9 req-NNNN
            parent_req = None
            if gwt.get("parent_req"):
                cw7_req_id = gwt["parent_req"]
                parent_req = req_id_map.get(cw7_req_id)
                if parent_req is None:
                    # Check if it's already a CW9 req-NNNN ID in the DAG
                    if cw7_req_id in dag.nodes:
                        parent_req = cw7_req_id
                    else:
                        # Check bindings from a prior run
                        parent_req = bindings.get(f"req:{cw7_req_id}")

            gwt_id = dag.register_gwt(
                given=gwt["given"],
                when=gwt["when"],
                then=gwt["then"],
                parent_req=parent_req,
                name=gwt.get("name"),
            )
            bindings[binding_key] = gwt_id

        gwt_output.append({"criterion_id": criterion_id, "gwt_id": gwt_id})

    # Save
    dag.save(dag_path)
    save_bindings(ctx.state_root, bindings)

    return {"requirements": req_output, "gwts": gwt_output}


def cmd_register(args: argparse.Namespace) -> int:
    """Register requirements + GWT behaviors from JSON stdin. Emit JSON stdout."""
    target = Path(args.target_dir).resolve()
    if not (target / ".cw9").exists():
        print(json.dumps({"error": f"No .cw9/ found in {target}"}), file=sys.stderr)
        return 1

    # Read and parse stdin
    try:
        payload = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, ValueError) as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}), file=sys.stderr)
        return 1

    # Validate requirements have id
    for i, req in enumerate(payload.get("requirements", [])):
        if "id" not in req:
            print(json.dumps({"error": f"requirements[{i}]: missing required field 'id'"}),
                  file=sys.stderr)
            return 1

    # Validate GWTs have criterion_id and given/when/then
    for i, gwt in enumerate(payload.get("gwts", [])):
        if "criterion_id" not in gwt:
            print(json.dumps({"error": f"gwts[{i}]: missing required field 'criterion_id'"}),
                  file=sys.stderr)
            return 1
        for field in ("given", "when", "then"):
            if field not in gwt:
                print(json.dumps({"error": f"gwts[{i}]: missing required field '{field}'"}),
                      file=sys.stderr)
                return 1

    result = _register_payload(target, payload)
    print(json.dumps(result, indent=2))
    return 0


def _resolve_gwt_ids(
    project_dir: Path,
    register_output: dict | None,
    explicit_gwts: list | None,
) -> list[str]:
    """Determine which GWT IDs to process.

    Resolution order:
    1. Explicit --gwt args (if provided)
    2. register_output from setup phase (if available)
    3. DAG nodes (fallback)
    """
    if explicit_gwts:
        return explicit_gwts
    if register_output and register_output.get("gwts"):
        return [g["gwt_id"] for g in register_output["gwts"]]
    dag_path = project_dir / ".cw9" / "dag.json"
    if dag_path.exists():
        dag_data = json.loads(dag_path.read_text())
        return sorted(nid for nid in dag_data.get("nodes", {}) if nid.startswith("gwt-"))
    return []


def _find_context_file(project_dir: Path, gwt_id: str, gwt_to_criterion: dict | None) -> Path | None:
    """Find context file for a GWT in .cw9/context/."""
    context_dir = project_dir / ".cw9" / "context"
    if not context_dir.exists():
        return None
    if gwt_to_criterion:
        crit_id = gwt_to_criterion.get(gwt_id)
        if crit_id:
            ctx_file = context_dir / f"{crit_id}.md"
            if ctx_file.exists():
                return ctx_file
    return None


def cmd_pipeline(args: argparse.Namespace) -> int:
    """Run full CW9 pipeline: setup -> loop -> bridge."""
    target = Path(args.target_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)

    need_setup = not args.skip_setup and not args.bridge_only

    # DB validation
    if need_setup:
        db = args.db or (Path(os.environ["CW7_DB"]) if os.environ.get("CW7_DB") else None)
        if not db:
            print("Error: --db required (or set CW7_DB)", file=sys.stderr)
            return 1
        if not db.exists():
            print(f"Error: CW7 database not found: {db}", file=sys.stderr)
            return 1
    else:
        db = None

    # Session inference from plan_path_dir
    session_id = args.session
    if session_id is None and args.plan_path_dir is not None:
        dirname = args.plan_path_dir.name
        if dirname.startswith("session-"):
            session_id = dirname

    # Phase 0: Setup
    register_output = None
    gwt_to_criterion: dict[str, str] = {}
    if need_setup:
        # init
        rc = main(["init", str(target), "--ensure"])
        if rc != 0:
            return rc

        # extract
        rc = main(["extract", str(target)])
        if rc != 0:
            return rc

        # CW7 extract + register
        from registry.cw7 import extract as cw7_extract, build_plan_path_map, copy_context_files
        payload = cw7_extract(db, session_id)

        # Copy plan_path context files
        if args.plan_path_dir is not None:
            context_dir = target / ".cw9" / "context"
            pp_map = build_plan_path_map(db, session_id) if session_id else None
            copy_context_files(args.plan_path_dir, context_dir, payload["gwts"], pp_map)

        register_output = _register_payload(target, payload)

        # Build gwt_id -> criterion_id mapping
        if register_output and register_output.get("gwts"):
            for g in register_output["gwts"]:
                gwt_to_criterion[g["gwt_id"]] = g["criterion_id"]

    # Resolve targets
    gwt_ids = _resolve_gwt_ids(target, register_output, args.gwts)
    if not gwt_ids:
        print("Error: No GWT IDs found. Provide --gwt or ensure register ran.", file=sys.stderr)
        return 1

    # Phase 1: Loop
    loop_results: dict[str, bool] = {}
    if not args.bridge_only:
        for gwt_id in gwt_ids:
            ctx_file_path = _find_context_file(target, gwt_id, gwt_to_criterion)
            loop_ns = argparse.Namespace(
                gwt_id=gwt_id,
                target_dir=str(target),
                max_retries=args.max_retries,
                context_file=ctx_file_path,
            )
            rc = cmd_loop(loop_ns)
            loop_results[gwt_id] = (rc == 0)

    # Determine which GWTs to bridge
    if args.bridge_only:
        verified_ids = [
            gid for gid in gwt_ids
            if (target / ".cw9" / "specs" / f"{gid}.tla").exists()
        ]
    else:
        verified_ids = [gid for gid, passed in loop_results.items() if passed]

    # Phase 2: Bridge
    bridge_results: dict[str, bool] = {}
    if not args.loop_only and verified_ids:
        for gwt_id in verified_ids:
            spec_path = target / ".cw9" / "specs" / f"{gwt_id}.tla"
            if not spec_path.exists():
                continue
            bridge_ns = argparse.Namespace(
                gwt_id=gwt_id,
                target_dir=str(target),
            )
            rc = cmd_bridge(bridge_ns)
            bridge_results[gwt_id] = (rc == 0)

    # Exit code: 0 if all attempted steps passed
    all_passed = (
        all(loop_results.values()) if loop_results else True
    ) and (
        all(bridge_results.values()) if bridge_results else True
    )
    return 0 if all_passed else 1


def cmd_test(args: argparse.Namespace) -> int:
    import subprocess as sp

    target = Path(args.target_dir).resolve()
    if not (target / ".cw9").exists():
        print(f"No .cw9/ found in {target}", file=sys.stderr)
        return 1

    ctx = ProjectContext.from_target(target)
    test_dir = ctx.test_output_dir

    if not test_dir.exists() or not list(test_dir.glob("test_*.py")):
        print(f"No generated tests in {test_dir}", file=sys.stderr)
        print("Run: cw9 gen-tests <gwt-id>", file=sys.stderr)
        return 1

    test_files = []

    if args.node_id:
        from registry.dag import RegistryDag
        dag_path = ctx.state_root / "dag.json"
        if not dag_path.exists():
            print("No DAG found. Run: cw9 extract", file=sys.stderr)
            return 1
        dag = RegistryDag.load(dag_path)

        # Populate test_artifacts from bridge artifact files
        for artifact_file in ctx.artifact_dir.glob("*_bridge_artifacts.json"):
            data = json.loads(artifact_file.read_text())
            gid = data.get("gwt_id", "")
            test_path = test_dir / f"test_{gid.replace('-', '_')}.py"
            if test_path.exists():
                dag.test_artifacts[gid] = str(test_path)

        affected = dag.query_affected_tests(args.node_id)
        if not affected:
            print(f"No tests affected by {args.node_id}")
            return 0
        test_files = affected
        print(f"Running {len(test_files)} affected test(s) for {args.node_id}")
    else:
        test_files = [str(f) for f in sorted(test_dir.glob("test_*.py"))]
        print(f"Running {len(test_files)} generated test(s)")

    result = sp.run(
        [sys.executable, "-m", "pytest"] + test_files + ["-v"],
        cwd=str(ctx.python_dir),
    )
    return result.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="cw9",
        description="CodeWriter9 — formally verified code generation",
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="Initialize .cw9/ in a target directory")
    p_init.add_argument("target_dir", nargs="?", default=".", help="Target project directory (default: .)")
    p_init.add_argument("--force", action="store_true", help="Reinitialize existing .cw9/")
    p_init.add_argument("--ensure", action="store_true",
                         help="No-op if .cw9/ already exists (idempotent init)")

    # status
    p_status = sub.add_parser("status", help="Show pipeline progress and per-GWT status")
    p_status.add_argument("target_dir", nargs="?", default=".", help="Target project directory (default: .)")
    p_status.add_argument("--json", action="store_true", dest="output_json", help="Output machine-readable JSON")

    # extract
    p_extract = sub.add_parser("extract", help="Extract DAG from schemas")
    p_extract.add_argument("target_dir", nargs="?", default=".")

    # loop
    p_loop = sub.add_parser("loop", help="Run LLM → PlusCal → TLC for a GWT behavior")
    p_loop.add_argument("gwt_id", help="GWT behavior ID (e.g., gwt-0024)")
    p_loop.add_argument("target_dir", nargs="?", default=".")
    p_loop.add_argument("--max-retries", type=int, default=8)
    p_loop.add_argument("--context-file", type=Path, default=None,
                        help="Supplementary context file passed verbatim to LLM")

    # bridge
    p_bridge = sub.add_parser("bridge", help="Translate verified spec → bridge artifacts")
    p_bridge.add_argument("gwt_id", help="GWT behavior ID")
    p_bridge.add_argument("target_dir", nargs="?", default=".")

    # gen-tests
    p_gen = sub.add_parser("gen-tests", help="Generate test file from bridge artifacts (LLM loop)")
    p_gen.add_argument("gwt_id", help="GWT behavior ID")
    p_gen.add_argument("target_dir", nargs="?", default=".")
    p_gen.add_argument("--max-attempts", type=int, default=3, help="Max generation attempts")
    p_gen.add_argument(
        "--lang", default="python",
        choices=["python", "typescript", "rust", "go"],
        help="Target language for test generation (default: python)",
    )

    # register
    p_reg = sub.add_parser("register", help="Register requirements + GWTs from JSON stdin")
    p_reg.add_argument("target_dir", nargs="?", default=".")

    # test
    p_test = sub.add_parser("test", help="Run generated tests (smart targeting optional)")
    p_test.add_argument("--node", dest="node_id", help="Only run tests affected by this node")
    p_test.add_argument("target_dir", nargs="?", default=".")

    # pipeline
    p_pipeline = sub.add_parser("pipeline", help="Run full CW9 pipeline: setup -> loop -> bridge")
    p_pipeline.add_argument("target_dir", nargs="?", default=".")
    p_pipeline.add_argument("--db", type=Path, default=None,
                             help="CW7 SQLite database path (or set CW7_DB env var)")
    p_pipeline.add_argument("--session", default=None)
    p_pipeline.add_argument("--gwt", action="append", dest="gwts", default=None)
    p_pipeline.add_argument("--max-retries", type=int, default=8)
    p_pipeline.add_argument("--skip-setup", action="store_true")
    p_pipeline.add_argument("--loop-only", action="store_true")
    p_pipeline.add_argument("--bridge-only", action="store_true")
    p_pipeline.add_argument("--plan-path-dir", type=Path, default=None)

    args = parser.parse_args(argv)

    if args.command == "init":
        return cmd_init(args)
    elif args.command == "status":
        return cmd_status(args)
    elif args.command == "extract":
        return cmd_extract(args)
    elif args.command == "loop":
        return cmd_loop(args)
    elif args.command == "bridge":
        return cmd_bridge(args)
    elif args.command == "gen-tests":
        return cmd_gen_tests(args)
    elif args.command == "register":
        return cmd_register(args)
    elif args.command == "test":
        return cmd_test(args)
    elif args.command == "pipeline":
        return cmd_pipeline(args)
    else:
        parser.print_help()
        return 0


if __name__ == "__main__":
    sys.exit(main())
