"""Simulation trace types and prompt formatting for test generation.

v5: TLC simulation traces are pre-verified concrete execution paths through
the state space. Each trace says: "starting from THIS state, applying THESE
actions, produces THIS result, and ALL invariants hold at every step."
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class SimulationTrace:
    """A TLC simulation trace — verified concrete scenario.

    Unlike CounterexampleTrace (which represents a violation), simulation
    traces represent VALID executions where all invariants hold.
    """
    states: list[dict[str, Any]]  # [{state_num, label, vars: {name: value}}]
    invariants_verified: list[str] = field(default_factory=list)

    @property
    def init_state(self) -> dict[str, str]:
        """The initial state — defines the test fixture."""
        return self.states[0]["vars"] if self.states else {}

    @property
    def final_state(self) -> dict[str, str]:
        """The final state — defines expected assertions."""
        return self.states[-1]["vars"] if self.states else {}

    @property
    def actions(self) -> list[str]:
        """The action sequence (labels after Init) — defines API calls."""
        return [s["label"] for s in self.states[1:]]

    @property
    def step_count(self) -> int:
        return len(self.states)


def format_traces_for_prompt(
    traces: list[SimulationTrace],
    invariant_names: list[str],
) -> str:
    """Format simulation traces as concrete verified scenarios for LLM prompt.

    This is the HIGHEST-RANKED context in the test generation prompt stack.
    Each trace is a pre-verified test case — the LLM translates (not invents).
    """
    sections = ["## Concrete Verified Scenarios\n"]
    sections.append(
        "Each trace below was generated by TLC from the verified model. "
        "ALL invariants hold at EVERY state. These are your test cases — "
        "translate each trace into Python API calls.\n"
    )

    for i, trace in enumerate(traces, 1):
        sections.append(
            f"### Trace {i} ({trace.step_count} steps, "
            f"tests {', '.join(invariant_names)})"
        )
        sections.append(f"Actions: {' → '.join(trace.actions)}\n")

        for state in trace.states:
            sections.append(f"State {state['state_num']}: <{state['label']}>")
            for var, val in state["vars"].items():
                sections.append(f"  /\\ {var} = {val}")
            sections.append("")

    return "\n".join(sections)


def load_simulation_traces(
    traces_data: list[list[dict[str, Any]]],
    invariant_names: list[str] | None = None,
) -> list[SimulationTrace]:
    """Load simulation traces from JSON data (as saved by cw9 loop).

    Args:
        traces_data: Raw JSON — list of traces, each a list of state dicts
        invariant_names: Names of invariants verified by the spec
    """
    return [
        SimulationTrace(
            states=trace_states,
            invariants_verified=invariant_names or [],
        )
        for trace_states in traces_data
    ]
