------------------------------ MODULE bridge_loop_composed ------------------------------
(*
 * Composed from: bridge_translator + one_shot_loop
 * Shared variables: current_state, dirty, op, pc, result, step_count
 * Generated by CodeWriter9.0 Composition Engine
 *)

EXTENDS FiniteSets, Integers, Sequences, TLC

CONSTANTS
    MaxSteps

VARIABLES
    actions_found, assertions_out, compose_busy, composed_specs, consecutive_failures, current_state, data_structures_out, dirty, has_counterexample, has_traces, input_hash, invariants_found, op, operations_out, pc, result, scenarios_out, schema_valid, step_count, tlc_passed, vars_found, verifiers_out

vars == << actions_found, assertions_out, compose_busy, composed_specs, consecutive_failures, current_state, data_structures_out, dirty, has_counterexample, has_traces, input_hash, invariants_found, op, operations_out, pc, result, scenarios_out, schema_valid, step_count, tlc_passed, vars_found, verifiers_out >>

\* --- Definitions from bridge_translator ---
bridge_translator_StateSet == {"idle", "parsing_spec", "translating_vars",
             "translating_actions", "translating_invariants",
             "translating_traces", "validating_output",
             "done", "failed"}
bridge_translator_ValidState == current_state \in StateSet
bridge_translator_BoundedExecution == step_count <= MaxSteps
bridge_translator_OutputConformsToSchema == dirty = TRUE \/
    (current_state = "done" =>
        /\ data_structures_out = vars_found
        /\ operations_out = actions_found
        /\ verifiers_out = invariants_found
        /\ assertions_out = invariants_found)
bridge_translator_TranslationOrder == dirty = TRUE \/
    (/\ (current_state = "translating_actions" => data_structures_out = vars_found)
     /\ (current_state = "translating_invariants" => operations_out = actions_found)
     /\ (current_state = "translating_traces" => verifiers_out = invariants_found))
bridge_translator_NoPartialOutput == dirty = TRUE \/
    (current_state = "done" =>
        /\ data_structures_out = vars_found
        /\ operations_out = actions_found
        /\ verifiers_out = invariants_found
        /\ assertions_out = invariants_found)
bridge_translator_InputPreserved == dirty = TRUE \/
    (current_state \notin {"idle", "parsing_spec"} => input_hash > 0)
bridge_translator_MainLoop == /\ pc["main"] = "MainLoop"
            /\ IF current_state \notin {"done", "failed"} /\ step_count < MaxSteps
                  THEN /\ \/ /\ pc' = [pc EXCEPT !["main"] = "ReceiveSpec"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "ParseSpec"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "TranslateVars"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "TranslateActions"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "TranslateInvariants"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "TranslateTraces"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "ValidateOutput"]
                  ELSE /\ pc' = [pc EXCEPT !["main"] = "Done"]
            /\ UNCHANGED << current_state, vars_found, actions_found, 
                            invariants_found, has_traces, data_structures_out, 
                            operations_out, verifiers_out, assertions_out, 
                            scenarios_out, schema_valid, input_hash, 
                            step_count, op, result, dirty >>
bridge_translator_ReceiveSpec == /\ pc["main"] = "ReceiveSpec"
               /\ IF current_state = "idle"
                     THEN /\ current_state' = "parsing_spec"
                          /\ dirty' = TRUE
                          /\ op' = "receive_spec"
                          /\ result' = "ok"
                          /\ step_count' = step_count + 1
                     ELSE /\ op' = "receive_skip"
                          /\ result' = "error"
                          /\ UNCHANGED << current_state, step_count, dirty >>
               /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
               /\ UNCHANGED << vars_found, actions_found, invariants_found, 
                               has_traces, data_structures_out, operations_out, 
                               verifiers_out, assertions_out, scenarios_out, 
                               schema_valid, input_hash >>
bridge_translator_ParseSpec == /\ pc["main"] = "ParseSpec"
             /\ IF current_state = "parsing_spec"
                   THEN /\ vars_found' = NumVariables
                        /\ actions_found' = NumActions
                        /\ invariants_found' = NumInvariants
                        /\ has_traces' = (NumInvariants > 0)
                        /\ input_hash' = NumVariables + NumActions + NumInvariants + 1
                        /\ dirty' = TRUE
                        /\ op' = "parsed"
                        /\ step_count' = step_count + 1
                        /\ pc' = [pc EXCEPT !["main"] = "ParseDecide"]
                        /\ UNCHANGED result
                   ELSE /\ op' = "parse_skip"
                        /\ result' = "error"
                        /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                        /\ UNCHANGED << vars_found, actions_found, 
                                        invariants_found, has_traces, 
                                        input_hash, step_count, dirty >>
             /\ UNCHANGED << current_state, data_structures_out, 
                             operations_out, verifiers_out, assertions_out, 
                             scenarios_out, schema_valid >>
bridge_translator_ParseDecide == /\ pc["main"] = "ParseDecide"
               /\ IF NumVariables >= 0 /\ NumActions >= 0 /\ NumInvariants >= 0
                     THEN /\ current_state' = "translating_vars"
                          /\ result' = "ok"
                     ELSE /\ current_state' = "failed"
                          /\ result' = "parse_error"
               /\ dirty' = FALSE
               /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
               /\ UNCHANGED << vars_found, actions_found, invariants_found, 
                               has_traces, data_structures_out, operations_out, 
                               verifiers_out, assertions_out, scenarios_out, 
                               schema_valid, input_hash, step_count, op >>
bridge_translator_TranslateVars == /\ pc["main"] = "TranslateVars"
                 /\ IF current_state = "translating_vars"
                       THEN /\ data_structures_out' = vars_found
                            /\ current_state' = "translating_actions"
                            /\ dirty' = TRUE
                            /\ op' = "translated_vars"
                            /\ result' = "ok"
                            /\ step_count' = step_count + 1
                            /\ pc' = [pc EXCEPT !["main"] = "TranslateVarsDone"]
                       ELSE /\ op' = "vars_skip"
                            /\ result' = "error"
                            /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                            /\ UNCHANGED << current_state, data_structures_out, 
                                            step_count, dirty >>
                 /\ UNCHANGED << vars_found, actions_found, invariants_found, 
                                 has_traces, operations_out, verifiers_out, 
                                 assertions_out, scenarios_out, schema_valid, 
                                 input_hash >>
bridge_translator_TranslateVarsDone == /\ pc["main"] = "TranslateVarsDone"
                     /\ dirty' = FALSE
                     /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                     /\ UNCHANGED << current_state, vars_found, actions_found, 
                                     invariants_found, has_traces, 
                                     data_structures_out, operations_out, 
                                     verifiers_out, assertions_out, 
                                     scenarios_out, schema_valid, input_hash, 
                                     step_count, op, result >>
bridge_translator_TranslateActions == /\ pc["main"] = "TranslateActions"
                    /\ IF current_state = "translating_actions"
                          THEN /\ operations_out' = actions_found
                               /\ current_state' = "translating_invariants"
                               /\ dirty' = TRUE
                               /\ op' = "translated_actions"
                               /\ result' = "ok"
                               /\ step_count' = step_count + 1
                               /\ pc' = [pc EXCEPT !["main"] = "TranslateActionsDone"]
                          ELSE /\ op' = "actions_skip"
                               /\ result' = "error"
                               /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                               /\ UNCHANGED << current_state, operations_out, 
                                               step_count, dirty >>
                    /\ UNCHANGED << vars_found, actions_found, 
                                    invariants_found, has_traces, 
                                    data_structures_out, verifiers_out, 
                                    assertions_out, scenarios_out, 
                                    schema_valid, input_hash >>
bridge_translator_TranslateActionsDone == /\ pc["main"] = "TranslateActionsDone"
                        /\ dirty' = FALSE
                        /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                        /\ UNCHANGED << current_state, vars_found, 
                                        actions_found, invariants_found, 
                                        has_traces, data_structures_out, 
                                        operations_out, verifiers_out, 
                                        assertions_out, scenarios_out, 
                                        schema_valid, input_hash, step_count, 
                                        op, result >>
bridge_translator_TranslateInvariants == /\ pc["main"] = "TranslateInvariants"
                       /\ IF current_state = "translating_invariants"
                             THEN /\ verifiers_out' = invariants_found
                                  /\ assertions_out' = invariants_found
                                  /\ current_state' = "translating_traces"
                                  /\ dirty' = TRUE
                                  /\ op' = "translated_invariants"
                                  /\ result' = "ok"
                                  /\ step_count' = step_count + 1
                                  /\ pc' = [pc EXCEPT !["main"] = "TranslateInvariantsDone"]
                             ELSE /\ op' = "invariants_skip"
                                  /\ result' = "error"
                                  /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                                  /\ UNCHANGED << current_state, verifiers_out, 
                                                  assertions_out, step_count, 
                                                  dirty >>
                       /\ UNCHANGED << vars_found, actions_found, 
                                       invariants_found, has_traces, 
                                       data_structures_out, operations_out, 
                                       scenarios_out, schema_valid, input_hash >>
bridge_translator_TranslateInvariantsDone == /\ pc["main"] = "TranslateInvariantsDone"
                           /\ dirty' = FALSE
                           /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                           /\ UNCHANGED << current_state, vars_found, 
                                           actions_found, invariants_found, 
                                           has_traces, data_structures_out, 
                                           operations_out, verifiers_out, 
                                           assertions_out, scenarios_out, 
                                           schema_valid, input_hash, 
                                           step_count, op, result >>
bridge_translator_TranslateTraces == /\ pc["main"] = "TranslateTraces"
                   /\ IF current_state = "translating_traces"
                         THEN /\ IF has_traces
                                    THEN /\ scenarios_out' = invariants_found
                                    ELSE /\ scenarios_out' = 0
                              /\ current_state' = "validating_output"
                              /\ dirty' = TRUE
                              /\ op' = "translated_traces"
                              /\ result' = "ok"
                              /\ step_count' = step_count + 1
                              /\ pc' = [pc EXCEPT !["main"] = "TranslateTracesDone"]
                         ELSE /\ op' = "traces_skip"
                              /\ result' = "error"
                              /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                              /\ UNCHANGED << current_state, scenarios_out, 
                                              step_count, dirty >>
                   /\ UNCHANGED << vars_found, actions_found, invariants_found, 
                                   has_traces, data_structures_out, 
                                   operations_out, verifiers_out, 
                                   assertions_out, schema_valid, input_hash >>
bridge_translator_TranslateTracesDone == /\ pc["main"] = "TranslateTracesDone"
                       /\ dirty' = FALSE
                       /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                       /\ UNCHANGED << current_state, vars_found, 
                                       actions_found, invariants_found, 
                                       has_traces, data_structures_out, 
                                       operations_out, verifiers_out, 
                                       assertions_out, scenarios_out, 
                                       schema_valid, input_hash, step_count, 
                                       op, result >>
bridge_translator_ValidateOutput == /\ pc["main"] = "ValidateOutput"
                  /\ IF current_state = "validating_output"
                        THEN /\ dirty' = TRUE
                             /\ step_count' = step_count + 1
                             /\ pc' = [pc EXCEPT !["main"] = "ValidateDecide"]
                             /\ UNCHANGED << op, result >>
                        ELSE /\ op' = "validate_skip"
                             /\ result' = "error"
                             /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                             /\ UNCHANGED << step_count, dirty >>
                  /\ UNCHANGED << current_state, vars_found, actions_found, 
                                  invariants_found, has_traces, 
                                  data_structures_out, operations_out, 
                                  verifiers_out, assertions_out, scenarios_out, 
                                  schema_valid, input_hash >>
bridge_translator_ValidateDecide == /\ pc["main"] = "ValidateDecide"
                  /\ IF data_structures_out = vars_found
                        /\ operations_out = actions_found
                        /\ verifiers_out = invariants_found
                        /\ assertions_out = invariants_found
                        THEN /\ schema_valid' = TRUE
                             /\ current_state' = "done"
                             /\ op' = "validated"
                             /\ result' = "success"
                        ELSE /\ schema_valid' = FALSE
                             /\ current_state' = "failed"
                             /\ op' = "validation_failed"
                             /\ result' = "schema_mismatch"
                  /\ dirty' = FALSE
                  /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                  /\ UNCHANGED << vars_found, actions_found, invariants_found, 
                                  has_traces, data_structures_out, 
                                  operations_out, verifiers_out, 
                                  assertions_out, scenarios_out, input_hash, 
                                  step_count >>
bridge_translator_translator == MainLoop \/ ReceiveSpec \/ ParseSpec \/ ParseDecide
                 \/ TranslateVars \/ TranslateVarsDone \/ TranslateActions
                 \/ TranslateActionsDone \/ TranslateInvariants
                 \/ TranslateInvariantsDone \/ TranslateTraces
                 \/ TranslateTracesDone \/ ValidateOutput \/ ValidateDecide

\* --- Definitions from one_shot_loop ---
one_shot_loop_StateSet == {"idle", "querying_context", "prompting_llm",
             "extracting_fragment", "compiling", "composing",
             "verifying", "translating_error", "routing",
             "done", "failed"}
one_shot_loop_ValidState == current_state \in StateSet
one_shot_loop_MutualExclusionOnCompose == dirty = TRUE \/
    (current_state = "composing" => compose_busy = TRUE)
one_shot_loop_TwoFailureLimit == dirty = TRUE \/
    (consecutive_failures > MaxRetries => current_state \in {"failed", "routing"})
one_shot_loop_DeterministicRouting == dirty = TRUE \/
    (current_state = "done" => tlc_passed = TRUE)
one_shot_loop_BoundedExecution == step_count <= MaxSteps
one_shot_loop_DerivedConsistency == dirty = TRUE \/
    (current_state = "done" => consecutive_failures = 0)
one_shot_loop_MainLoop == /\ pc["main"] = "MainLoop"
            /\ IF current_state \notin {"done", "failed"} /\ step_count < MaxSteps
                  THEN /\ \/ /\ pc' = [pc EXCEPT !["main"] = "ReceiveBehavior"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "QueryContext"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "ReceiveResponse"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "ExtractFragment"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "CompilePlusCal"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "ComposeSpecs"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "RunTLC"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "TranslateError"]
                          \/ /\ pc' = [pc EXCEPT !["main"] = "RouteResult"]
                  ELSE /\ pc' = [pc EXCEPT !["main"] = "Done"]
            /\ UNCHANGED << current_state, consecutive_failures, compose_busy, 
                            composed_specs, tlc_passed, has_counterexample, 
                            step_count, op, result, dirty >>
one_shot_loop_UpdateDerived == /\ pc["main"] = "UpdateDerived"
                 /\ dirty' = FALSE
                 /\ pc' = [pc EXCEPT !["main"] = "MainLoop"]
                 /\ UNCHANGED << current_state, consecutive_failures, 
                                 compose_busy, composed_specs, tlc_passed, 
                                 has_counterexample, step_count, op, result >>
one_shot_loop_ReceiveBehavior == /\ pc["main"] = "ReceiveBehavior"
                   /\ IF current_state = "idle"
                         THEN /\ current_state' = "querying_context"
                              /\ dirty' = TRUE
                              /\ op' = "receive_behavior"
                              /\ result' = "ok"
                              /\ step_count' = step_count + 1
                         ELSE /\ op' = "receive_skip"
                              /\ result' = "error"
                              /\ UNCHANGED << current_state, step_count, dirty >>
                   /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                   /\ UNCHANGED << consecutive_failures, compose_busy, 
                                   composed_specs, tlc_passed, 
                                   has_counterexample >>
one_shot_loop_QueryContext == /\ pc["main"] = "QueryContext"
                /\ IF current_state = "querying_context"
                      THEN /\ current_state' = "prompting_llm"
                           /\ dirty' = TRUE
                           /\ op' = "query_context"
                           /\ result' = "ok"
                           /\ step_count' = step_count + 1
                      ELSE /\ op' = "query_skip"
                           /\ result' = "error"
                           /\ UNCHANGED << current_state, step_count, dirty >>
                /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                /\ UNCHANGED << consecutive_failures, compose_busy, 
                                composed_specs, tlc_passed, has_counterexample >>
one_shot_loop_ReceiveResponse == /\ pc["main"] = "ReceiveResponse"
                   /\ IF current_state = "prompting_llm"
                         THEN /\ current_state' = "extracting_fragment"
                              /\ dirty' = TRUE
                              /\ op' = "receive_response"
                              /\ result' = "ok"
                              /\ step_count' = step_count + 1
                         ELSE /\ op' = "response_skip"
                              /\ result' = "error"
                              /\ UNCHANGED << current_state, step_count, dirty >>
                   /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                   /\ UNCHANGED << consecutive_failures, compose_busy, 
                                   composed_specs, tlc_passed, 
                                   has_counterexample >>
one_shot_loop_ExtractFragment == /\ pc["main"] = "ExtractFragment"
                   /\ IF current_state = "extracting_fragment"
                         THEN /\ current_state' = "compiling"
                              /\ dirty' = TRUE
                              /\ op' = "extract_fragment"
                              /\ result' = "ok"
                              /\ step_count' = step_count + 1
                         ELSE /\ op' = "extract_skip"
                              /\ result' = "error"
                              /\ UNCHANGED << current_state, step_count, dirty >>
                   /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                   /\ UNCHANGED << consecutive_failures, compose_busy, 
                                   composed_specs, tlc_passed, 
                                   has_counterexample >>
one_shot_loop_CompilePlusCal == /\ pc["main"] = "CompilePlusCal"
                  /\ IF current_state = "compiling"
                        THEN /\ current_state' = "composing"
                             /\ compose_busy' = TRUE
                             /\ dirty' = TRUE
                             /\ op' = "compile"
                             /\ result' = "ok"
                             /\ step_count' = step_count + 1
                        ELSE /\ op' = "compile_skip"
                             /\ result' = "error"
                             /\ UNCHANGED << current_state, compose_busy, 
                                             step_count, dirty >>
                  /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                  /\ UNCHANGED << consecutive_failures, composed_specs, 
                                  tlc_passed, has_counterexample >>
one_shot_loop_ComposeSpecs == /\ pc["main"] = "ComposeSpecs"
                /\ IF current_state = "composing" /\ compose_busy = TRUE
                      THEN /\ composed_specs' = (composed_specs \union {"new_spec"})
                           /\ compose_busy' = FALSE
                           /\ current_state' = "verifying"
                           /\ dirty' = TRUE
                           /\ op' = "compose"
                           /\ result' = "ok"
                           /\ step_count' = step_count + 1
                      ELSE /\ op' = "compose_skip"
                           /\ result' = "error"
                           /\ UNCHANGED << current_state, compose_busy, 
                                           composed_specs, step_count, dirty >>
                /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                /\ UNCHANGED << consecutive_failures, tlc_passed, 
                                has_counterexample >>
one_shot_loop_RunTLC == /\ pc["main"] = "RunTLC"
          /\ IF current_state = "verifying"
                THEN /\ \/ /\ tlc_passed' = TRUE
                           /\ has_counterexample' = FALSE
                           /\ current_state' = "routing"
                           /\ dirty' = TRUE
                           /\ op' = "tlc_pass"
                           /\ result' = "pass"
                           /\ step_count' = step_count + 1
                        \/ /\ tlc_passed' = FALSE
                           /\ has_counterexample' = TRUE
                           /\ current_state' = "translating_error"
                           /\ dirty' = TRUE
                           /\ op' = "tlc_fail"
                           /\ result' = "fail"
                           /\ step_count' = step_count + 1
                        \/ /\ tlc_passed' = FALSE
                           /\ has_counterexample' = FALSE
                           /\ current_state' = "routing"
                           /\ dirty' = TRUE
                           /\ op' = "tlc_fail_no_ce"
                           /\ result' = "fail"
                           /\ step_count' = step_count + 1
                ELSE /\ op' = "tlc_skip"
                     /\ result' = "error"
                     /\ UNCHANGED << current_state, tlc_passed, 
                                     has_counterexample, step_count, dirty >>
          /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
          /\ UNCHANGED << consecutive_failures, compose_busy, composed_specs >>
one_shot_loop_TranslateError == /\ pc["main"] = "TranslateError"
                  /\ IF current_state = "translating_error"
                        THEN /\ current_state' = "routing"
                             /\ dirty' = TRUE
                             /\ op' = "translate_error"
                             /\ result' = "ok"
                             /\ step_count' = step_count + 1
                        ELSE /\ op' = "translate_skip"
                             /\ result' = "error"
                             /\ UNCHANGED << current_state, step_count, dirty >>
                  /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
                  /\ UNCHANGED << consecutive_failures, compose_busy, 
                                  composed_specs, tlc_passed, 
                                  has_counterexample >>
one_shot_loop_RouteResult == /\ pc["main"] = "RouteResult"
               /\ IF current_state = "routing"
                     THEN /\ IF tlc_passed = TRUE
                                THEN /\ current_state' = "done"
                                     /\ consecutive_failures' = 0
                                     /\ dirty' = TRUE
                                     /\ op' = "route_pass"
                                     /\ result' = "done"
                                     /\ step_count' = step_count + 1
                                ELSE /\ IF consecutive_failures > MaxRetries
                                           THEN /\ current_state' = "failed"
                                                /\ dirty' = TRUE
                                                /\ op' = "route_fail"
                                                /\ result' = "requirements_inconsistency"
                                                /\ step_count' = step_count + 1
                                                /\ UNCHANGED consecutive_failures
                                           ELSE /\ consecutive_failures' = consecutive_failures + 1
                                                /\ current_state' = "idle"
                                                /\ dirty' = TRUE
                                                /\ op' = "route_retry"
                                                /\ result' = "retry"
                                                /\ step_count' = step_count + 1
                     ELSE /\ op' = "route_skip"
                          /\ result' = "error"
                          /\ UNCHANGED << current_state, consecutive_failures, 
                                          step_count, dirty >>
               /\ pc' = [pc EXCEPT !["main"] = "UpdateDerived"]
               /\ UNCHANGED << compose_busy, composed_specs, tlc_passed, 
                               has_counterexample >>
one_shot_loop_loop == MainLoop \/ UpdateDerived \/ ReceiveBehavior \/ QueryContext
           \/ ReceiveResponse \/ ExtractFragment \/ CompilePlusCal
           \/ ComposeSpecs \/ RunTLC \/ TranslateError \/ RouteResult

\* --- Composed Init: bridge_translator.Init /\ one_shot_loop.Init ---
Init_composed ==
    \* From bridge_translator
    /\ (* Global variables *)
        /\ current_state = "idle"
        /\ vars_found = 0
        /\ actions_found = 0
        /\ invariants_found = 0
        /\ has_traces = FALSE
        /\ data_structures_out = 0
        /\ operations_out = 0
        /\ verifiers_out = 0
        /\ assertions_out = 0
        /\ scenarios_out = 0
        /\ schema_valid = TRUE
        /\ input_hash = 0
        /\ step_count = 0
        /\ op = "idle"
        /\ result = "none"
        /\ dirty = FALSE
        /\ pc = [self \in ProcSet |-> "MainLoop"]
    \* From one_shot_loop
    /\ (* Global variables *)
        /\ current_state = "idle"
        /\ consecutive_failures = 0
        /\ compose_busy = FALSE
        /\ composed_specs = {}
        /\ tlc_passed = FALSE
        /\ has_counterexample = FALSE
        /\ step_count = 0
        /\ op = "idle"
        /\ result = "none"
        /\ dirty = FALSE
        /\ pc = [self \in ProcSet |-> "MainLoop"]

\* --- Composed Next: bridge_translator.Next \/ one_shot_loop.Next ---
Next_composed ==
    \/ (bridge_translator_Next /\ UNCHANGED << compose_busy, composed_specs, consecutive_failures, has_counterexample, tlc_passed >>)
    \/ (one_shot_loop_Next /\ UNCHANGED << actions_found, assertions_out, data_structures_out, has_traces, input_hash, invariants_found, operations_out, scenarios_out, schema_valid, vars_found, verifiers_out >>)

\* --- Composed Invariants (referenced individually in .cfg) ---

Spec == Init_composed /\ [][Next_composed]_vars

===========================================================================