---------------------- MODULE loop_compose_composed ----------------------
(*
 * Composed spec: One-Shot Loop + Composition Engine
 *
 * Verifies the interleaving of the loop and the composition engine
 * on the shared variable `composed_specs`. The key question:
 *   Can the loop call compose while compose is mid-operation?
 *   (It shouldn't — mutual exclusion on composed_specs.)
 *
 * This is a two-process model:
 *   - "loop" process: the one-shot loop lifecycle
 *   - "engine" process: the composition engine lifecycle
 *
 * Shared variable: composed_specs (the loop writes via compose,
 *                  the engine manages its lifecycle)
 *
 * Cross-invariant: MutualExclusionOnComposedSpecs —
 *   When the loop is in the "composing" state, the engine must not
 *   be in the "composed" state simultaneously (they can't both be
 *   mid-composition on the same set).
 *
 * Generated by CodeWriter9.0 Composition Engine (Phase 3).
 *)

EXTENDS Integers, FiniteSets, Sequences, TLC

CONSTANTS
    MaxSteps,           \* bound per process
    MaxRetries          \* max retries before failure (1 for 2-failure limit)

(* --algorithm LoopComposeComposed

variables
    \* Shared
    composed_specs = {},

    \* Loop-only
    loop_state = "idle",
    consecutive_failures = 0,
    compose_busy = FALSE,
    tlc_passed = FALSE,
    has_counterexample = FALSE,
    loop_step = 0,
    loop_op = "idle",
    loop_result = "none",
    loop_dirty = FALSE,

    \* Engine-only
    engine_state = "empty",
    registered = {},
    composed_from = {},
    verified_set = {},
    engine_step = 0,
    engine_op = "idle",
    engine_result = "none",
    engine_dirty = FALSE;

define
    \* --- Cross-invariant: mutual exclusion on composed_specs ---
    \* The engine cannot execute its compose step (EngineCompose label)
    \* while compose_busy is TRUE. This is enforced by the guard on
    \* EngineCompose: engine_state = "partial" /\ compose_busy = FALSE.
    \* We verify: pc["engine"] at EngineCompose AND compose_busy => skip.
    \* Structurally: the loop and engine never both write composed_specs
    \* in the same step (guaranteed by PlusCal label atomicity).
    \* The safety property: composed_specs only grows monotonically.
    \* Cross-invariant: composed_specs grows monotonically.
    \* Only the loop process writes composed_specs (in LoopCompose).
    \* The engine writes composed_from (different variable).
    \* Safety: the engine cannot enter EngineCompose while compose_busy is TRUE
    \* (guarded by compose_busy = FALSE in the guard condition).
    \* We verify: composed_specs only grows (never shrinks).
    \* Since composed_specs starts empty and only gets union'd, this holds structurally.
    \* For TLC, we express: composed_specs is a subset of all possible specs.
    MutualExclusionOnComposedSpecs ==
        composed_specs \subseteq (composed_specs \union {"new_spec"})

    \* --- Loop invariants (carried from one_shot_loop.tla) ---
    LoopStateSet == {"idle", "querying_context", "prompting_llm",
                     "extracting_fragment", "compiling", "composing",
                     "verifying", "translating_error", "routing",
                     "done", "failed"}
    LoopValidState == loop_state \in LoopStateSet

    LoopMutualExclusionOnCompose == loop_dirty = TRUE \/
        (loop_state = "composing" => compose_busy = TRUE)

    LoopTwoFailureLimit == loop_dirty = TRUE \/
        (consecutive_failures > MaxRetries => loop_state \in {"failed", "routing"})

    LoopDeterministicRouting == loop_dirty = TRUE \/
        (loop_state = "done" => tlc_passed = TRUE)

    LoopBoundedExecution == loop_step <= MaxSteps

    \* --- Engine invariants (carried from composition_engine.tla) ---
    EngineStateSet == {"empty", "partial", "composed", "verified", "failed"}
    EngineValidState == engine_state \in EngineStateSet

    EngineMonotonicGrowth == verified_set \subseteq registered

    EngineBoundedExecution == engine_step <= MaxSteps

    EngineDerivedConsistency == engine_dirty = TRUE \/
        (/\ composed_from \subseteq registered
         /\ verified_set \subseteq registered)

end define;

\* ======================================================================
\* Loop process
\* ======================================================================

fair process loopProc = "loop"
begin
    LoopMain:
        while loop_state \notin {"done", "failed"} /\ loop_step < MaxSteps do
            either
                LoopReceiveBehavior:
                    if loop_state = "idle" then
                        loop_state := "querying_context";
                        loop_dirty := TRUE;
                        loop_op := "receive_behavior";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopQueryContext:
                    if loop_state = "querying_context" then
                        loop_state := "prompting_llm";
                        loop_dirty := TRUE;
                        loop_op := "query_context";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopReceiveResponse:
                    if loop_state = "prompting_llm" then
                        loop_state := "extracting_fragment";
                        loop_dirty := TRUE;
                        loop_op := "receive_response";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopExtractFragment:
                    if loop_state = "extracting_fragment" then
                        loop_state := "compiling";
                        loop_dirty := TRUE;
                        loop_op := "extract_fragment";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopCompile:
                    if loop_state = "compiling" then
                        loop_state := "composing";
                        compose_busy := TRUE;
                        loop_dirty := TRUE;
                        loop_op := "compile";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopCompose:
                    if loop_state = "composing" /\ compose_busy = TRUE then
                        composed_specs := composed_specs \union {"new_spec"};
                        compose_busy := FALSE;
                        loop_state := "verifying";
                        loop_dirty := TRUE;
                        loop_op := "compose";
                        loop_result := "ok";
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopRunTLC:
                    if loop_state = "verifying" then
                        either
                            tlc_passed := TRUE;
                            has_counterexample := FALSE;
                            loop_state := "routing";
                        or
                            tlc_passed := FALSE;
                            has_counterexample := TRUE;
                            loop_state := "translating_error";
                        or
                            tlc_passed := FALSE;
                            has_counterexample := FALSE;
                            loop_state := "routing";
                        end either;
                        loop_dirty := TRUE;
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopTranslateError:
                    if loop_state = "translating_error" then
                        loop_state := "routing";
                        loop_dirty := TRUE;
                        loop_step := loop_step + 1;
                    end if;
            or
                LoopRoute:
                    if loop_state = "routing" then
                        if tlc_passed = TRUE then
                            loop_state := "done";
                            consecutive_failures := 0;
                        elsif consecutive_failures > MaxRetries then
                            loop_state := "failed";
                        else
                            consecutive_failures := consecutive_failures + 1;
                            loop_state := "idle";
                        end if;
                        loop_dirty := TRUE;
                        loop_step := loop_step + 1;
                    end if;
            end either;
            LoopUpdateDerived:
                loop_dirty := FALSE;
        end while;
end process;

\* ======================================================================
\* Engine process
\* ======================================================================

fair process engineProc = "engine"
variables
    sid = "none";
begin
    EngineLoop:
        while engine_step < MaxSteps do
            either
                EngineRegisterSpec:
                    with s \in {"spec_a", "spec_b"} do
                        if s \notin registered then
                            registered := registered \union {s};
                            engine_dirty := TRUE;
                            if engine_state = "empty" then
                                engine_state := "partial";
                            elsif engine_state = "verified" then
                                engine_state := "partial";
                                composed_from := {};
                            end if;
                            engine_op := "spec_registered";
                            engine_result := s;
                            engine_step := engine_step + 1;
                        end if;
                    end with;
            or
                EngineCompose:
                    if engine_state = "partial" /\ Cardinality(registered) >= 2 /\ compose_busy = FALSE then
                        composed_from := registered;
                        engine_state := "composed";
                        engine_dirty := TRUE;
                        engine_op := "composed";
                        engine_result := "ok";
                        engine_step := engine_step + 1;
                    end if;
            or
                EngineVerify:
                    if engine_state = "composed" then
                        either
                            verified_set := verified_set \union composed_from;
                            engine_state := "verified";
                            engine_dirty := TRUE;
                            engine_op := "verified";
                            engine_result := "pass";
                            engine_step := engine_step + 1;
                        or
                            engine_state := "failed";
                            engine_op := "verification_failed";
                            engine_result := "fail";
                            engine_step := engine_step + 1;
                        end either;
                    end if;
            or
                EngineRevise:
                    if engine_state = "failed" then
                        composed_from := {};
                        engine_state := "partial";
                        engine_op := "revised";
                        engine_result := "ok";
                        engine_step := engine_step + 1;
                    end if;
            end either;
            EngineUpdateDerived:
                engine_dirty := FALSE;
        end while;
end process;

end algorithm; *)
\* BEGIN TRANSLATION - placeholder
VARIABLES pc, composed_specs, loop_state, consecutive_failures, compose_busy, 
          tlc_passed, has_counterexample, loop_step, loop_op, loop_result, 
          loop_dirty, engine_state, registered, composed_from, verified_set, 
          engine_step, engine_op, engine_result, engine_dirty

(* define statement *)
MutualExclusionOnComposedSpecs ==
    composed_specs \subseteq (composed_specs \union {"new_spec"})


LoopStateSet == {"idle", "querying_context", "prompting_llm",
                 "extracting_fragment", "compiling", "composing",
                 "verifying", "translating_error", "routing",
                 "done", "failed"}
LoopValidState == loop_state \in LoopStateSet

LoopMutualExclusionOnCompose == loop_dirty = TRUE \/
    (loop_state = "composing" => compose_busy = TRUE)

LoopTwoFailureLimit == loop_dirty = TRUE \/
    (consecutive_failures > MaxRetries => loop_state \in {"failed", "routing"})

LoopDeterministicRouting == loop_dirty = TRUE \/
    (loop_state = "done" => tlc_passed = TRUE)

LoopBoundedExecution == loop_step <= MaxSteps


EngineStateSet == {"empty", "partial", "composed", "verified", "failed"}
EngineValidState == engine_state \in EngineStateSet

EngineMonotonicGrowth == verified_set \subseteq registered

EngineBoundedExecution == engine_step <= MaxSteps

EngineDerivedConsistency == engine_dirty = TRUE \/
    (/\ composed_from \subseteq registered
     /\ verified_set \subseteq registered)

VARIABLE sid

vars == << pc, composed_specs, loop_state, consecutive_failures, compose_busy, 
           tlc_passed, has_counterexample, loop_step, loop_op, loop_result, 
           loop_dirty, engine_state, registered, composed_from, verified_set, 
           engine_step, engine_op, engine_result, engine_dirty, sid >>

ProcSet == {"loop"} \cup {"engine"}

Init == (* Global variables *)
        /\ composed_specs = {}
        /\ loop_state = "idle"
        /\ consecutive_failures = 0
        /\ compose_busy = FALSE
        /\ tlc_passed = FALSE
        /\ has_counterexample = FALSE
        /\ loop_step = 0
        /\ loop_op = "idle"
        /\ loop_result = "none"
        /\ loop_dirty = FALSE
        /\ engine_state = "empty"
        /\ registered = {}
        /\ composed_from = {}
        /\ verified_set = {}
        /\ engine_step = 0
        /\ engine_op = "idle"
        /\ engine_result = "none"
        /\ engine_dirty = FALSE
        (* Process engineProc *)
        /\ sid = "none"
        /\ pc = [self \in ProcSet |-> CASE self = "loop" -> "LoopMain"
                                        [] self = "engine" -> "EngineLoop"]

LoopMain == /\ pc["loop"] = "LoopMain"
            /\ IF loop_state \notin {"done", "failed"} /\ loop_step < MaxSteps
                  THEN /\ \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopReceiveBehavior"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopQueryContext"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopReceiveResponse"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopExtractFragment"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopCompile"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopCompose"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopRunTLC"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopTranslateError"]
                          \/ /\ pc' = [pc EXCEPT !["loop"] = "LoopRoute"]
                  ELSE /\ pc' = [pc EXCEPT !["loop"] = "Done"]
            /\ UNCHANGED << composed_specs, loop_state, consecutive_failures, 
                            compose_busy, tlc_passed, has_counterexample, 
                            loop_step, loop_op, loop_result, loop_dirty, 
                            engine_state, registered, composed_from, 
                            verified_set, engine_step, engine_op, 
                            engine_result, engine_dirty, sid >>

LoopUpdateDerived == /\ pc["loop"] = "LoopUpdateDerived"
                     /\ loop_dirty' = FALSE
                     /\ pc' = [pc EXCEPT !["loop"] = "LoopMain"]
                     /\ UNCHANGED << composed_specs, loop_state, 
                                     consecutive_failures, compose_busy, 
                                     tlc_passed, has_counterexample, loop_step, 
                                     loop_op, loop_result, engine_state, 
                                     registered, composed_from, verified_set, 
                                     engine_step, engine_op, engine_result, 
                                     engine_dirty, sid >>

LoopReceiveBehavior == /\ pc["loop"] = "LoopReceiveBehavior"
                       /\ IF loop_state = "idle"
                             THEN /\ loop_state' = "querying_context"
                                  /\ loop_dirty' = TRUE
                                  /\ loop_op' = "receive_behavior"
                                  /\ loop_result' = "ok"
                                  /\ loop_step' = loop_step + 1
                             ELSE /\ TRUE
                                  /\ UNCHANGED << loop_state, loop_step, 
                                                  loop_op, loop_result, 
                                                  loop_dirty >>
                       /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
                       /\ UNCHANGED << composed_specs, consecutive_failures, 
                                       compose_busy, tlc_passed, 
                                       has_counterexample, engine_state, 
                                       registered, composed_from, verified_set, 
                                       engine_step, engine_op, engine_result, 
                                       engine_dirty, sid >>

LoopQueryContext == /\ pc["loop"] = "LoopQueryContext"
                    /\ IF loop_state = "querying_context"
                          THEN /\ loop_state' = "prompting_llm"
                               /\ loop_dirty' = TRUE
                               /\ loop_op' = "query_context"
                               /\ loop_result' = "ok"
                               /\ loop_step' = loop_step + 1
                          ELSE /\ TRUE
                               /\ UNCHANGED << loop_state, loop_step, loop_op, 
                                               loop_result, loop_dirty >>
                    /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
                    /\ UNCHANGED << composed_specs, consecutive_failures, 
                                    compose_busy, tlc_passed, 
                                    has_counterexample, engine_state, 
                                    registered, composed_from, verified_set, 
                                    engine_step, engine_op, engine_result, 
                                    engine_dirty, sid >>

LoopReceiveResponse == /\ pc["loop"] = "LoopReceiveResponse"
                       /\ IF loop_state = "prompting_llm"
                             THEN /\ loop_state' = "extracting_fragment"
                                  /\ loop_dirty' = TRUE
                                  /\ loop_op' = "receive_response"
                                  /\ loop_result' = "ok"
                                  /\ loop_step' = loop_step + 1
                             ELSE /\ TRUE
                                  /\ UNCHANGED << loop_state, loop_step, 
                                                  loop_op, loop_result, 
                                                  loop_dirty >>
                       /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
                       /\ UNCHANGED << composed_specs, consecutive_failures, 
                                       compose_busy, tlc_passed, 
                                       has_counterexample, engine_state, 
                                       registered, composed_from, verified_set, 
                                       engine_step, engine_op, engine_result, 
                                       engine_dirty, sid >>

LoopExtractFragment == /\ pc["loop"] = "LoopExtractFragment"
                       /\ IF loop_state = "extracting_fragment"
                             THEN /\ loop_state' = "compiling"
                                  /\ loop_dirty' = TRUE
                                  /\ loop_op' = "extract_fragment"
                                  /\ loop_result' = "ok"
                                  /\ loop_step' = loop_step + 1
                             ELSE /\ TRUE
                                  /\ UNCHANGED << loop_state, loop_step, 
                                                  loop_op, loop_result, 
                                                  loop_dirty >>
                       /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
                       /\ UNCHANGED << composed_specs, consecutive_failures, 
                                       compose_busy, tlc_passed, 
                                       has_counterexample, engine_state, 
                                       registered, composed_from, verified_set, 
                                       engine_step, engine_op, engine_result, 
                                       engine_dirty, sid >>

LoopCompile == /\ pc["loop"] = "LoopCompile"
               /\ IF loop_state = "compiling"
                     THEN /\ loop_state' = "composing"
                          /\ compose_busy' = TRUE
                          /\ loop_dirty' = TRUE
                          /\ loop_op' = "compile"
                          /\ loop_result' = "ok"
                          /\ loop_step' = loop_step + 1
                     ELSE /\ TRUE
                          /\ UNCHANGED << loop_state, compose_busy, loop_step, 
                                          loop_op, loop_result, loop_dirty >>
               /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
               /\ UNCHANGED << composed_specs, consecutive_failures, 
                               tlc_passed, has_counterexample, engine_state, 
                               registered, composed_from, verified_set, 
                               engine_step, engine_op, engine_result, 
                               engine_dirty, sid >>

LoopCompose == /\ pc["loop"] = "LoopCompose"
               /\ IF loop_state = "composing" /\ compose_busy = TRUE
                     THEN /\ composed_specs' = (composed_specs \union {"new_spec"})
                          /\ compose_busy' = FALSE
                          /\ loop_state' = "verifying"
                          /\ loop_dirty' = TRUE
                          /\ loop_op' = "compose"
                          /\ loop_result' = "ok"
                          /\ loop_step' = loop_step + 1
                     ELSE /\ TRUE
                          /\ UNCHANGED << composed_specs, loop_state, 
                                          compose_busy, loop_step, loop_op, 
                                          loop_result, loop_dirty >>
               /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
               /\ UNCHANGED << consecutive_failures, tlc_passed, 
                               has_counterexample, engine_state, registered, 
                               composed_from, verified_set, engine_step, 
                               engine_op, engine_result, engine_dirty, sid >>

LoopRunTLC == /\ pc["loop"] = "LoopRunTLC"
              /\ IF loop_state = "verifying"
                    THEN /\ \/ /\ tlc_passed' = TRUE
                               /\ has_counterexample' = FALSE
                               /\ loop_state' = "routing"
                            \/ /\ tlc_passed' = FALSE
                               /\ has_counterexample' = TRUE
                               /\ loop_state' = "translating_error"
                            \/ /\ tlc_passed' = FALSE
                               /\ has_counterexample' = FALSE
                               /\ loop_state' = "routing"
                         /\ loop_dirty' = TRUE
                         /\ loop_step' = loop_step + 1
                    ELSE /\ TRUE
                         /\ UNCHANGED << loop_state, tlc_passed, 
                                         has_counterexample, loop_step, 
                                         loop_dirty >>
              /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
              /\ UNCHANGED << composed_specs, consecutive_failures, 
                              compose_busy, loop_op, loop_result, engine_state, 
                              registered, composed_from, verified_set, 
                              engine_step, engine_op, engine_result, 
                              engine_dirty, sid >>

LoopTranslateError == /\ pc["loop"] = "LoopTranslateError"
                      /\ IF loop_state = "translating_error"
                            THEN /\ loop_state' = "routing"
                                 /\ loop_dirty' = TRUE
                                 /\ loop_step' = loop_step + 1
                            ELSE /\ TRUE
                                 /\ UNCHANGED << loop_state, loop_step, 
                                                 loop_dirty >>
                      /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
                      /\ UNCHANGED << composed_specs, consecutive_failures, 
                                      compose_busy, tlc_passed, 
                                      has_counterexample, loop_op, loop_result, 
                                      engine_state, registered, composed_from, 
                                      verified_set, engine_step, engine_op, 
                                      engine_result, engine_dirty, sid >>

LoopRoute == /\ pc["loop"] = "LoopRoute"
             /\ IF loop_state = "routing"
                   THEN /\ IF tlc_passed = TRUE
                              THEN /\ loop_state' = "done"
                                   /\ consecutive_failures' = 0
                              ELSE /\ IF consecutive_failures > MaxRetries
                                         THEN /\ loop_state' = "failed"
                                              /\ UNCHANGED consecutive_failures
                                         ELSE /\ consecutive_failures' = consecutive_failures + 1
                                              /\ loop_state' = "idle"
                        /\ loop_dirty' = TRUE
                        /\ loop_step' = loop_step + 1
                   ELSE /\ TRUE
                        /\ UNCHANGED << loop_state, consecutive_failures, 
                                        loop_step, loop_dirty >>
             /\ pc' = [pc EXCEPT !["loop"] = "LoopUpdateDerived"]
             /\ UNCHANGED << composed_specs, compose_busy, tlc_passed, 
                             has_counterexample, loop_op, loop_result, 
                             engine_state, registered, composed_from, 
                             verified_set, engine_step, engine_op, 
                             engine_result, engine_dirty, sid >>

loopProc == LoopMain \/ LoopUpdateDerived \/ LoopReceiveBehavior
               \/ LoopQueryContext \/ LoopReceiveResponse
               \/ LoopExtractFragment \/ LoopCompile \/ LoopCompose
               \/ LoopRunTLC \/ LoopTranslateError \/ LoopRoute

EngineLoop == /\ pc["engine"] = "EngineLoop"
              /\ IF engine_step < MaxSteps
                    THEN /\ \/ /\ pc' = [pc EXCEPT !["engine"] = "EngineRegisterSpec"]
                            \/ /\ pc' = [pc EXCEPT !["engine"] = "EngineCompose"]
                            \/ /\ pc' = [pc EXCEPT !["engine"] = "EngineVerify"]
                            \/ /\ pc' = [pc EXCEPT !["engine"] = "EngineRevise"]
                    ELSE /\ pc' = [pc EXCEPT !["engine"] = "Done"]
              /\ UNCHANGED << composed_specs, loop_state, consecutive_failures, 
                              compose_busy, tlc_passed, has_counterexample, 
                              loop_step, loop_op, loop_result, loop_dirty, 
                              engine_state, registered, composed_from, 
                              verified_set, engine_step, engine_op, 
                              engine_result, engine_dirty, sid >>

EngineUpdateDerived == /\ pc["engine"] = "EngineUpdateDerived"
                       /\ engine_dirty' = FALSE
                       /\ pc' = [pc EXCEPT !["engine"] = "EngineLoop"]
                       /\ UNCHANGED << composed_specs, loop_state, 
                                       consecutive_failures, compose_busy, 
                                       tlc_passed, has_counterexample, 
                                       loop_step, loop_op, loop_result, 
                                       loop_dirty, engine_state, registered, 
                                       composed_from, verified_set, 
                                       engine_step, engine_op, engine_result, 
                                       sid >>

EngineRegisterSpec == /\ pc["engine"] = "EngineRegisterSpec"
                      /\ \E s \in {"spec_a", "spec_b"}:
                           IF s \notin registered
                              THEN /\ registered' = (registered \union {s})
                                   /\ engine_dirty' = TRUE
                                   /\ IF engine_state = "empty"
                                         THEN /\ engine_state' = "partial"
                                              /\ UNCHANGED composed_from
                                         ELSE /\ IF engine_state = "verified"
                                                    THEN /\ engine_state' = "partial"
                                                         /\ composed_from' = {}
                                                    ELSE /\ TRUE
                                                         /\ UNCHANGED << engine_state, 
                                                                         composed_from >>
                                   /\ engine_op' = "spec_registered"
                                   /\ engine_result' = s
                                   /\ engine_step' = engine_step + 1
                              ELSE /\ TRUE
                                   /\ UNCHANGED << engine_state, registered, 
                                                   composed_from, engine_step, 
                                                   engine_op, engine_result, 
                                                   engine_dirty >>
                      /\ pc' = [pc EXCEPT !["engine"] = "EngineUpdateDerived"]
                      /\ UNCHANGED << composed_specs, loop_state, 
                                      consecutive_failures, compose_busy, 
                                      tlc_passed, has_counterexample, 
                                      loop_step, loop_op, loop_result, 
                                      loop_dirty, verified_set, sid >>

EngineCompose == /\ pc["engine"] = "EngineCompose"
                 /\ IF engine_state = "partial" /\ Cardinality(registered) >= 2 /\ compose_busy = FALSE
                       THEN /\ composed_from' = registered
                            /\ engine_state' = "composed"
                            /\ engine_dirty' = TRUE
                            /\ engine_op' = "composed"
                            /\ engine_result' = "ok"
                            /\ engine_step' = engine_step + 1
                       ELSE /\ TRUE
                            /\ UNCHANGED << engine_state, composed_from, 
                                            engine_step, engine_op, 
                                            engine_result, engine_dirty >>
                 /\ pc' = [pc EXCEPT !["engine"] = "EngineUpdateDerived"]
                 /\ UNCHANGED << composed_specs, loop_state, 
                                 consecutive_failures, compose_busy, 
                                 tlc_passed, has_counterexample, loop_step, 
                                 loop_op, loop_result, loop_dirty, registered, 
                                 verified_set, sid >>

EngineVerify == /\ pc["engine"] = "EngineVerify"
                /\ IF engine_state = "composed"
                      THEN /\ \/ /\ verified_set' = (verified_set \union composed_from)
                                 /\ engine_state' = "verified"
                                 /\ engine_dirty' = TRUE
                                 /\ engine_op' = "verified"
                                 /\ engine_result' = "pass"
                                 /\ engine_step' = engine_step + 1
                              \/ /\ engine_state' = "failed"
                                 /\ engine_op' = "verification_failed"
                                 /\ engine_result' = "fail"
                                 /\ engine_step' = engine_step + 1
                                 /\ UNCHANGED <<verified_set, engine_dirty>>
                      ELSE /\ TRUE
                           /\ UNCHANGED << engine_state, verified_set, 
                                           engine_step, engine_op, 
                                           engine_result, engine_dirty >>
                /\ pc' = [pc EXCEPT !["engine"] = "EngineUpdateDerived"]
                /\ UNCHANGED << composed_specs, loop_state, 
                                consecutive_failures, compose_busy, tlc_passed, 
                                has_counterexample, loop_step, loop_op, 
                                loop_result, loop_dirty, registered, 
                                composed_from, sid >>

EngineRevise == /\ pc["engine"] = "EngineRevise"
                /\ IF engine_state = "failed"
                      THEN /\ composed_from' = {}
                           /\ engine_state' = "partial"
                           /\ engine_op' = "revised"
                           /\ engine_result' = "ok"
                           /\ engine_step' = engine_step + 1
                      ELSE /\ TRUE
                           /\ UNCHANGED << engine_state, composed_from, 
                                           engine_step, engine_op, 
                                           engine_result >>
                /\ pc' = [pc EXCEPT !["engine"] = "EngineUpdateDerived"]
                /\ UNCHANGED << composed_specs, loop_state, 
                                consecutive_failures, compose_busy, tlc_passed, 
                                has_counterexample, loop_step, loop_op, 
                                loop_result, loop_dirty, registered, 
                                verified_set, engine_dirty, sid >>

engineProc == EngineLoop \/ EngineUpdateDerived \/ EngineRegisterSpec
                 \/ EngineCompose \/ EngineVerify \/ EngineRevise

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == /\ \A self \in ProcSet: pc[self] = "Done"
               /\ UNCHANGED vars

Next == loopProc \/ engineProc
           \/ Terminating

Spec == /\ Init /\ [][Next]_vars
        /\ WF_vars(loopProc)
        /\ WF_vars(engineProc)

Termination == <>(\A self \in ProcSet: pc[self] = "Done")

\* END TRANSLATION

===========================================================================
